### ISSUE TITLE
How to use the same snapping for scrolling with a trackpad?

### ISSUE THREAD

**Issue by chrisneven** [rcbyr/keen-slider#1]
I saw your post on reddit and I have to say, I'm really glad I found out about this library! Definitely the best one out there with the most native feeling indeed.

However, I was wondering if it's supported to use the snapping when just scrolling? Like with a trackpad for example. I created a [repo](https://codesandbox.io/s/twilight-frost-r7y3o?file=/src/App.tsx) where I tried to use css scrollsnapping as well, but this won't work as all "children" are positioned absolute. 

Is there a way to achieve this? Or is it not supported, which I could also understand.

**Comment by rcbyr** [comment]
Thank you so much. 
I think css scrollsnapping will not be supported in the near future.

But trackpad/scroll support is almost at the top of my todo list.

**Comment by rcbyr** [comment]
I made an example of how to add a wheel support for the slider. https://keen-slider.io/examples#scroll-wheel-controls

**Comment by chrisneven** [comment]
@rcbyr awesome!

Thanks again for this super cool package!
