### ISSUE TITLE
Animate the slider only if next slide is not visible ?

### ISSUE THREAD

**Issue by flackeryy** [rcbyr/keen-slider#100]
Hi

First of all, I want to say that the current behaviour works very well for all general cases.

For example, when you have a single slider with `slidesPerView: 4`, and when you click `next` button, you would like to see the 5th slide, instead of just make the second slide active. The current behaviour is below

![CleanShot 2021-03-17 at 3 13 30](https://user-images.githubusercontent.com/23479556/111473190-70c56a80-8733-11eb-8009-f7e926ad6486.gif)

**But**, in my case, I was needed to build a Slider with the navigation (e.g. combine 2 sliders). As an example, the `slick` slider has an ability `asNavFor` that gives the appropriate result, but here I didn't found a ready solution so made it on my own.

Here is the sandbox link (https://codesandbox.io/s/solitary-dew-1coi2?fontsize=14&hidenavigation=1&theme=dark)

But the issue in my case, that the navigation slider triggers the slide animation each time the currentSlide is changed. And stops the animation only when the slider reaches its limit. 

![CleanShot 2021-03-17 at 3 28 07](https://user-images.githubusercontent.com/23479556/111475116-6e641000-8735-11eb-90d1-416bdfd643d3.gif)

What I expect to have is that the navigation slider doesn't run the slide animation if the currentSlide is in the visible viewport. The expected behaviour is present when I change slides on the "last" page (so there are no more slides), otherwise, the animation occurs.

![CleanShot 2021-03-17 at 3 34 59](https://user-images.githubusercontent.com/23479556/111476033-63f64600-8736-11eb-9b16-03f1bc59de7b.gif)

**My questions is**: is it possible to implement the expected behaviour? Of course, it would be perfect to have a config option, like `animateVisibleSlides` that will be `true` by default (the current behaviour), but it can be set to false to disable the animation. I understand that updating the package functional might take some time, so just asking for any ideas of how to implement it on my side?

I hope the explanation is clear :) But please let me know if more details needed.

**Comment by rcbyr** [comment]
Hey @flackeryy 

sorry for the very late answer. Here is a codesandbox: https://codesandbox.io/s/relaxed-noether-qe3hgl?file=/index.html
