### ISSUE TITLE
BUG: Drag does not work on IE11

### ISSUE THREAD

**Issue by igorfv** [rcbyr/keen-slider#101]
Drag does not work when dragging from the slide but it works fine when dragging from the empty space between the slides.

![Mar-17-2021 14-36-45](https://user-images.githubusercontent.com/191252/111512198-41f8c580-872e-11eb-9508-5002b31b404d.gif)

**How to test:**
Open https://keen-slider.io/examples/#examples on IE11

PS: The keen-slider site is also kinda broken on IE11.

**Comment by igorfv** [comment]
The last version that works on IE 11 is 4.2.6

**Comment by igorfv** [comment]
The problem is the `pointer-events:none` on the CSS. There's a known IE bug.
A solution would be using a IE10/11 specific CSS to revert this change to auto:
```@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) { .keen-slider[data-keen-slider-moves] *{pointer-events:auto} }```

**Comment by rcbyr** [comment]
Tested with v6.6.9. Works fine. Thanks for the hint!
