### ISSUE TITLE
Error: Invalid hook call.

### ISSUE THREAD

**Issue by baptisteArno** [rcbyr/keen-slider#103]
I'm trying to add this lib in my Next.js project but I get this error:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

I tried everything, I checked those 3 possible reasons. Do you think it could be a bug from this library ? (I don't get this error when I'm using other hooks)

**Comment by mattrothenberg** [comment]
I'm using this just fine on a Next.js project – can you provide more context as to where you're invoking the hook?

**Comment by baptisteArno** [comment]
I updated my packages and it worked. It was probably due to my workspace setup 👍
