### ISSUE TITLE
Click on slide to navigate?

### ISSUE THREAD

**Issue by murray-b** [rcbyr/keen-slider#105]
Would be great if there was a way to click on the slide itself to move to it, instead of using drag or controls. 

We've tried implementing this on our own using `moveToSlide` function `onClick` of a slide, but occasionally the slider interprets the click as a drag and the event doesn't get registered.

Any suggestions?

**Comment by andrey-hohlov** [comment]
Works for me with handling event capturing phase (checked on Vue project)

```
@click.capture="next()"
```

**Comment by rcbyr** [comment]
@andrey-hohlov Good solution. Thanks for the clarification!
