### ISSUE TITLE
Invalid absoluteSlide calculation with float slidesPerView

### ISSUE THREAD

**Issue by andrey-hohlov** [rcbyr/keen-slider#106]
Hi,
It's a super feature to use float value to define slider per view. But I faced a problem.

I need to show/hide prev/next arrows. Prev is visible if active slide > 0, next is visible if active slide is not the last.

Look at this example: https://codesandbox.io/s/busy-bhaskara-n7rc0?file=/src/index.js

When you move to the last slide:
- ```slideChanged``` event never fires
- ```absoluteSlide``` value points to previous slide

So, the only way to detect if end reached is to check:

```
const { absoluteSlide, size, positions } = e.details();

if (absoluteSlide === size - 2) {
  const { portion } = positions[positions.length - 1];
  if (portion === 1) {
    // End reached!
  }
}
```

A bit ugly and sometimes ```portion``` is 0.99999...

The same example. Slide to the end and then click on the slider. It scrolls to the second slide.
Video: https://monosnap.com/file/eY7IxPU9x9jLA91Nq368OmUGJwi3M8

Like it doesn't think the last slide is a slide at all.

Use the same example, but change ```slidesPerView``` to 1.5.
It works!

I think the problem is here: https://github.com/rcbyr/keen-slider/blob/869d6a86d660ae5a5dec4bd78b7d29c11fd0491e/src/keen-slider.js#L676

Because of rounding sometimes it doesn't give a correct result.
Looks like the result is wrong if the float part is more than 0.5.
Like 1.5 works, 1.51 - doesn't work.

**Comment by rcbyr** [comment]
Thanks for the hint. The rounding problems are fixed in the new major release.
