### ISSUE TITLE
Type 'Timeout' is not assignable to type 'undefined'

### ISSUE THREAD

**Issue by codthing** [rcbyr/keen-slider#109]
Very good library. But it seems not very friendly to TypeScript.
When I use the library in a React application with TS, I just want to autoplay, but I get an error:

![image](https://user-images.githubusercontent.com/16655229/116513420-23284a00-a8fc-11eb-9856-f5e22be2bab2.png)

**Comment by gwadhwani** [comment]
You need to define type for your timer like so:

`const timer = useRef<ReturnType<typeof setInterval>>(null);`

This will allow typescript to know your timer's type and won't complain about the mentioned error.

**Comment by rcbyr** [comment]
@gwadhwani Thank you for your clarification.
