### ISSUE TITLE
Slide for other actions?

### ISSUE THREAD

**Issue by DamianRivas** [rcbyr/keen-slider#11]
Would you happen to have a blog post or resource about how you implemented native-like sliding?

I'm working on an application where I want users to slide to flip flash cards so your package stood out to me in this week's issue of JS Weekly. Next time I need a carousel I'll be sure to give this package a try 😊

**Comment by rcbyr** [comment]
Hallo @DamianRivas,

Unfortunately, no. I searched for a lib with native behavior and found nothing (to be honest, I didn't search too long). So I decided to give it a try, and in every iteration, I got closer. But I still have a lot of ideas to make it even better.

Maybe reading my code will help. Especially in the "event section". It's a lot about preventing standard behavior at the right moments.

**Comment by DamianRivas** [comment]
@rcbyr I will definitely study the source as a reference. Thank you! I'm looking forward to seeing the advances you make in this code
