### ISSUE TITLE
Incorrect return type for `useKeenSlider`

### ISSUE THREAD

**Issue by YauheniKhadanionak** [rcbyr/keen-slider#110]
[Sandbox](https://codesandbox.io/s/bold-babbage-5et7p)

Inside **useKeenSlider** you use **useState** with default `null` value and then return **slider**
https://github.com/rcbyr/keen-slider/blob/869d6a86d660ae5a5dec4bd78b7d29c11fd0491e/src/react.js#L17-L26

So looks like **[THookReturn](https://github.com/rcbyr/keen-slider/blob/master/react.d.ts#L6)** type should be updated to
```ts
export type THookReturn<T extends HTMLElement> = [
  React.RefObject<T>,
  KeenSlider | null
]
```

Thanks a lot for great library

**Comment by rcbyr** [comment]
Hello @YauheniKhadanionak 

sorry for the late answer and thank you very much for the hint. The typings should be correct in the new version.
