### ISSUE TITLE
Changing the width of centered - looping slides

### ISSUE THREAD

**Issue by IrvingArmenta** [rcbyr/keen-slider#113]
I'm wondering if there is a way to change the width of the centered and looping slides to perhaps `80%` or `70%` , something more than `50%` and keep them centered of course. 

I'm aware I can `!important`  the min-width styles but the  JS calculations get all messed up.  

Am I missing some specification or option?

**Comment by knenkne** [comment]
+

**Comment by chiranshu14** [comment]
What css class should we use to apply styles to the centered slide?

**Comment by rcbyr** [comment]
There are a few ways to achieve a width/height change for the centered or active slide. But the implementation depends on the desired behavior. I have created a possible solution and hope it helps: https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/centered/javascript?file=/index.html

**Comment by filippolcr** [comment]
Ehi @rcbyr, I've explored the codesandbox link that you've provided, but I don't see any changes compared to default examplle implementation. Can you check the link, please?

**Comment by filippolcr** [comment]
Exploring a little bit further, this [https://codesandbox.io/s/laughing-tree-xfzkx?file=/src/index.js:142-204](url) did the trick.

**Comment by jackgregory** [comment]
@rcbyr really keen to see this example as well. The sandbox you posted is just the default centred example. Could you share the one you created for @filippolcr ? Thanks!

**Comment by martdavidson** [comment]
@rcbyr Hey, did you mean to post a different link above? I can't figure out a way to resize a slide while navigating the carousel.

**Comment by VincentVToscano** [comment]
> Exploring a little bit further, this [https://codesandbox.io/s/laughing-tree-xfzkx?file=/src/index.js:142-204](url) did the trick.

By any chance @rcbyr did you happen to have a public link to your sandbox -- much thanks!

**Comment by d3v4nt** [comment]
Anyone got this one sorted out?

**Comment by VincentVToscano** [comment]
> Anyone got this one sorted out?

@d3v4nt  - Not yet
