### ISSUE TITLE
Slider inside slider

### ISSUE THREAD

**Issue by andrey-hohlov** [rcbyr/keen-slider#114]
_Like a products carousel where each product has its own photo gallery._

All slides swipe by the same time: https://codesandbox.io/s/twilight-hill-uzk1s?file=/index.html

A similar problem but with different direction https://github.com/rcbyr/keen-slider/issues/83

Any workaround?

**Comment by andrey-hohlov** [comment]
A common issue in another carousel https://github.com/davidcetinkaya/embla-carousel/issues/141 with some workround

**Comment by rcbyr** [comment]
Hey @andrey-hohlov,

I created a quick example: https://codesandbox.io/s/friendly-visvesvaraya-n5h7q?file=/index.html

Hope this helps!

**Comment by andrey-hohlov** [comment]
@rcbyr awesome!
