### ISSUE TITLE
Is it possible to Create multiple separate sliders with their combine keen-slider implementation?

### ISSUE THREAD

**Issue by ngtrian** [rcbyr/keen-slider#116]
How to handle if you want to apply slider to many element with different positions of the page? Then I want to use navigation arrow, so do I have to repeat the keen-slider implementations?

**Comment by lihuelworks** [comment]
Looking for this too. I have a for-loop that shows a different ammount of content depending the div, and only the first one gets shown right. The others try to "copy" the width calculation and end up completely squished (not having the same ammount of "keen-slides"

![image](https://user-images.githubusercontent.com/49965980/120740911-80e71d80-c4ca-11eb-95cb-3dcdf9b2cee8.png)

**Comment by jack-pallot** [comment]
Here's an example with multiple sliders - [https://codesandbox.io/s/charming-lovelace-h0or7](https://codesandbox.io/s/charming-lovelace-h0or7)

**Comment by rcbyr** [comment]
I think this can be closed. The only thing that is important is that each slider needs its own instance, then everything works.
