### ISSUE TITLE
Offset calculation is incorrect when container width is fractional

### ISSUE THREAD

**Issue by Jonne** [rcbyr/keen-slider#117]
See the example in the following sandbox. If you navigate to slide 3, you see part of slide 2 on the left.

https://codesandbox.io/s/epic-http-j134s

This is because the width of the container is 600.48 px

**Comment by allddarrass** [comment]
@rcbyr when this issue is going to fixed?

**Comment by rcbyr** [comment]
This is fixed in the new major version(v6).
