### ISSUE TITLE
Setting Fixable width and height on keen-slider__slide makes the items not remain in one line

### ISSUE THREAD

**Issue by JudeTejada** [rcbyr/keen-slider#120]
I have a property set on my slider which would only shows  3 items. but When I try to add a fixable width and height it no longer show 3 items on the slider but more than 6, and this is due to how the keen slider set the height of each item depending on `slidesPerView`

```
  const [sliderRef, slider] = useKeenSlider({
    slideChanged(s) {
      setCurrentSlide(s.details().relativeSlide);
    },
    spacing: 10,
    slidesPerView: 3,
    centered: true,
    vertical: true,
    loop: false,
    initial: 0,
  });

````

What It would look like if removed fixed width and height

![image](https://user-images.githubusercontent.com/29864561/120967382-3a88fd00-c71c-11eb-88fe-5146625105f4.png)

With Fixed and Height
I had set each item with
```
  minHeight: "5.6rem !important",
    maxHeight: "5.6rem !important",
    maxWidth: "5.6rem !important",
    minWidth: "5.6rem !important",
```

![image](https://user-images.githubusercontent.com/29864561/120967424-45439200-c71c-11eb-90fc-5dfb431098d3.png)

**Comment by rcbyr** [comment]
Sorry for the late answer. Setting fixed values for width(if vertical=false) or height (if vertical=true) does not work for the slider(especially not in version 5). You just have to let the slider handle these values.
