### ISSUE TITLE
index.d.ts missing autoAdjustSlidesPerView?: boolean;

### ISSUE THREAD

**Issue by TheBenEdwards** [rcbyr/keen-slider#122]
I am having an issue with my TS project where I am trying to use `autoAdjustSlidesPerView: false` but keep getting the error 
`Object literal may only specify known properties, and 'autoAdjustSlidesPerView' does not exist in type 'TOptionsEvents'.ts`
Upon checking `index.d.ts` i noticed `TOptions` does not contain an `autoAdjustSlidesPerView?: boolean;` property. 
Is there something I am missing or is this intentional? Upon adding it myself on my local version it worked and I didn't have any more issues.

**Comment by rcbyr** [comment]
Fixed. Thank you very much!
