### ISSUE TITLE
Feature Request: Move the slider using the scroll wheel

### ISSUE THREAD

**Issue by seanhuggins1** [rcbyr/keen-slider#125]
Allowing the user to move the carousel with the mouse would make for a better user experience.
The combination of click-dragging functionality + scroll wheel functionality would make for the ultimate carousel.

I've tried to recreate the effect on this website https://prb-a.com/ using Flickity + Locomotive Scroll, unfortunately to no avail. But this site is a perfect example.

**Comment by jack-pallot** [comment]
Here's an example of adding mouse wheel support. It needs tuning and refining a bit, but maybe it will help [https://codesandbox.io/s/keen-slider-mousewheel-8w78p](https://codesandbox.io/s/keen-slider-mousewheel-8w78p)

**Comment by cabbageofficial198** [comment]
But in React, How I can add? I am using keenslider hook

**Comment by rcbyr** [comment]
I have added an example for this case. https://keen-slider.io/examples#scroll-wheel-controls

**Comment by dsbrianwebster** [comment]
Thank you @rcbyr 🔥

**Comment by tea-vitamin** [comment]
@rcbyr Is there a way to make it move horizontally while scrolling vertically?

**Comment by tea-vitamin** [comment]
Actually solved it by switching the x and y values here:
 function dispatch(e: WheelEvent, name: string) {
      position.x -= e.deltaX
      position.y -= e.deltaY
      slider.container.dispatchEvent(
        new CustomEvent(name, {
          detail: {
            // When scrolling vertically the slider moves horizontally
            x: position.y,
            y: position.x
          }
        })
      )
    }
