### ISSUE TITLE
Video inside slide starts playing in Firefox on drag instead of moving the slider.

### ISSUE THREAD

**Issue by sangeet** [rcbyr/keen-slider#127]
So, apparently the Firefox video isn't differentiating between the drag and click event and hence I'm unable to drag the slider when using Firefox. This issue is completely limited to Firefox and I haven't encountered the same behavior in Firefox or Brave (Chromium).

I read up and tried using "data-keen-slider-pe" but that didn't seem to help at all. Please correct me if my usage was incorrect but I added this attribute to the slider and slide in two separate tries and neither of them worked.

As it currently stands, any drag event on Firefox video doesn't drag the slides and just starts playing video instead which essentially makes dragging on it impossible. I'm attaching a video which demonstrates how differently Safari and Firefox are handling this.

Is there a way to work around this?

https://user-images.githubusercontent.com/346858/124233414-70a97900-db30-11eb-8687-79b7276c367d.mp4

html structure if curious :
```html
<div
  class="keen-slider overflow-visible-important"
  data-keen-slider-pe="true"
  style="scroll-behavior: unset;"
>
  <div
    class="keen-slider__slide number-slide0 pt-16 overflow-visible-important max-h-128"
    style="z-index: 30; min-width: calc(100% + 0px); max-width: calc(100% + 0px); transform: translate3d(-560px, 0px, 0px);"
  >
    <div
      style="transform: translateY(-2rem);"
      class="block link-no-effects transition-all duration-300 linear rounded-lg  shadow-jolly overflow-hidden -mx-5 h-full"
      href=""
    >
      <video
        src="https://dl.airtable.com/.attachments/b13cf5c8b122dcec554c1b8233636175/41964eb8/TamilNadilIndia1.mp4"
        controls=""
        class="h-full w-full bg-white"
      ></video>
    </div>
  </div>
  <!-- Slide repeated several times -->
</div>
```

**Comment by jack-pallot** [comment]
This looks more like differences in the browsers video player behavior than an actual bug to me. I think you're going to have issues with accidental clicks on mobile doing this as well. 

What you could do, is overlay a wrapper over the video, with a play button, essentially looking like a video player. Then use JS to play the video when clicked and pause the video when the slideChanged event happens. This will give you greater control over misfires like this.

**Comment by sangeet** [comment]
I know it's a bit of a idealistic assumption, but shouldn't the slider anyway handle drag and click on it's own rather than the embedded object dictating it?

You firstly interact with the slider and then the content inside slides. Perhaps this could be handled in the slider and perhaps an option added to override custom behavior instead of the touch/click events being passed to the slide component by default and causing conflicts.

**Comment by sangeet** [comment]
For now, I added a button positioned `absolute` on top that hides or displays based on video is paused or not and that seems to do the job fine for now.

```js
<div className={`h-full w-full ${className} relative`}>
      {state.paused && (
        <button
          className="absolute inset-0 h-full w-full bg-transparent"
          onClick={controls.play}
        />
      )}
      {video}
</div>
```
