### ISSUE TITLE
Slides disappear before they are fully transitioned out of the view when loop:true

### ISSUE THREAD

**Issue by sangeet** [rcbyr/keen-slider#128]
Hi @rcbyr @slavanossar

Related to https://github.com/rcbyr/keen-slider/issues/54

The suggested fix for this problem was adding a non-integer value for `slidesPerView`, but that did not fix this problem for me. Would it be possible to explain in a bit more detail what the fix for this is or perhaps documenting it since this seems to be a frequent problem for me.

Note that I have 5 slides per view and changing the number to 5.3 or nearby does make no difference. Is any solution for this possible?

https://user-images.githubusercontent.com/346858/124583510-bf2c7f80-de70-11eb-8713-4adc083159fa.mp4

**Comment by rcbyr** [comment]
Hey @sangeet, sorry for the late answer.

The problem is that your viewport is too large. Since the slides are not cloned to create a looping effect, there must be enough slides to fill the gap between the change to the other side. I hope this will help you!
