### ISSUE TITLE
Is it possible to change the ease when transitioning slides?

### ISSUE THREAD

**Issue by gitgudcameron** [rcbyr/keen-slider#129]
I'm trying to make a slow-moving carousel that auto slides with linear ease. Is this possible? Adding `transition-timing-function: linear` doesn't do the trick because it's animating with JS.

Let me know if this is possible, could find it in the docs. 

Thanks

**Comment by rcbyr** [comment]
Sorry for the late answer. Yes it is possible. Check this out: https://keen-slider.io/examples#automove
