### ISSUE TITLE
[Solved by myself] The auto responsive feature fails to work with a sidebar that could be hidden.

### ISSUE THREAD

**Issue by cainmagi** [rcbyr/keen-slider#132]
I am using this awesome component with my website. But I find that it could not work well with the sidebar of my site. Because this sidebar could be hidden by clicking the collapse button, each time I click it, I find that the auto responsive keen-slider does not render properly.

| Click before | Click after |
| :-----: | :-----: |
| ![good](https://user-images.githubusercontent.com/32186723/127416282-1b5be1ed-c111-4020-bd3a-cdfa1bd469db.png) | ![bad](https://user-images.githubusercontent.com/32186723/127416291-762f0ee7-d7bd-4068-8091-5dd81898bde5.png) |

* This page could be found here: https://cainmagi.github.io/FFmpeg-Encoder-Decoder-for-Python/docs/
* The source codes could be found here:
  * The page with the component: https://github.com/cainmagi/FFmpeg-Encoder-Decoder-for-Python/blob/docs/docs/introduction.mdx
  * The customized component: https://github.com/cainmagi/FFmpeg-Encoder-Decoder-for-Python/blob/docs/src/components/KeenSlider.js

Certainly, If I change the browser width, the components will be adjusted to a good width. But I wonder whether this should be a bug? By the way, currently, I could not hack into the implementation of the sidebar, so I want to know whether this problem could be solved from keen-slider side.

Thank you!

**Comment by cainmagi** [comment]
I have solved this problem by myself, although the hotfix I use is a little bit ugly:

```jsx
import React, { useCallback } from 'react';
import clsx from 'clsx';

import { useResizeDetector } from 'react-resize-detector';
import { useKeenSlider } from "keen-slider/react";
import "keen-slider/keen-slider.scss";
import styles from "./KeenSlider.module.scss";

function KeenSlider(props) {
  let sliderRes;
  const [currentSlide, setCurrentSlide] = React.useState(0)
  const [sliderRef, slider] = useKeenSlider({
    ...
    created(s) {
      sliderRes=s;
    },
    ...
  });
  
  const onResize = useCallback(() => {
    if (sliderRes !== undefined && sliderRes !== null) {
      sliderRes.resize();
    }
  }, []);
  const { width, height, ref } = useResizeDetector({ onResize, handleWidth: true, handleHeight: false });
  
  return (
    <>
      <div ref={ref} className={styles.navigationWrapper}>
        <div ref={sliderRef} className="keen-slider">
          ...
    </>
  );
}
```

This problem is solved by using [`react-resize-detector`](https://www.npmjs.com/package/react-resize-detector). It seems that `keen-slider` is using the windows' size to monitor the change of the slider. I need to point out that this is not a good idea. Instead, the monitor should be equipped on the slider object itself. I strongly suggest the author to replace the window monitor with the component monitor in the next version. 😃

**Comment by rcbyr** [comment]
Thanks for your feedback! I have created an example for this problem. https://keen-slider.io/examples#resize
