### ISSUE TITLE
destroyed hook fires on init

### ISSUE THREAD

**Issue by andrey-hohlov** [rcbyr/keen-slider#136]
I noticed incorrect hook triggering. The first event when you initialize the slider is ```destroyed```.

```sliderInit()```
calls ```sliderCheckBreakpoint()```
that calls ```sliderRebind()```
that calls ```sliderUnbind()```
that calls ```hook('destroyed')```

We have to check if it's the first initialization and do not trigger this hook.
What do you think?

**Comment by andrey-hohlov** [comment]
Also here, order of events on init:

```
destroyed
beforeChange
slideChanged
afterChange
mounted
created
```

I think it should be:

```
created
mounted
```

and that's all.

**Comment by rcbyr** [comment]
Hey @andrey-hohlov 

you are right. The lifecycle was broken. It ist fixed in the new version.
