### ISSUE TITLE
Slider Width Issues.

### ISSUE THREAD

**Issue by Louboutin1017** [rcbyr/keen-slider#138]
Im not sure where to write this but here's the the issue, Im trying to adjust width of the default slider but it's not possible via CSS.

Default added via JS
min-width: calc(50% - 7.5px);

I tried adding this with CSS
min-width: calc(80% - 7.5px);

But only 1 to 4 sliders works, while 5, 6  doesn't slide through.

I cannot find anywhere in documentation to have a custom min-width:

Advise.

**Comment by rcbyr** [comment]
Sorry for the late answer. Can you provide a code example?
