### ISSUE TITLE
[React] Maximum update depth exceeded 

### ISSUE THREAD

**Issue by nghiepit** [rcbyr/keen-slider#139]
When the wrap element contains `slider` is invisible:
> Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```jsx
 const [sliderRef, slider] = useKeenSlide();

<section className="hidden lg:block">
    <div ref={sliderRef} className="keen-slider">
       <div className="keen-slider__slide"></div>
       <div className="keen-slider__slide"></div>
    </div>
</section>
```
An error will appear when `<section className="hidden">` is invisible.

**Comment by rcbyr** [comment]
Hey @nghiepit 

could you provide a code example?
