### ISSUE TITLE
RTL support and Register new animation Feature Request

### ISSUE THREAD

**Issue by sadeghbarati** [rcbyr/keen-slider#14]
Hi @rcbyr 

## RTL :
Thanks for this cool slider and lightweight ❤️ 

`dir="rtl"` attribute for element or an option in KeenSlider

---

## Register Animation :

like your [Sandbox Example](https://codesandbox.io/s/keen-slider-zoomout-react-1bfic?file=/src/App.js) ZoomOut animation which that really dope if we can register our animation like `swiper.js`

https://swiperjs.com/api/#coverflow-effect
https://swiperjs.com/api/#flip-effect
https://swiperjs.com/api/#cube-effect

with regards

**Comment by rcbyr** [comment]
Hello @sadeghbarati,

thank you very much. I'm not quite sure I understood your request right. So I will try to answer as best I can.

This project aims to be a lightweight and good foundation to build some fancy components. With this in mind, I will focus on improving the movement animations and performance or building some missing features like the possibility to have slides with different widths/heights. And of course, I will provide more advanced examples.
So I will not implement the advanced examples as an option to the keen-slider. Instead, I could help you implement them in your preferred framework by adding more code examples.
