### ISSUE TITLE
Hide part of the last item

### ISSUE THREAD

**Issue by aminsaedi** [rcbyr/keen-slider#140]
I'm using react and have problem on the last item in slider
![image](https://user-images.githubusercontent.com/23167933/131734541-84f900eb-9da6-47f1-840b-583f50602b11.png)
Look at the last item's right side. It seems that a little part of item is invisible.

CSS:
```
.container{
  width: 80%;
  margin: 0 auto;
  padding: 0 5rem;
  background-color: red;
}
.item{
  /* display: flex; */
  width: 18rem;
  max-width: 18rem;
  /* height: 20rem; */
  overflow: hidden;
  border: #e4e4e4 1px solid;
  border-radius: 0.5rem;
  background-color: white;
}
```
JSX:
```
const [sliderRef] = useKeenSlider({
    slidesPerView: 4,
    spacing: 25,
    loop: true,
    // rtl: true,
  });
return(
 <div className="container">
        <div ref={sliderRef} className="keen-slider">
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
          <Product className="keen-slider__slide" />
        </div>
 </div>
);
```

**Comment by rcbyr** [comment]
Hey @aminsaedi 

sorry for the late reply. You just need to add `box-sizing: border-box;` to `.item`. I will also add this property to `.keen-slider__slide`, in the next version.

**Comment by uniquesolution** [comment]
Hi I am using this slider in a wordpress site  here https://uniquesweb.co.in/ntheme/keen-slider/ , the last image is getting cropped. the "keen-slider__slide" div has already `box-sizing: border-box;` css provided. Still the last image in the slider getting cropped. Any idea?
