### ISSUE TITLE
Variable slide speeds, slide 1 stays on screen longer then slide 2

### ISSUE THREAD

**Issue by robawills** [rcbyr/keen-slider#141]
Hey,

Is there a way to set different slides to have different autoplaying speeds. 
So for example slide 1 is in view for longer then slide 2?

**Comment by asoutheastasiandessert** [comment]
I second this

**Comment by rcbyr** [comment]
Here is a code sandbox that shows how this can be done: https://codesandbox.io/s/runtime-thunder-36d96?file=/src/App.js
