### ISSUE TITLE
The problem of slidesPerView with the real count of slides

### ISSUE THREAD

**Issue by yanalexandrov1987** [rcbyr/keen-slider#143]
If the value of the slidesPerView parameter is greater than the slides items, the plugin overrides the slides width, and "breaks" the layout.
For example, the value of slidesPerView is 4, the screen width is 1000 pixels, the number of slides is 2 with a width of 250px. Logically, the slider should not be initialized in this case, but no, the plugin overrides the width of the slides to 1000px. Nonsense.

**Comment by yanalexandrov1987** [comment]
Ah, the autoAdjustSlidesPerView property is not described in the dock. You need to set it to false.

**Comment by rcbyr** [comment]
This problem is gone with the new major version.
