### ISSUE TITLE
Autoplay?

### ISSUE THREAD

**Issue by hrqmonteiro** [rcbyr/keen-slider#145]
How can i make an autoplay slider using the React version? Couldn't find it.

**Comment by guilhermebellotti** [comment]
Sorry for the question... I tried looking for something in the documentation but I couldn't find anything on the subject.

I wonder if it's possible to have autoplay on the slide, but without looping enabled?
Is it possible or is there a way to get the slide back to the starting position without the loop?

Thx!

**Comment by rcbyr** [comment]
Hey @guilhermebellotti 

sorry for the late answer. I would solve it this way: 
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v5/misc/autoplay/javascript?file=/script.js
