### ISSUE TITLE
SlideChanged hook fired before Mounted hook

### ISSUE THREAD

**Issue by condini-mastheus** [rcbyr/keen-slider#147]
I've notice that the `slideChanged` hook is fired before `mounted` hook. I'm not sure if it's a bug or intended behavior but why this hook is called before `mounted` or called at all when carousel is initializing?

I also made a really [small example](https://codesandbox.io/s/fervent-haze-3rbi1?file=/src/Slider.vue) and it's shown in the picture above:
![Captura de Tela 2021-10-14 às 10 05 49](https://user-images.githubusercontent.com/12428539/137324885-7561b7f1-a7dc-413c-9832-d2edcd798c75.png)

**Comment by rcbyr** [comment]
The lifecycle was fixed in the new major version.
