### ISSUE TITLE
Keen slider is not initializing properly in some browsers on first load.

### ISSUE THREAD

**Issue by jhaltercmu2020** [rcbyr/keen-slider#149]
Steps to reproduce.
1. Create a simple keen slider using 'keen-slider/react' with a slideChanged option that updates the current slide based on the slide details with a next and previous button that calls useCallback on the slider and calls the next or previous function.
2. Load the slider in a private Firefox browser and see that the slider doesn't get fully initialized.
3. On refresh you will see the slider looks correct and is functioning correctly and stepping through the browser you can see it gets initialized correctly.

This seems to be a timing issue with the keen slider. The initialize of the keen slider is happening before the html dom is loaded.

A temporary fix that we used was to update the options when the slider changes because in the slider code here:
https://github.com/rcbyr/keen-slider/blob/bfb2816b46d9f59874843f13c1982b4ad17bd2f3/src/react.js#L25
if the options change this re-initializes the slider effectively.

**Comment by rcbyr** [comment]
Hello @Jhalter5Stones 

can you reproduce this problem with the new version (v6.*)? I think the problem is gone.

**Comment by DineshRout779** [comment]
Has it been fixed?

**Comment by javascript-coding-fan** [comment]
@jhaltercmu2020 If you found out a solution, can you pls share?
