### ISSUE TITLE
Problem with container with transform: scale and slide width

### ISSUE THREAD

**Issue by SamuelGaona** [rcbyr/keen-slider#156]
I have a grid using Shuffle.js, it resizes the containers from scale(0.001) to scale(1) to animate filters, that causes keen-slider take width 0.3px instead of 300px and causes small slides.

That doesn't happen in v5, in none of my tests. I've tested slides.perView = 1, the default one, diferent selector but its the same problem. If you resize the window, the problem solves, but thats not a viable solution.

![image](https://user-images.githubusercontent.com/8404410/143671685-148dd773-406a-4a67-890a-04ea4f9195bf.png)

**Comment by SamuelGaona** [comment]
![image](https://user-images.githubusercontent.com/8404410/143671815-374a7fec-c100-400a-9684-60386a6943fe.png)

**Comment by rcbyr** [comment]
Hey @SamuelGaona 

sorry that this doesn't work as expected. I understand the problem, but don't understand why this works with v5. Could you please create a codesandbox or post some code of your implementation.

**Comment by SamuelGaona** [comment]
Yeah, i'll try to create one tomorrow. Good night! Ty for answering.

**Comment by designast** [comment]
In the old version, it works because it uses% instead of pixels when calculating the width of the slide.
*I am using the update method of the slider after my scale animation has finished.

**Comment by rcbyr** [comment]
Hey @designast 

sorry, I overlooked your comment. Thanks for pointing out what the difference is. Since the slider works a little differently to make variable widths possible, I'm not entirely sure that returning to % values will make a difference in this issue. I will think about it.

**Comment by JoseGarciaM** [comment]
I'm having the same issue in NextJs

**Comment by JoseGarciaM** [comment]
returned to the old version as @designast says and it works wonders in the latest NextJs version

**Comment by JoseGarciaM** [comment]
@designast @SamuelGaona use KeenSliderPlugin and ResizePlugin example. It solved the issue. Hope it helps =D

**Comment by SamuelGaona** [comment]
> @designast @SamuelGaona use KeenSliderPlugin and ResizePlugin example. It solved the issue. Hope it helps =D

Any link? :o

**Comment by JoseGarciaM** [comment]
> > @designast @SamuelGaona use KeenSliderPlugin and ResizePlugin example. It solved the issue. Hope it helps =D
> 
> Any link? :o

https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/resize/react-typescript?file=/src/App.tsx
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/resize/react?file=/src/App.js

=D

**Comment by SamuelGaona** [comment]
> > > @designast @SamuelGaona use KeenSliderPlugin and ResizePlugin example. It solved the issue. Hope it helps =D
> > 
> > 
> > Any link? :o
> 
> https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/resize/react-typescript?file=/src/App.tsx https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/resize/react?file=/src/App.js
> 
> =D

Not working, it keeps reporting a width of 300px, when Shuffle.js hides the box, it gets as small as 0.3px, but the ResizePlugin keeps reporting 300px.

**Comment by SamuelGaona** [comment]
Nevermind, I got it working, I just have to add a timeout to call `slider.update()` . I'm gonna iterate over that, but ty for pointing me the direction.

Btw, estás invitado a Tecolutla, Veracruz @JoseGarciaM .

**Comment by SamuelGaona** [comment]
I solved it overriding the slide and container width with `min-width: 100% !important` . Such a dirty hack, but I think the library should expose an option to treat widths as percentages with a `slides.perView: 1` option.

**Comment by rcbyr** [comment]
Fixed this in v6.6.14.

**Comment by aleor** [comment]
Thanks a lot for this fix @rcbyr, it was bugging me for a long time.. I had to use workarounds provided in other issues, like calling ```slider.update()``` within ```setTimeout``` or something similar.
After update to v6.6.14 issue is no longer there and I got rid of these additional calls to update slider.
