### ISSUE TITLE
Some important code examples for Angular have been disappeared from the official site

### ISSUE THREAD

**Issue by oleg-golota** [rcbyr/keen-slider#157]
Of course it's not an issue. But could you restore the links to sandboxes with the following essential examples written in **Angular**.
https://keen-slider.io/examples#navigation
https://keen-slider.io/examples#lazy-loading
It's true that I can try to learn these features by react examples, but this is not very convenient. And since these examples were present recently, but disappeared a few days ago, I would ask you to return them back.

**Comment by rcbyr** [comment]
Hello @oleg-golota 

I am currently working on the new version and have to rewrite the examples for it. So the missing examples will be available soon. If you are working with the old version (v5.*) of the slider, you can easily access the examples via the git repository [keen-slider-sandboxes](https://github.com/rcbyr/keen-slider-sandboxes).

For example, the links to the missing sandbox are: 
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v5/media/lazy-load/angular
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v5/navigation/arrows-and-dots/angular

**Comment by saurabh-codeword** [comment]
http://web.archive.org/web/20210323122004/https://keen-slider.io/examples/ All v5 code sandbox links are available here
