### ISSUE TITLE
Server side render initial style cause FOUC

### ISSUE THREAD

**Issue by joehua87** [rcbyr/keen-slider#16]
Thank you for your awesome works

When rendering keen-slider on the server-side; the slide widths & heights are calculated only when JS starting to work -> causing [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)
The possible solution I think of is exporting sliderSetWidths & friends (https://github.com/rcbyr/keen-slider/blob/master/src/keen-slider.js#L449), so the user can calculate the widths & heights on the server-side before sending it to the client

**Comment by rcbyr** [comment]
Hello @joehua87,

Thank you so much. 

I don't think this is gonna work out so well. (Sorry, for the lack of explanation, but I'm on the run and wanted to answer anyway) 

Instead, I would suggest creating some basic styles that make the slider look good when it is not initialized. And if necessary, you could remove these styles with the "created" event hook.

**Comment by joehua87** [comment]
> Instead, I would suggest creating some basic styles that make the slider look good when it is not initialized. And if necessary, you could remove these styles with the "created" event hook.

Thank you for your quick response, current I've gone with the approach you've suggested, but I think that managing the style in only 1 place is better. 😄 
Do you have any suggestions to do with only some small modifications?

**Comment by rcbyr** [comment]
I am currently working on something that makes the occurrence of a FOUC less likely. I hope I'm done with it over the weekend.

**Comment by srameshr** [comment]
@rcbyr This issue still exists. Anything on how to fix this?

**Comment by ponciusz** [comment]
this is quick example how I am solving it: 
its Next.js + css modules
its just partial code I hope you get the idea.

full css for placeholder here:
```
.placeholder {
  display: flex;
  $spacing: 10;

  .slide {
    min-width: calc(
      100% / var(--slides-per-mobile) -
        calc(#{$spacing}px / var(--slides-per-mobile) * (var(--slides-per-mobile) - 1))
    );
    max-width: calc(
      100% / var(--slides-per-mobile) -
        calc(#{$spacing}px / var(--slides-per-mobile) * (var(--slides-per-mobile) - 1))
    );

    @include breakpoint(tablet) {
      min-width: calc(
        100% / var(--slides-per-tablet) -
          calc(#{$spacing}px / var(--slides-per-tablet) * (var(--slides-per-tablet) - 1))
      );
      max-width: calc(
        100% / var(--slides-per-tablet) -
          calc(#{$spacing}px / var(--slides-per-tablet) * (var(--slides-per-tablet) - 1))
      );
    }

    @include breakpoint(desktop) {
      min-width: calc(
        100% / var(--slides-per-desktop) -
          calc(#{$spacing}px / var(--slides-per-desktop) * (var(--slides-per-desktop) - 1))
      );
      max-width: calc(
        100% / var(--slides-per-desktop) -
          calc(#{$spacing}px / var(--slides-per-desktop) * (var(--slides-per-desktop) - 1))
      );
    }

    // @for WILL BE DONE ONCE AND FOREVER ON APP BUILD
    // DONT USE VARIABLES HERE AS IT WILL NOT WORK
    // 6 IS HARDCODED WITH ASSUMPTION THAT ITS MAX
    // SLIDES PER VIEW JUST TO COVER PLACEHOLDER CASE
    @for $i from 1 through 6 {
      $ofset: ($i - 1) * $spacing;

      &:nth-child(#{$i}) {
        transform: translate3d(#{$ofset}px, 0px, 0px);
      }
    }
  }
}
```

that's how div wrapper looks like:
```
styles = {
    '--slides-per-mobile': slidesPerViewMobile,
    '--slides-per-tablet': slidesPerViewTablet,
    '--slides-per-desktop': slidesPerViewDesktop,
  } as React.CSSProperties;

<div
          ref={sliderRef}
          className={classNames('keen-slider', s.keen, { [s.placeholder]: !loaded })}
          style={styles}
        >
```

**Comment by ponciusz** [comment]
btw calculating on SSR will be costly and you won't be able to use cached versions.
Solution above relies fully on CSS.

**Comment by rcbyr** [comment]
I think this issue can be closed. The most reasonable solution for me is to use some initial styles that prevent FOUC. Like on https://keen-slider.io

**Comment by ojj1123** [comment]
I have same issue. But I resolve this issue thansk to @rcbyr 

## Solution
> I think this issue can be closed. The most reasonable solution for me is to use some initial styles that prevent FOUC. Like on https://keen-slider.io/

The author said that **a solution is to use initial styles like on [keen-slider docs](https://keen-slider.io/)**:

<img width="1136" alt="265272254-0e0900de-e8d7-4953-9b94-dcf25664af70" src="https://github.com/rcbyr/keen-slider/assets/33178048/97e84077-904c-49c8-a375-b6d65822c7bb">

It's code here:

```tsx
<ul className='w-full' ref={sliderRef}>
  <li className='min-w-full max-w-full'>
    ...
  </li>
  <li className='min-w-full max-w-full'>
    ...
  </li>
  <li className='min-w-full max-w-full'>
    ...
  </li>
</ul>
```

Using Tailwindcss
`w-full` is same `width: 100%`
`max-w-full` is same `max-width: 100%`
`min-w-full` is same `min-width: 100%`

You do write `w-full` in keen-slider container's(above `ul` tag) `style` prop. It match usually window's width. And then style keen-slider children(above `li` tag) as `max-w-full` and `min-w-full`.

## AS-IS/TO-BE
### AS-IS
https://github.com/rcbyr/keen-slider/assets/33178048/d5da7e9b-c58e-415d-9232-4a10ad758d6b

### TO-BE
https://github.com/rcbyr/keen-slider/assets/33178048/bf181ca8-376c-4f32-bcce-09c481131194

**Comment by therealak12** [comment]
I use this for a varying number of slides by breakpoints:

```css
/*custom breakpoints*/
@theme {
    --breakpoint-c1: 31rem;
    --breakpoint-c2: 44rem;
    --breakpoint-c3: 56rem;
    --breakpoint-c4: 69rem;
    --breakpoint-c5: 81rem;
}
```

```typescript
const foucPreventionStyle = "max-w-1/2 min-w-1/2 c1:max-w-1/3 c1:min-w-1/3 c2:max-w-1/4 c2:min-w-1/4 c3:max-w-1/5 c3:min-w-1/5 c4:max-w-1/6 c4:min-w-1/6"

const [sliderRef, sliderInstanceRef] = useKeenSlider<HTMLDivElement>({
    rtl: true,
    breakpoints: {
        '(min-width: 500px)': {
            slides: {perView: 3, spacing: 4},
        },
        '(min-width: 700px)': {
            slides: {perView: 4, spacing: 6},
        },
        '(min-width: 900px)': {
            slides: {perView: 5, spacing: 6},
        },
        '(min-width: 1100px)': {
            slides: {perView: 6, spacing: 8},
        },
        '(min-width: 1300px)': {
            slides: {perView: 7, spacing: 8},
        },
    },
    slides: {perView: 2, spacing: 6},
  ...
}
```

and finally include `foucPreventionStyle` in keen-slider's styles.
