### ISSUE TITLE
slider.track.details.rel and slider.track.details.abs is not correct sometimes.

### ISSUE THREAD

**Issue by xin2014** [rcbyr/keen-slider#161]
![image](https://user-images.githubusercontent.com/7124907/144408147-4256f557-7763-47d1-ac69-e430573c5bbd.png)
![rel](https://user-images.githubusercontent.com/7124907/144407608-95e93cd4-4b88-4921-9480-301bd899672f.gif)

**Comment by rcbyr** [comment]
Thank you for the hint. I have released a patch version. (v6.2.3)

**Comment by rcbyr** [comment]
Thanks again. Should be correct by now. (v6.2.4)
