### ISSUE TITLE
Question: How to relay to container that the width has changed

### ISSUE THREAD

**Issue by VincentVToscano** [rcbyr/keen-slider#163]
Great product. Cheers to the Keen Slider team.

I am using "keen-slider": "^6.2.0" in a vanilla JS environment

When I get to mobile or vice-versa I change the width the container. In actuality, the width is always 100% set in CSS, and I apply padding left and right only to the page in mobile, then remove for desktop. Below is my current JS. Essentially, I want a fluid layout (changes width according to browser width).

```
	const slider                    = new KeenSlider('.global-featured-articles__carousel-slider', {
			mode: "free-snap",
			loop: true,
			breakpoints: {
				'(min-width: 0px) and (max-width: 959px)': {
					slides: {
						perView: 2,
						spacing: 16,
					},
				}
			},
			selector: '.global-featured-articles__carousel-slider-slide',
			slides: {
				perView: 4,
				spacing: 16,
			}
		}
	);
```

Thanks in advance.

**Comment by rcbyr** [comment]
Hey @VincentVToscano 

thanks for using keen-slider.
I'm sorry, but I haven't understood the question yet. The container is the source of the width for the slider, so I don't know why you want to pass the width to it.

I have created a code example and the width of the slider changes according to the browser width. https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/default/javascript?file=/index.html

Can you specify the question a bit more?

**Comment by VincentVToscano** [comment]
Hi @rcbyr,
Thank you for the prompt response! You have correctly landed on the desired effect: responsive container/slider that uses `width: 100%`. I was hoping that using a percentage-based width defined via CSS would achieve this. Thank you for creating the code example. In this context (follow-up question for you as time permits), if you wanted on desktop to ensure the slides were a set width (say 200px), would you recommend setting `max-width` and `min-width` to 200px !important`, then setting the `perView` property to `auto`? **I am happy to relocate this question to another ticket if that is better for the community or is more desirable.** Again, thanks in advance!
Best Regards

**Comment by rcbyr** [comment]
Hello @VincentVToscano 

no problem, glad I could help. I think your suggestion is the best and easiest way to achieve that. Check this out: https://codesandbox.io/s/broken-rgb-gqfe9?file=/index.html

**Comment by VincentVToscano** [comment]
HI @rcbyr,
That's perfect! Thanks for the updated example and all your help. Happy and healthy holidays to you and the Keen team!
Best Regards
