### ISSUE TITLE
Two separate sliders render the data of one

### ISSUE THREAD

**Issue by kursademirtas** [rcbyr/keen-slider#164]
I need two different sliders on the homepage. I give different refs for both, but both render only the first slider's data. By the way, we are using Next.js in the project.

**Comment by rcbyr** [comment]
Hey @kursademirtas 

Could you provide a code example. The website (keen-slider.io) is also built with next.js, so there should be no problem.

**Comment by kursademirtas** [comment]
I have one more slider just like this one, they are both on my homepage and they render different data. Their references are completely different, I tried to give id but it didn't work. The only problem is that the second slider renders the data of the first.
https://gist.github.com/kursademirtas/fb69e732dc1af543e1747d22278150e5

**Comment by rcbyr** [comment]
@kursademirtas Thanks for the code. I have not been able to recreate the problem. Can you give me a code sandbox or repository where this problem occurs?
