### ISSUE TITLE
Keen slider doesn't work if I place it on a modal?

### ISSUE THREAD

**Issue by siamahnaf198** [rcbyr/keen-slider#165]
Hello, I am creating a `next js` application. I use `keen slider` in my several project. First of all Thanks to the all developer of keen slider. It is a amazing slider. But I am facing one problem when I place` keen slider` into a modal in my current project. Can you help me or is it an a serious issue?

Here is the modal component--

```
const Modals = ({ details, btnText, works, name, icon }) => {
    const [visible, setVisible] = useState(false);
    const modalToggler = () => {
        setVisible(!visible)
    }
    return (
        <Box>
            <ButtonBase onClick={modalToggler} >
                Open Modal
            </ButtonBase>
            <Rodal
                visible={visible}
                onClose={modalToggler}
            >
                <Typography variant="h5" component="h5">
                    {name}
                </Typography>
                // Carousel components
                <Carousels works={works} visible={visible} />
            </Rodal>
        </Box>
    );
};
export default Modals;
```

And this is the carousel component--

```
import { useState } from "react";
import { useKeenSlider } from "keen-slider/react";
import "keen-slider/keen-slider.min.css";

const Carousels = ({ works, visible }) => {
    const [currentSlide, setCurrentSlide] = useState(0)
    const [loaded, setLoaded] = useState(false)
    const [sliderRef, instanceRef] = useKeenSlider({
        initial: 0,
        slideChanged(slider) {
            setCurrentSlide(slider.track.details.rel)
        },
        created() {
            setLoaded(true)
        },
    })
    return (
        <div ref={sliderRef} className="keen-slider"> // Here I try it also `ref={visible ? sliderRef: null}` But not working
            {works &&
                works.map((work, i) => (
                    <div key={i} className="keen-slider__slide number-slide1">
                        <img src={work.image} />
                    </div>
                ))
            }
        </div>
    );
};
export default Carousels;
```

It just show a white screen. Not showing any carousel. But when I place it outside the modal then it works perfectly. What is the problem when I place it into modal.

Again thanks.

**Comment by rcbyr** [comment]
Hey @siamahnaf198 

it is not too easy to say where the problem lies. Probably the slider is loaded in an invisible state without width and is then not updated. You could try to add this to your Carousel component.
```
useEffect(() => {
if(visible) instanceRef.current.update()
}, [visible])
``` 

But its only a shot in the dark. May you can create a codesandbox with the error.

**Comment by derekphilipau** [comment]
I just had the same problem, but in Vue.  Because the modal was not opened, the ref isn't actually in the DOM yet.  Your modal might have an event like onOpen after the modal has been opened and is visible.  In that event handler you can access the ref and create the slider.  Then in the modal onClose destroy the slider.

**Comment by siamahnaf198** [comment]
Hello @rcbyr I try with your code. But not working--

Here is the codeSandbox link - https://codesandbox.io/s/cocky-sun-eujii

Please help to to going on.

**Comment by rcbyr** [comment]
Thanks for the codesandbox and pointing out that problem. I will have a look at it.

**Comment by rcbyr** [comment]
A quick solution would be to use the animationEnd event: https://codesandbox.io/s/nice-wilson-w3wl8?file=/Components/carousel.js

**Comment by siamahnaf198** [comment]
@rcbyr I think it is an a issue still that carousel content come some time delay when I open the modal. I am facing the design issue. Can give another solution?

**Comment by siamahnaf198** [comment]
Any ohter solutions?

**Comment by siamahnaf198** [comment]
I am mising keen Slider. 😭😭😢

**Comment by rcbyr** [comment]
You could do something like that (the version is 6.3.0)
https://codesandbox.io/s/modest-wood-mkdsl?file=/Components/carousel.js

**Comment by siamahnaf198** [comment]
It working find now.. Thank you

**Comment by siamahnaf198** [comment]
Can you reopen this issue.. Here is another problem in your solutions.  Please see the video.

https://user-images.githubusercontent.com/78312010/144744749-cfa92293-851b-4571-b242-fde6545f1f19.mp4


or I have to create new issue?

Thank you very much for your valuable time

**Comment by siamahnaf198** [comment]
If you hear me(I confused that you can hear me from a closed issue. It is a closed issue). Please determine my case.

**Comment by siamahnaf198** [comment]
Can I get any solutions.

**Comment by siamahnaf198** [comment]
@rcbyr, can I get any solutions?

**Comment by faizanarif196** [comment]
Oh, yes. I am eagerly waiting for it..

**Comment by siamahnaf198** [comment]
I am also.

**Comment by siamahnaf198** [comment]
😭😭😭😭😭😭😭
![SadGIF](https://user-images.githubusercontent.com/78312010/145001290-1f110cb7-f5c4-4e3b-9019-3e7290629e3f.gif)

**Comment by amari-dev** [comment]
I had the same issue. I fixed it with this workaround. I am lazy loading my modal. My modal unmounts if's not visible anymore.
```
const [mounted, setMounted] = useState(false);

useEffect(() => {
    setMounted(true);
 }, []);

return <>
    {mounted && <div ref={sliderRef} className="keen-slider">....</div>}
</>

```

**Comment by siamahnaf198** [comment]
Can you give me a example?

**Comment by siamahnaf198** [comment]
It is not working... @ ; 😭

**Comment by rcbyr** [comment]
You could do something like that: https://codesandbox.io/s/xenodochial-cloud-gng4z?file=/Components/carousel.js:735-812

**Comment by siamahnaf198** [comment]
wow. Smoothest. Thank you @rcbyr .

**Comment by siamahnaf198** [comment]
This is like amazing. Thank you very much @rcbyr 
.

Love from Bangladesh.
A team of web development
Code Station 21
