### ISSUE TITLE
How to get previous (v5) pause behavior in autoplay slider in React

### ISSUE THREAD

**Issue by kaushalyap** [rcbyr/keen-slider#167]
I was using v5 autoplay behavior with pause, upgrade to v6 things have changed significantly,  example behavior is not consistent between v5 and v6.

I want to have previous behavior in v6 where slide animate and come to the position, then pause a while then animate to the next slide.
How could I have that in v6?

**Comment by rcbyr** [comment]
Hey @kaushalyap 

Here is a codesandbox: https://codesandbox.io/s/nameless-cherry-rnnnc?file=/src/App.js

The behavior should be the same and has been improved or did I miss something?

**Comment by kaushalyap** [comment]
@rcbyr  Thanks,  You are correct I was looking at the wrong example (Auto Move) instead of Auto Switch. Sorry my fault.

Keen Slider is great! thanks for creating it. I decided to go with keen-slider because it is lightweight, so keep it lightweight and dependency free.

----------------

Not related:

I am seeing some type errors with 

` loop: true, `

```
Type 'true' is not assignable to type '(boolean | { min?: number; max?: number; }) & ((slider: KeenSliderInstance<{}, {}, "created" | "dragEnded" | "dragStarted" | "loop">) => void)'.ts(2322)
react.d.ts(162, 3): The expected type comes from property 'loop' which is declared here on type 'KeenSliderOptions<{}, {}, "created" | "dragEnded" | "dragStarted" | "loop">'
boolean
```
`timer.current = setInterval(() => {`


```
Type 'Timer' is not assignable to type 'undefined'.ts(2322)
void | IntervalID
(property) React.MutableRefObject<undefined>.current: undefined
```
I am using js but I have  `"checkJs": true,` on jsconfig.json to get the advantage of type system in ts. While I could suppress those linting errors, I want to know what they mean and how to fix them without suppressing in js?

**Comment by rcbyr** [comment]
@kaushalyap Thank you! I do my best to keep it lightweight and I can promise it will stay dependency free. 

I'm already working on a solution for the first error and will give you an update here.
The second error is not related to keen-slider. Maybe, you will have to pass a default value. E.g. `const timer = React.useRef(0);`. I would recommend to use the new code example. https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/autoplay/autoswitch/react?file=/src/App.js

**Comment by rcbyr** [comment]
@kaushalyap I have fixed the typing error in the last version.(v6.3.3).

**Comment by kaushalyap** [comment]
Thanks! I'll upgrade!
