### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by alireza-mh** [rcbyr/keen-slider#17]
It would be nice if the slider supports RTL.

**Comment by rcbyr** [comment]
Hey @alireza-mh,
Yes, I think you're right. I will add an option for this soon.

**Comment by angelcustodio** [comment]
hey @rcbyr, do you have something already planned for this feature?

**Comment by rcbyr** [comment]
hey @angelcustodio

I added this feature with version 5.3.2.
