### ISSUE TITLE
Keen slider not working in both modal and tabs?

### ISSUE THREAD

**Issue by simonsantan** [rcbyr/keen-slider#171]
Hi, there. I am using keen slider in my project. I am trying to implement keen slider in both modal and tabs. When I place the slider into modal and tabs it doesn't work. But When I placed it another place in the page then it working Findley.

I see there another person create a issue with the same problem. I read the full conversation but not getting any solutions. I also get some solution from that conversation. But There is still some problem designing issue.

Thank you very much.

**Comment by rcbyr** [comment]
Hello @simonsantan 

as you mentioned there is an other issue about the same error(#165). So that can be closed.

**Comment by siamahnaf198** [comment]
But how can I get the solutions.

**Comment by simonsantan** [comment]
@rcbyr But How can I get the solutions?
