### ISSUE TITLE
crash？？？ when package with electron

### ISSUE THREAD

**Issue by yuwenbai** [rcbyr/keen-slider#172]
detailsChanged: (s) => {
      setSliderState(s.track.details)
    },
    animationEnded: (s) => {
      console.log('animationEnded, ', s)
    },
。。。 when i add  the event ’animationEnded‘  in the usekeenslider   it's normal in develop mode
but crash after package with release mode
use afterchange never happen before
my environment is electron

**Comment by rcbyr** [comment]
@yuwenbai Can you give me a little more code or a repository where I can reproduce this problem?

**Comment by yuwenbai** [comment]
> 
just use your example code  then add extra  
animationEnded: (s) => {
  console.log('animationEnded, ', s)
},
packing with electron will be ocur

**Comment by rcbyr** [comment]
@yuwenbai Unfortunately, I couldn't reproduce your error with a simple sample project, built for macOS. Everything works.

**Comment by yuwenbai** [comment]
> @yuwenbai Unfortunately, I couldn't reproduce your error with a simple sample project, built for macOS. Everything works.
