### ISSUE TITLE
Having error when I use autoplay, arrow & dot navigation and thumbnail at a time?

### ISSUE THREAD

**Issue by siamahnaf198** [rcbyr/keen-slider#174]
Hello, I need a slider with autoplay, arrow & dot naviation and also with thumbnail? I use keen slider and put all the code from examples. Everything is well. 

But getting one problem when I slide very last slides like image-

![Screenshot 2021-12-11 152125](https://user-images.githubusercontent.com/78312010/145671575-c1805526-7e2a-4226-9452-20ee2b3d016f.png)

Here is the codeSandBox link- https://codesandbox.io/s/charming-babbage-cvivy

In the codeSandBox- You can see error when

You try to slide more when you reach the last slide. like video-

https://user-images.githubusercontent.com/78312010/145671672-1f1d481f-1363-4449-8f08-66c6c9666065.mp4

**Comment by siamahnaf198** [comment]
@rcbyr Can get any solutions?

**Comment by rcbyr** [comment]
See my changes: https://codesandbox.io/s/charming-mirzakhani-yjlgk?file=/pages/index.js

**Comment by siamahnaf198** [comment]
Thank you very much. Love from Siam Ahnaf.
