### ISSUE TITLE
Question: How to create slide count in Vue.js?

### ISSUE THREAD

**Issue by rylanharper** [rcbyr/keen-slider#176]
Hey There! I really appreciate all the work that has gone into this project. I have used Keen Slider many times in my Vue projects and it always works wonderfully :)

I recently came across this really cool [codesandbox](https://codesandbox.io/s/elastic-mountain-8nwob?file=/src/App.js:296-591) in which the author has created a slide counter above his keen-slider component.. I am a bit of a noob with this and I am wondering how this can be achieved in Vue?

Any help would be really appreciated.. P.S I know this isn't an issue, but currently there are no discussions enabled in this repo for minor questions like this one!

**Comment by rcbyr** [comment]
Hey @rylanharper 

thank you very much. It's nice to hear that.

I've created a codesandbox for you and hope it helps.
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/default/vue?file=/src/Slider.vue

**Comment by rylanharper** [comment]
@rcbyr Wow! Thank you for the quick response. 

This is awesome! It is actually incredibly simple lol.. I really appreciate the help. I will save this codesandbox on my profile for future reference. Thank you!
