### ISSUE TITLE
RTL does not work when body tag contains dir rtl

### ISSUE THREAD

**Issue by JanStevens** [rcbyr/keen-slider#177]
Hi,

Thanks for this awesome project, just what we where looking for! I noticed that RTL does work correctly but if you change your body tag to `<body dir="rtl">` then the slider is completely off.

I've created a sandbox that shows the issue, if you remove the `dir` element on the body tag then everything works fine if you add it then the transformations are off. Notice that setting `rtl: true` or `rtl: false` has no effect.

Setting `dir="rtl"` is always advised when working with RTL languages, it lets the browser know that all native element should be rendered with rtl in mind.

https://codesandbox.io/s/naughty-butterfly-0mxfw?file=/src/App.tsx

**Comment by rcbyr** [comment]
Hey @JanStevens 

thank you for using the library and pointing out this problem. I have created a bug fix version. See your forked codesandbox. https://codesandbox.io/s/wizardly-rosalind-iq7kv?file=/src/App.tsx

**Comment by JanStevens** [comment]
Awesome that worked! Thanks alot
