### ISSUE TITLE
How to get amount of slides?

### ISSUE THREAD

**Issue by enisze** [rcbyr/keen-slider#178]
Hey, I want to use the slider, with a fixed minWidth but slidesPerView set to `auto`. How do I get the amount of slides to e.g. disable the chevron? `instanceRef.current.track.details.slides.length` returns the amount of all elements, but not the slides (e.g. I have n elements per slide depending on the viewport)

**Comment by rcbyr** [comment]
Hey @enisze 

to disable the chevron you could use `instanceRef.current.track.details.progress`. It goes from 0 to 1. 

I hope that helps.

**Comment by enisze** [comment]
Hey @rcbyr I tried to that. The thing is the progress only goes to 1 if I click on the last fragment inside the slide. If i use the chevron (which only uses `next()`), it does not hit 1 but something like 0,934 . Currently I am solving it with getting the current width and dividing it with the given width to get the `slidesPerView`, but this is kinda a workaround. Any other suggestions?

**Comment by rcbyr** [comment]
Hey @enisze 

on which event do you take this value?

**Comment by enisze** [comment]
I do it during render @rcbyr. This is currently the way I get the amount of `slidesPerView`.


```
const getSlidesPerView = ({
  sliderSize,
  width,
  spacing,
}: {
  sliderSize: number
  width?: number
  spacing: number
}) => {
  const amountOfSlidesWithoutSpacing = sliderSize / (width ?? 1)
  const amountOfSlidesWithSpacing =
    (sliderSize - (Math.ceil(amountOfSlidesWithoutSpacing) - 1) * spacing) /
    (width ?? 1)

  return amountOfSlidesWithSpacing
}
```

**Comment by rcbyr** [comment]
Hey @enisze 

I've created an example and hope that helps.
https://codesandbox.io/s/admiring-field-zfpyz

**Comment by enisze** [comment]
Hey @rcbyr it is a bit more difficult in my case :D. I did not use the new ThumbnailPlugin yet. So I worked with two separate sliders to solve the Thumbnail problem. Could you provide me an example with the ThumbnailPlugin and chevronNavigation on both ends? I would need the slider to also move the Thumbnail slide when it reaches the middle slide index of the view.

https://user-images.githubusercontent.com/15271433/147815224-e476c86c-96c7-4210-a18e-588fb73dfdfd.mp4

I am not sure if this issue would be solved with the thumbnailPlugin, but I think more it would be the same issue? 
Kind regards

**Comment by rcbyr** [comment]
In the current version you can use the `maxIdx` property of the track details. This value gives you the maximum index that can be reached.
