### ISSUE TITLE
Slide doesn't fit container's width

### ISSUE THREAD

**Issue by meliborn** [rcbyr/keen-slider#179]
...but resizing does the job right. Screen record will give you a better explanation:

https://user-images.githubusercontent.com/735194/147296745-25506414-7183-4efd-8626-0508ee7abf57.mp4

```jsx
<div ref={refCallback} className="keen-slider">
          {testimonials.map((data) => (
            <div key={data.name} className="keen-slider__slide">
              <p className="testimonials__heading">{data.heading}</p>
              <div className="flex">
                <div className="testimonials__rating">
                  <img src={Rating} />
                </div>
                <div className="testimonials__date">{data.date}</div>
              </div>
              <p className="testimonials__body">{data.body}</p>
              <div className="testimonials__separator" />
              <div className="testimonials__author">
                <div>
                  <img src={data.avatar} />
                </div>
                <div>{data.name}</div>
              </div>
            </div>
          ))}
        </div>
```

**Comment by rcbyr** [comment]
Hello @meliborn ,

It's a bit hard to tell, but this behavior is usually caused by a change in width of the container after the slider is initialized. Ideally, fix this problem in outer element styles. I hope this helps. Otherwise, a code sandbox would be helpful.

**Comment by meliborn** [comment]
@rcbyr I thought this too, but couldn't find this expanded container. Is there a way to "reinitialize" slider? Like `slider.update()`

**Comment by rcbyr** [comment]
A call to `slider.update()` should fix this problem. You could also use a resize observer. I have already created an example for this. https://keen-slider.io/examples#resize

**Comment by meliborn** [comment]
@rcbyr Works like a charm, million thanks to you.
