### ISSUE TITLE
Use react-native-gesture-handler with react-native

### ISSUE THREAD

**Issue by mattijsf** [rcbyr/keen-slider#180]
Hi. I'm not sure to what extent the 0 dependencies is important to this library but I feel that this library could benefit greatly by utilizing react-native-gesture-handler with react-native-reanimated (v2) where gestures and layout updates can be offloaded to the UI thread entirely.

Did you consider this? Would it be feasible to write a separate plugin / hook to make this possible?

**Comment by rcbyr** [comment]
Hello @mattijsf 

adding this libraries is unfortunately not an option, because the 0 dependencies is really important. Since the slider is extensible with plugins and also the drag and render functions of the slider are plugins, you can make this possible.

**Comment by mattijsf** [comment]
I was looking at the code and I really like your architecture and style. I'll make an attempt to add a reanimated plugin.

**Comment by mattijsf** [comment]
Is there anything you can recommend in terms of development setup? Are you using some example repo plus yarn / npm link?

**Comment by rcbyr** [comment]
I would create a react native app and connect the repository with npm link.

**Comment by mattijsf** [comment]
I was testing this on a fairly old iOS device (1st gen iPhone SE). Even though this library performs animations/transitions on the JS thread and UI updates through `setNativeProps` I was still able to get 60 fps on that device (with a basic setup). Quite impressive and I didn't expect that...

**Comment by rcbyr** [comment]
Nice to hear that. Thank you for testing this.
