### ISSUE TITLE
[BUG] - Use Spacing when controll slider

### ISSUE THREAD

**Issue by lucasmoura-boticario** [rcbyr/keen-slider#184]
When to use spacing 15 bug slider 

fix please

https://codesandbox.io/s/distracted-haslett-lq9mc?file=/src/App.js:405-417

**Comment by lucasmoura-boticario** [comment]
spaces bug: 5, 30

**Comment by lucasmoura-boticario** [comment]
in different scenarios the spacing bugs, it makes the slideChanged fire to the last value and thus impossible to return.

**Comment by rcbyr** [comment]
Did this error also occur with the latest version 6.6.3?

**Comment by ponciusz** [comment]
https://github.com/rcbyr/keen-slider/pull/196 This will solve it.
@rcbyr  please review its third ticket that this fix will solve
For anyone who need it asap like me I already released fix: 
`import { useKeenSlider } from "@ponciusz/keen-slider/react";`
 example with my fix: https://codesandbox.io/s/sad-paper-zncvl9 based on your example

**Comment by rcbyr** [comment]
Seems to be fixed by the PR from ponciusz.
