### ISSUE TITLE
Prevent Default click Events while swiping

### ISSUE THREAD

**Issue by bigfanjs** [rcbyr/keen-slider#187]
We are just starting to use Keen Slider moving away from another library. It works smooth but we faced this little issue related to events propagation.

We have a an anchor link container around a carousel(using Keen Slider now). When we swipe, it opens up the link URL we have in our wrapper anchor link. It works like charm on Mobile. this is only a desktop mouse issue.

We found nothing related to this issue. And we are not sure if you guys have any control configuration that enables this thing or anything we can do to prevent the anchor link default behavior right after dragging finished.

Here is a little demonstration of our JSX.
```jsx
<a href="https://keen-slider.io">
  <ul ref={sliderRef}>
      <li className="keen-slider__slide" >Keen</li>
      <li className="keen-slider__slide" >Slider</li>
      <li className="keen-slider__slide" >Rocks</li>
  </ul>
</a>
```

Thank you guys.

**Comment by rcbyr** [comment]
Hey @bigfanjs 

sorry for the very late answer. Here is a codeexample: https://codesandbox.io/s/old-dust-s5w4r9?file=/src/App.js
