### ISSUE TITLE
Slider chokes when you call prev or next on keydown

### ISSUE THREAD

**Issue by everdimension** [rcbyr/keen-slider#188]
Hi!
Thank you for an amazing library, I wanted to try it out for a long time

Everything works great, but I have one issue.
In my slider, I added keyboard events so that you can list through slides by pressing left or right keyboard buttons

It works, and if you press the buttons really quick, it works well, too.
But if you press and hold the button, the slider chokes and starts lagging really badly, basically staying on one slide for a long time

I reproduced it here: https://codesandbox.io/s/zen-pond-seoml?file=/src/App.tsx:773-830

Is there any way to work around this?

**Comment by rcbyr** [comment]
Hey,

thank you very much! Unfortunately I couldn't reproduce the described behavior. Which browser and OS do you use?

**Comment by ponciusz** [comment]
@everdimension maybe try to debounce your effect for me sounds like holding key emits more prev/next events that actual animation can handle imagine 100x key hits in 2 seconds when slide transition is 300ms.

or maybe implement some state which lets you go next only when prev transition ends
