### ISSUE TITLE
[Help] Direction property

### ISSUE THREAD

**Issue by NIIISH** [rcbyr/keen-slider#189]
Hello! Thank you for this great libriary. Everything worked fine on old version but now after upgrade to latest cant find some things like direction property from "details". So please could you explain how it can be done in latest version by proper way (I use direction to animate dots)

**Comment by rcbyr** [comment]
Hey @NIIISH 

I've created a codesandbox for you.

 https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/default/react?file=/src/App.js

**Comment by NIIISH** [comment]
@rcbyr Thank you very much!
