### ISSUE TITLE
Issue on slidesPerView

### ISSUE THREAD

**Issue by ronaldohoch** [rcbyr/keen-slider#19]
First of all, You're the best! Thank You!
Second... When you have slidesPerView set as the same number of slides (On my case, 7), the plugin doesn't show the 7th slide.

Here my code: https://codesandbox.io/s/keen-slider-spacing-angular-i1w7d?file=/src/app/app.component.ts

On ngOnInit function, i set the variable "this.slides" with an array of 7 objects.
In app.component.html i used a *ngFor to render the divs and then... the 7th slide don't show up on start.

**Comment by rcbyr** [comment]
Hey @ronaldohoch,

thank you very much. You're right, this is a bug. It should only be reset to 6 slidesPerView when the loop is activated. I will fix this in the next few days.

**Comment by rcbyr** [comment]
Hey @ronaldohoch 

I just fixed it in the new release. Thanks again for your hint.
