### ISSUE TITLE
Adding scrollbar to the bottom of the slider

### ISSUE THREAD

**Issue by spapenybe** [rcbyr/keen-slider#190]
Hi!
I am trying to add a scrollbar to the bottom of the slider like this (green scrollbar):
![image](https://user-images.githubusercontent.com/73598675/153183586-0a6e6315-119a-4063-8b71-c05e20f4484d.png)
I managed to get a scrollbar by adding `overflow-x: scroll !important;` to the `keen-slider` class. The problem is when calling `instance.next()` or `instance.prev()` on arrow click, the scrollbar is showing incorrectly because of the transform of the keen-slider items is updated.
Is there an example/solution somewhere for what i'm trying to achieve?

**Comment by rcbyr** [comment]
Hey @spapenybe 

I would suggest to go with CSS Scroll Snap if you want to show the scrollbar.

**Comment by roman-antl-satoshilabs** [comment]
> Hey @spapenybe
> 
> I would suggest to go with CSS Scroll Snap if you want to show the scrollbar.

I tried this with Scroll snap too, but the scrollbar is stuck at the start and doesn't move.
Any idea or example for that? Thank you
