### ISSUE TITLE
Recycling / Lazy children loading

### ISSUE THREAD

**Issue by Elytum** [rcbyr/keen-slider#191]
Hi,

Has anyone implemented a recycling mechanism with keen slider ?
Each of my slides has ~30 DOM elements with ~25 slides, but only 7 are rendered in the worst case scenario.

Currently, all 25 slides are added to the DOM, amounting to 750 DOM elements, and would grow if more slides are loaded.
Some kind of recycling would reduce it down to 210 in the current case, which would be quite less intensive for SSR / memory usage.

Thanks !

**Comment by rcbyr** [comment]
Hey @Elytum 

could this be what you are looking for? https://keen-slider.io/examples#dynamic-content

**Comment by Elytum** [comment]
@rcbyr Thanks a lot !

I missed it in my rapid reading of the docs, you saved me from using an ok-ish version I was struggling to debug.
You know what the say, hours of trial and error can save you a few minutes of reading the docs !

**Comment by Elytum** [comment]
Implemented it, works great. (I'm replacing https://github.com/andyyou/react-coverflow for a more lightweight solution)
Only thing is, it seems to rely on the loop option, so how would you implement the same behavior while enabling infinite looping ?
