### ISSUE TITLE
SolidJS support

### ISSUE THREAD

**Issue by davedbase** [rcbyr/keen-slider#192]
I was hoping we could add support for SolidJS to Keen-Slider out of the box. If that's not in scope of your project perhaps you might be interested in my own implementation (https://github.com/davedbase/solid-slider). Would you accept a PR for adding Usage in Solid to your documentation at minimum?

**Comment by rcbyr** [comment]
Hey @davedbase 

sorry for the late answer. For now, I want to keep the complexity of the library at a level that I can handle and maintain myself. For this reason, I will only add integrations and documentation for libraries and frameworks that I know well or work with.

I think an example implementation could be a solution. You can find the examples linked on keen-slider.io in this repository: https://github.com/rcbyr/keen-slider-sandboxes/tree/v6

If you adapt an example(maybe basic/default at first) and create a PR,  I would link it on the website.

I think an example implementation could be a solution. You can find the examples from keen-slider.io in this repository: https://github.com/rcbyr/keen-slider-sandboxes/tree/v6

If you adapt an example for solid-js (maybe basic/default as first) and create a PR, I would link it on the website.

**Comment by davedbase** [comment]
Cool! I have a backlog of Solid migrations but I will definitely do this now that I know you're open to it. Thanks!
