### ISSUE TITLE
ADAPTIVE HEIGHT Vanilla JS Example Please

### ISSUE THREAD

**Issue by unetics** [rcbyr/keen-slider#194]
I have been loving this library but have a project that needs ADAPTIVE HEIGHT i am not using nor do i want to use REACT is there any way we can get a Vanilla JS version on the docs?

**Comment by rcbyr** [comment]
Hey @unetics 

here is a code example. https://codesandbox.io/s/agitated-leaf-u214yp?file=/index.html

**Comment by unetics** [comment]
Amazing thanks!!

**Comment by pwfcurry** [comment]
React version for anyone that's interested: https://keen-slider.io/examples#adaptive-height

https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/adaptive-height/react-typescript?file=/src/App.tsx
