### ISSUE TITLE
Allow mousemove event to still fire whilst dragging

### ISSUE THREAD

**Issue by simon-bird** [rcbyr/keen-slider#198]
Hey chaps,

We have been using Keen-slider for a while now but it seems since the v6 update any document eventlisteners for mousemove get disabled when dragging the slider on this version.

It would be great for this to still be allowed as we can't use custom cursors currently as they stop moving when a user interacts with the slider and then jump back once they let go. It wasn't an issue on v5.5.1

Cheers guys and hopefully a quick change!

**Comment by rcbyr** [comment]
Hey @simon-bird 

I've created a code example for you and hope it helps.
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/default/react?file=/src/App.js

**Comment by simon-bird** [comment]
Hey @rcbyr 

Thanks for that it did help and we found a workaround redeclaring it, however would it possible in future versions for it not to prevent these actions by default?

All the best
Simon

**Comment by rcbyr** [comment]
Seems to work again in the current version.
