### ISSUE TITLE
React Typescript sliderRef from useKeenSlider type error

### ISSUE THREAD

**Issue by ninoM** [rcbyr/keen-slider#2]
So I'm using React v16.3.1 and Typescript. 
```js
         const [sliderRef] = useKeenSlider();
        ...
        <div ref={sliderRef}>
          <img src={imageUrl} alt="some" />
          <img src={imageUrl} alt="some" />
          <img src={imageUrl} alt="some" />
        </div>
```

And basically it has the red underline on the `ref` prop of the div saying 
`Type 'RefObject<HTMLElement>' is not assignable to type 'string | ((instance: HTMLDivElement | null)`

**Comment by rcbyr** [comment]
You have to pass the type of your HtmlElement to the hook.
`
const [sliderRef] = useKeenSlider<HTMLDivElement>()
`

**Comment by ninoM** [comment]
Thanks that solved it.
