### ISSUE TITLE
Need advice: how to transition slide width at animationStarted?

### ISSUE THREAD

**Issue by McSimKammerer** [rcbyr/keen-slider#200]
Hi!

Can anyone help me to make such slider:

![ezgif-1-76321ea802](https://user-images.githubusercontent.com/91434403/158220633-19131e67-5bd8-4fc1-ae10-16adc3f4e03a.gif)

So current active slide will transition to some fixed width (% or abs - doesn't matter), and last active will transition to fixed width of all inactive slides. Slider with loop mode option. Is it possible at all?
I really need your advise because for past days I cannot wrap my head around how to make such plugin. I cannot even understand at which point keen-slider calculates translateX for slides. Because first and last slides behaves unpredictably.
For transition animation I'm using animejs, but any other solution will be much appreciated.

Thank you in advance!

**Comment by rcbyr** [comment]
Hey @McSimKammerer 

sorry for the late answer. I've been thinking about this problem for a while and haven't had a good idea how to implement it. At the moment, the slider needs static dimensions to work correctly. If these dimensions change, the slider must be reinitialized. Unfortunately, your implementation idea breaks with this principle.

Let me know if you can make this work, I will do it too if I do come up with an idea.
