### ISSUE TITLE
min-width & max-width not setting properly in keen-slider__slide class

### ISSUE THREAD

**Issue by Madhanwebdev** [rcbyr/keen-slider#203]
On my page, they have a cards with keen slider carousel, while clicking the card I will navigate to the same page with a different id. after the navigation the card widths are collapsed, I will inspect the keen slider some card min-width & max-width are not set properly when I refresh the whole page the min-width & max-width working properly, I don't want to refresh the page during navigation
What can I do about this issue?

**Comment by rcbyr** [comment]
Hey @Madhanwebdev 

sorry for the late answer. It is a little bit hard to tell without seeing any code. I would suggest to have a look at the mutation observer plugin. https://keen-slider.io/examples#mutation

**Comment by AlexanderHubar** [comment]
@rcbyr same for me. https://cln.sh/WXaNCr

**Comment by rcbyr** [comment]
Hey @AlexanderHubar

I think something like this could fix your problem:

`useEffect(() => {
  slider.current.update()
  thumbnail.current.update()
}, [media, slider, thumbnail])`

**Comment by AlexanderHubar** [comment]
@rcbyr thank you for the answer

**Comment by danishirasna** [comment]
@rcbyr I'm also facing this issue, but this line doesn't fix my problem.

**Comment by fresonn** [comment]
@danishirasna
```css
.keen-slider__slide {
  min-width: 100% !important;
  max-width: 100% !important;
}
```
