### ISSUE TITLE
swipe multiple items per slide

### ISSUE THREAD

**Issue by munafio** [rcbyr/keen-slider#204]
How can we implement a slider with multiple swipe, for example : 

I have a list of movies and I need 10 items per 1 slide, and when I click the arrows I need it to swipe to the next 10 items not only to the next 1 item as showing in your examples!

how can I implement this approach? I don't see any option for that.

**Comment by ponciusz** [comment]
probably use slider.moveToIdx than grab your current index and add 10, subtract it for back arrow.

**Comment by rcbyr** [comment]
What ponciusz said.

**Comment by harryduong91** [comment]
@ponciusz It's doesn't work with responsive
