### ISSUE TITLE
If user is scrolling towards the end

### ISSUE THREAD

**Issue by Spell28** [rcbyr/keen-slider#209]
Hi, can you help me with **'SCROLL WHEEL CONTROLS'** in horizontal mode?
I'm reversed delta in default example and
I'm trying change base example for that conditions:

1. **If user is scrolling towards the end, stop control wheel and get user access to page global scroll.**
2. **if user is scrolling to first item, stop control wheel and get user access to page global scroll.**

For now in default example if delta reversed:
Slider scroll always block global scroll from the page

sorry for my bad english.

**Comment by rcbyr** [comment]
Hey @Spell28 

I have created a small code example to show you how to achieve this. Hope it helps!
https://codesandbox.io/s/smoosh-firefly-6i48tw?file=/index.html
