### ISSUE TITLE
Vertical carousel

### ISSUE THREAD

**Issue by filip-jk** [rcbyr/keen-slider#21]
Hi there! 

The slider looks brilliant, wonderful job! I'm curious if there are any plans on adding support for vertical sliders/carousels? We'd definitely switch over to your library in my company but vertical support is, unfortunately, a must.

Thanks so much!

Regards!
F.

**Comment by rcbyr** [comment]
Thank you very much! Unfortunately, I don't have a jump mark for the vertical slider. But you find an example under [basic](https://keen-slider.io/examples/#basic).
