### ISSUE TITLE
slides.perView option when change from number to auto, slide's width is not recalculate

### ISSUE THREAD

**Issue by boomikuma** [rcbyr/keen-slider#216]
When changing the perView option of the slider from a number to 'auto', the width of the slides are not recalculate.

**Expected behavior:**
When changing (with setState) the per view option to 'auto', each of the slides should update to reflect the max and min width. 

``` tsx
const [slidesPerView, setSlidesPerView] = React.useState<number | 'auto'>(2);
  const [sliderRef, sliderInstanceRef] = useKeenSlider<HTMLDivElement>(
    {
      slides: {
        perView: slidesPerView
      }
    }
  );

  return (
    <>
.....
      <button
        onClick={() => {
          setSlidesPerView("auto");
          sliderInstanceRef.current?.update();
        }}
      >
        {slidesPerView}
      </button>
      <div ref={sliderRef}>
       ...
      </div>
.....
```

https://user-images.githubusercontent.com/37561295/161424130-e3317d5f-b399-43fa-88d4-1733f3244883.mp4

**Comment by rcbyr** [comment]
Hey @boomikuma 

thank you for making me aware of this problem. I have fixed it in v6.6.6. Note that in your case you need to set the size of the slides for "auto" mode via classes. Inline styles would be overwritten by the slider.
