### ISSUE TITLE
thumbnailed slider example issue

### ISSUE THREAD

**Issue by Necromant24** [rcbyr/keen-slider#217]
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/navigation-controls/thumbnails/vue3?file=/src/App.vue

**Comment by Necromant24** [comment]
makes errors on mooving, "Cannot read properties of undefined (reading 'absToRel')"

**Comment by Necromant24** [comment]
just need to comment addActive(main.track.absToRel(next)) and works without errors

**Comment by rcbyr** [comment]
Thanks for the hint. Fixed.
