### ISSUE TITLE
White screen after keyboard navigation

### ISSUE THREAD

**Issue by asader** [rcbyr/keen-slider#219]
First of all, thank you for that awesome library! 
After i navigate through slider with keyboard (tab key) and then trying to navigate with mouse, transform value of slide is wrong and as result you get blank page instead of slide.

Here's codesandbox example
https://codesandbox.io/s/affectionate-euclid-6pmmeh

**Comment by rcbyr** [comment]
Hey @asader 

thank you very much.
In my opinion this is an unwanted browser specific behavior. For the moment, I would suggest to set the tabIndex of the links to "-1" to prevent this.

**Comment by lukethacoder** [comment]
Is there a way to keep the auto focusing on the slides without breaking the transform values?
