### ISSUE TITLE
Animations and Autoplay build-in

### ISSUE THREAD

**Issue by Erehr** [rcbyr/keen-slider#22]
Can we have animations (fade/slide) and autoplay functionality build-in instead on depending on external code for vue/angular/react? As it is this functionality is not avaliable for vanillajs at all. In other carousel/slider scripts this is normally passed as arguments like this.

```
var slider = new KeenSlider('#my-slider', {  
    loop: true,  
    animation: 'slide', // or fade  
    autoplay: 1000, // time in ms  
})
```

**Comment by rcbyr** [comment]
Hello @Erehr,

the project is really new, and after some feedback, I realized that I need to make the goal of this project clearer on the website and in the repo description. This is what I will do. 

Until then:
This project aims to be a lightweight and good foundation to build some fancy components. With this in mind, I will focus on improving the movement animations and performance or building some missing features like the possibility to have slides with different widths/heights. And of course, I will provide more advanced examples.
So I will not implement the advanced examples as an option to the keen-slider. Instead, I could help you implement them in your preferred "framework" by adding more code examples, e.g. for vanillajs.

**Comment by Erehr** [comment]
> So I will not implement the advanced examples as an option to the keen-slider. Instead, I could help you implement them in your preferred "framework" by adding more code examples, e.g. for vanillajs.

That would be fine too. I already got vanillajs version of controls from reddit user already so only changing animation and autoplay is left for what I need. 

I would really like to use this one slider in my projects because as you said it's lightweight but mostly because it doesn't need any wrapper divs around it (there's only one other slider I found that do that). I even managed to avoid using <div class="navigation-wrapper"> for controls which is great.

**Comment by rcbyr** [comment]
Hello @Erehr 

Yeah, the user was me. ;-) Actually, I want to provide all examples in JS. I'm just a little busy at the moment. But I will start with the fader and the autoplay and send you the links in a few days.

**Comment by rcbyr** [comment]
Hey @Erehr 

I created the media examples and autoplay example in vanilla js. I hope this will help.

**Comment by Erehr** [comment]
> I created the media examples and autoplay example in vanilla js. I hope this will help.

Thanks. Just checked it but fader is not working and autoplay example shows nothing at all.

**Comment by ivanhojvat** [comment]
> Hey @Erehr
> 
> I created the media examples and autoplay example in vanilla js. I hope this will help.

Hi @Erehr. 
Please can you share a link to the example in vanilla js? I'm only seeing the example for React & React+Ts

**Comment by rcbyr** [comment]
Hey @ivanhojvat,

I have to update the examples for the new major version. I'm done with that in a couple of days. If you want the examples for the old version (v5) you can see my answer on this issue. #157
