### ISSUE TITLE
Vertical sliding over one slide using touchpad

### ISSUE THREAD

**Issue by CodeAsArt** [rcbyr/keen-slider#220]
Hi guys!

First of all thanks for Keen slider, which is super fast on any device/browser! However I need your help with vertical sliding over one slide using touchpad (especially on MacOS). I'm trying to do vertical slider controlled by mouse scroll and/or touchpad scroll. However I'm not able to achieve one slide scrolling using touchpad (one long and fast touchpad scroll event). Anytime I'm able to scroll more than just one slide. I've tried a lot of ways to solve it without any luck. Here you can find minimal setup: https://codesandbox.io/s/gifted-jepsen-dmxldt?file=/index.html based on official vertical keen slider example: https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/vertical/javascript?file=/index.html

I'll be really thankful for any working fork or advice :)

**Comment by rcbyr** [comment]
@CodeAsArt  If I understand you correctly, your problem is that you always swipe more than one slide with the touchpad?

**Comment by CodeAsArt** [comment]
@rcbyr Basically yes, if you do "fast" swipe/scroll on touchpad it'll scroll more than one slide. However, if you do "small / slow" swipe/scroll on touchpad it'll scroll just one slide (which is ok). So it depends on movement speed.

**Comment by rcbyr** [comment]
Hey @CodeAsArt 
It's not very easy to implement this kind of behavior because the wheel event is not consistent for every browser or device. So it can be very tedious to make this fit for yourself or for your customers. Here is a possible solution (far from finished): https://codesandbox.io/s/determined-gauss-kulzgb?file=/index.html

**Comment by CodeAsArt** [comment]
@rcbyr I knooow 😄  I've tried similar solution too, but I've found significant drawback of this solution. When you use mouse wheel for scrolling and scroll one slide by one then it look like the slider is frozen or doesn't respond on users input. Anyway I appreciate your support 🙂 , however this solution doesn't solving issue without new one :/

**Comment by rcbyr** [comment]
I gave it another try: https://codesandbox.io/s/elegant-lamarr-78e60p?file=/index.html

**Comment by CodeAsArt** [comment]
Hi @rcbyr, first of all thank you for another try and your patience with our problem. 👍  Your last try seems to be better than previous one, but there is still mouse wheel drawback.

**Comment by rcbyr** [comment]
Hey @CodeAsArt, that's what I meant before, the wheel event is not consistent. With my Macbook touchpad or mouse it works just fine. On my Windows PC with a mouse as well. It doesn't seem to work as well on your device. Perhaps you can fine tune my solution to fit your needs. It would be great if you share your solution if you find a better one.
