### ISSUE TITLE
Issue with fader mode and slides that contain links

### ISSUE THREAD

**Issue by ghtm2** [rcbyr/keen-slider#221]
Hi.

While the images are fading between one another the lowest link in the stack is seeping through to the top.
It is corrected when the next slide reaches `opacity: 1`, which, depending on the animation duration, can take quite a while.

I've crudely modified the fader example [here](https://codesandbox.io/s/great-chandrasekhar-ld00qv).

Is there any way to fix or work around that?

Thanks.

**Comment by rcbyr** [comment]
@ghtm2 Can you provide a video of what you are seeing?

**Comment by ghtm2** [comment]
Sure.
I've used the same sandbox linked in my first post.

https://user-images.githubusercontent.com/98537985/164381931-7a80f7cd-5384-4fbc-982e-fb2095f2923c.mp4

The actual link below the cursor is visible in the bottom left corner.

**Comment by rcbyr** [comment]
Thanks for the video. I didn't get the problem at first. Here is a solution: https://codesandbox.io/s/relaxed-maxwell-93crfo?file=/index.html

**Comment by ghtm2** [comment]
Thank you very much for taking a look this quick.

It's much better than before, but not completely fixed I'm afraid.
If you reload the page the very first drag between slide One and Two still shows the wrong link.

**Comment by rcbyr** [comment]
I have updated the example.

**Comment by ghtm2** [comment]
Yep, it works now.
Thanks again.

**Comment by vader1359** [comment]
@rcbyr Hello, I just have the same issue. It seems your solution based on changing the z-index when new slide load, but does it affect performance if z-index keeps changing? I wonder if there is other solution.
