### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.concat.apply') (iOS 11)

### ISSUE THREAD

**Issue by oowliq** [rcbyr/keen-slider#222]
Slider breaks on iOS 11 Safari
TypeError: undefined is not an object (evaluating 'this.concat.apply')

When calling the useKeenSlider everything is fine, the problems start when we pass the ref to the element

`const [sliderRef] = useKeenSlider(
        {
            mode: 'free-snap',
            initial: 0,
            slides: {
                perView: 2,
                spacing: 3,
            },
        },
    );
`

![image](https://user-images.githubusercontent.com/47437822/165695568-da9bd643-a9fd-4e8f-a6f6-1f1285a007ce.png)

**Comment by rcbyr** [comment]
Thanks for noticing me about that problem. I will have a look at that in a few days.

**Comment by rcbyr** [comment]
Fixed in v6.6.12
