### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by solidevolution** [rcbyr/keen-slider#224]
We update our dependencies with npm-check

`❯◉ keen-slider              6.6.10  ❯  6.6.12  https://keen-slider.io`

Here best practice is to use the release function of GitHub and write some informations about feature and bugfixes instead only tagging versions without information.

If then the link in npm-check goes directly to the release page on GitHub, I would be very very happy :-D

**Comment by rcbyr** [comment]
Thank you for your feedback. I understand the problem and wanted to use releases for some time now. Next time I will create a release.

**Comment by solidevolution** [comment]
Great support, thank you for your awesome work!
