### ISSUE TITLE
Setting State in slideChanged strange behaviour

### ISSUE THREAD

**Issue by sharaku17** [rcbyr/keen-slider#226]
Hi guys, 

I am coming today with a very strange behavior that sadly I cannot manage to reproduce in a CodeSandbox, so the bug has to be on my side somehow. I am not sure if somebody can help me, but I am just hoping that maybe someone has some kind of idea of what could lead to this weird behavior.

I have implemented a Slider with navigation Bullet Points similar to the one in the examples here: [codesandbox](https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/navigation-controls/arrows-and-dots/react?file=/src/App.js)

Now there is something strange happening in my project. In the SliderOption I also have the slideChanged hook declared and inside that Hook, I am setting the Current Slide to `slider.track.details.rel` exactly like in the example. The Problem is now that if I click on a bullet point that is for example 3 indexes away from the currently active slide, then normally the slideChanged hook should fire 3 times for each index changing and the state of CurrentSlide should be updated 3 times until reaching the target index. 
This is not happening in my project, the hook is only firing once, so the state of currentslide is only changed by +/- 1. 

Even more strange is the fact that if I take the `setCurrentSlide(Slider.track.details.rel)` hook out of the `slideChanged ` hook, then the hook is firing multiple times again like expected which is the correct behavior.

So I cannot explain why setting the CurrentSlide State to  `slider.track.details.rel` is breaking the whole thing?
 Does anyone have maybe i slight idea of what might be causing this?

**Comment by rcbyr** [comment]
Hey @sharaku17 

which keen-slider version and react version are you using? 

Are you using exactly the same component as in the example? If not, can you share your code?

**Comment by sharaku17** [comment]
Hi @rcbyr  

I was using the keen-slider Version 6.6.10

I actually managed to fix the Problem during the weekend, as expected the issue was happening due to a issue on our code side. Somebody had implemented a useEffect hook that was causing the described behavior and thus I was able to fix it. 

On the other hand I have a second question, I hope its fine if I ask this here and don't make a second Issue (I will if you think it might be better to) 

In the CodeSandbox [here](https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/navigation-controls/arrows-and-dots/react?file=/src/App.js) 

If we click on the arrows, there appears a blinking cursor next to the navigation dots (I am using Google Chrome on Mac) 
Any idea why this is happening ? 


https://user-images.githubusercontent.com/32689131/167380078-c9745a74-048a-4e8f-9ced-1e031c842262.mov

**Comment by rcbyr** [comment]
Hey @sharaku17 

sorry but I couldn't reproduce that with Google Chrome (101.0.4951.54) on Mac. :-(
