### ISSUE TITLE
Slider breaks when inside container with flex-grow

### ISSUE THREAD

**Issue by chernushevich** [rcbyr/keen-slider#227]
Hello,

When the slider is placed inside a container that has flex-grow set to 1, it breaks (a horizontal scrollbar appears).

Example: [https://codesandbox.io/s/flex-grow-2sxm5u?file=/src/App.js](https://codesandbox.io/s/flex-grow-2sxm5u?file=/src/App.js)

I am on latest Chrome on Windows.

Is this expected behavior? If so, how should it be handled? Thank you!

**Comment by rcbyr** [comment]
Hey @chernushevich 

adding `overflow: hidden;` to your inner-container should fix that problem.

**Comment by chernushevich** [comment]
Hello @rcbyr 
Thank you! That fixed the problem, however now I've ran into a different issue - the slides don't take 100% of the allocated space if there is a sidebar with more that 2 words (I know this sounds confusing, please see attached example).

Example (reload the preview to see the bug): https://codesandbox.io/s/flex-grow-2sxm5u?file=/src/App.js

**Comment by rcbyr** [comment]
It seems that the width of the container was not yet calculated at the time the slider was initialized. A fix could look like this: https://codesandbox.io/s/flex-grow-forked-omoo7d?file=/src/App.js

**Comment by chernushevich** [comment]
@rcbyr that worked! Thank you for the help.
