### ISSUE TITLE
Slide cloning doesn't work with lazy slides

### ISSUE THREAD

**Issue by mephistia** [rcbyr/keen-slider#228]
Hello, first I'd like to thank you for the great lib, it's really impressive!

So, I'm having a bit of a problem trying to clone the slides to create a looping carousel even if the amount of slides doesn't "cover" the viewport.

I'm using wrapper components to centralize the carousel logic (Carousel and CarouselSlide). The Carousel component receives children and options, and the children are CarouselSlides. The Carousel component uses the slider hook, and I put the clone logic in the useEffect hook.

In the App, I'm populating an array in the useEffect hook, so they're the "lazy slides content". Then I'm mapping the array to be the content of the CarouselSlide component.

If I try to render the slides with an empty array (lazy array not populated yet), there's this error message:

```
TypeError
slider.current.track.details is null
```

I'm not sure if the problem relies on the clone logic, or the componentization of the slider, or in the lazyness of the content passed to the slides, but I couldn't find any examples of cloning the slides, or using the hook with a component. I'm using the useEffect hook instead of a custom plugin because I couldn't figure out how to duplicate the slides like that.

You can see the code I tried here: [https://codesandbox.io/s/clone-keen-slider-oihk05?file=/src/Carousel.tsx](https://codesandbox.io/s/clone-keen-slider-oihk05?file=/src/Carousel.tsx)

Thanks!

**Comment by rcbyr** [comment]
Hey @mephistia 

I have created an example to show a simpler approach.
I hope this helps: https://codesandbox.io/s/empty-sun-3vvvsd?file=/src/App.js

**Comment by mephistia** [comment]
> Hey @mephistia
> 
> I have created an example to show a simpler approach. I hope this helps: https://codesandbox.io/s/empty-sun-3vvvsd?file=/src/App.js

Hi, thanks for the example, it was really helpful! I was able to get it working by using a similar approach, but outside of the Carousel component, manipulating the items itself and not the children.

Do you think it could work as a plugin for the slider? I tried to modify the `slider.slides` array but it didn't update, even when calling the update method right after.
