### ISSUE TITLE
Slider unable to calculate correct width inside of Grid

### ISSUE THREAD

**Issue by zack-carlson** [rcbyr/keen-slider#229]
Keen slider inside of a grid has difficulty determining width when the grid-template-columns uses 1fr;

grid-template-columns: 100% however works fine.  
https://codesandbox.io/s/flex-grow-forked-h96l3g?file=/src/styles.css

**Comment by rcbyr** [comment]
Thank you for sharing that. I want to fix that in the next week.

**Comment by rcbyr** [comment]
Hey @zack-carlson 

adding `overflow: hidden;` to your wrapper (`.main`) will fix the width calculation.
