### ISSUE TITLE
Vertical thumbnail grow when window is resized, slides per view not working

### ISSUE THREAD

**Issue by mephistia** [rcbyr/keen-slider#230]
Hello, I was trying to make a thumbnail navigation with vertical slides and noticed the slides height go crazy when the window is resized (the more you resize the window, the taller they get). The vertical slider also does not apply the `slides: { perView }` option correctly.

I wondered if some of my CSS could have been causing that, so I forked the thumbnail example and just added `vertical: true` to the options, and it does happen there too: https://codesandbox.io/s/vertical-thumbnails-hz42eh?file=/src/App.tsx

Is there a fix I could make on my side? Thanks!

**Comment by rcbyr** [comment]
Hey @mephistia 

yes, it was your css. You have to give the container ".keen-slider" a fixed height. See my changes: https://codesandbox.io/s/vertical-thumbnails-forked-kyfuns?file=/src/styles.css

**Comment by pySilver** [comment]
@rcbyr I think I stumbled upon a similar case. In other words, the wrapper around the vertical slider should have a fixed height by itself, right? And that height should be calculated as `n * singleSlideHeightWithPaddingsAndMargins` ?
