### ISSUE TITLE
slider is not sliding when: slider.current?.moveToIdx()

### ISSUE THREAD

**Issue by ponciusz** [rcbyr/keen-slider#231]
https://codesandbox.io/s/bold-poincare-ux70op?file=/src/App.tsx:1993-2022

If element we want to scroll is pretty close to the end of slider and there is no way to align it to left its not scrolling at all.

https://user-images.githubusercontent.com/3374777/168265688-ccf471cd-683a-4c6a-8872-fabd1174fc4c.mp4

**Comment by rcbyr** [comment]
The slide index 5 is not reachable. `track.details.maxIdx` gives you the maximum reachable index. See here: https://codesandbox.io/s/angry-wozniak-miycc5?file=/src/App.tsx

**Comment by ponciusz** [comment]
Perfect its solving the issue. Thanks
