### ISSUE TITLE
Auto variable width slider

### ISSUE THREAD

**Issue by leneos** [rcbyr/keen-slider#233]
I get data from server so the content of each slide will differ from each other. Generally each slide contains icon and text.
How to make auto variable width slider? I can't do it with keen-slider like in docs, because in the docs you have to strictly describe minWidth and maxWidth. Help me please.

**Comment by rcbyr** [comment]
Hey @leneos 

I've created a codesandbox to show you one possible way to achieve that: https://codesandbox.io/s/elated-babycat-pekgvi?file=/src/App.js

**Comment by leneos** [comment]
@rcbyr It works perfectly! Thank you very much!!!

**Comment by jeremies** [comment]
@rcbyr In my app sometimes the boxes of the sliders overlap implementing this solution. There is an alternative way to do that?

**Comment by jeremies** [comment]
Hey @rcbyr,
I tried to do a `yarn build` and then the bug doesn't occur!

Thank you!
