### ISSUE TITLE
Can keen accommodate slides that exceed the carousel width?

### ISSUE THREAD

**Issue by dungle-scrubs** [rcbyr/keen-slider#234]
I have a need for the final slide, which is wider (or taller if vertical) that the slider itself.  When reaching the end, the rest of the slide ends up cut off and out of view because the slide aligns to the start of itself, rather than the end edge..  

The use case for me is a vertical slider where each panel is taller than the screen, but I'd like the user to be able to scroll to the bottom edge of the final slide.

**Comment by rcbyr** [comment]
Hey @dungle-scrubs,

I'm not quite sure I completely understand your goal. Here is a code sandbox with my guess: https://codesandbox.io/s/suspicious-fire-w2ux8l?file=/src/App.js

**Comment by dungle-scrubs** [comment]
@rcbyr Thanks that does demonstrate what I'm trying to ask.  The last slide, when the animation ends and the slider is at rest, extends beyond the bounds so you'll never see the rest of the slide.  What I'm hoping to do is have the bottom of the final slide end up aligned with the bottom of the slider (and therefore the top of that slide will be the side that ends up cut off). 

You can also see this demonstrated [here](https://www.abercrombie.com/shop/us/p/oversized-gauzy-coverup-top-48207824?categoryId%3D6570723%26seq%3D02%26faceout%3Dmodel1&sa=D&source=editors&ust=1653618425026069&usg=AOvVaw1y59I8p3cGEHkLO3oe-UQ4).  When you click on one of the slider images, a vertical slider pops up in a modal, and all of the slides are taller than the viewport.

**Comment by rcbyr** [comment]
Hey @dungle-scrubs 

thanks for the explanation. I hope that I understand you right. Did you want to do something like that? https://codesandbox.io/s/crimson-framework-4g3f4j?file=/src/App.js

**Comment by dungle-scrubs** [comment]
> Hey @dungle-scrubs
> 
> thanks for the explanation. I hope that I understand you right. Did you want to do something like that? https://codesandbox.io/s/crimson-framework-4g3f4j?file=/src/App.js

Hey @rcbyr thanks, this is very close to what I'm looking for.  However instead of the size being relative to the viewport (in this case it's 1.2 time the hight of the viewport) I'm hoping to have the slide be a set height, either manually defined or the natural height of the image.  Is that possible?
