### ISSUE TITLE
Rounding Error on Dynamic Slider with multiple Slides

### ISSUE THREAD

**Issue by MrAlexand0r** [rcbyr/keen-slider#235]
## Summary
It seems like, when progress is above 0.9999999999999, it gets rounded up to the next Dynamic Page, which causes a Problem in my Projekt with multiple slides per view.

## Video Proof
![Video](https://i.imgur.com/zpZnwWO.gif)

As you can see in the video, the absolute index jumps from 6/27/22 to 7/5/22, which in this case should not happen.

I edited the official example to roughly mimic how it is currently implemented in my projekt.

### You can view it here:
https://codesandbox.io/s/laughing-snow-d93iki?file=/src/app/app.component.ts

In case this is relevant:
Monitor Size: 27" 1440p (2560×1440)

**Comment by rcbyr** [comment]
Hey @MrAlexand0r 

thanks for pointing out the problem. It is not quite easy to solve and I have to think about it some more.

**Comment by rcbyr** [comment]
Fixed in v6.7.0

**Comment by MrAlexand0r** [comment]
@rcbyr  Our Team just came across a similar bug that can be reproduced in the same Sandbox Demo.
Codesandbox with the latest keen-slider Version: https://codesandbox.io/s/tender-glitter-d6gl7r

![](https://i.imgur.com/wLY7mdb.gif])

When the progress is 0.99999999999999 and you try to jump to an absolute index when using dynamic slides, it moves to another, wrong index instead.
How to reproduce:
Go to Abs Index 56 (2/27/23) and skip forward

It will attempt to moveToIdx(63, true) but will end up at index 55.
It looks like another rounding error to me, but I'll try to dig deeper

**Comment by MrAlexand0r** [comment]
I found a possible solution, however I am unsure if this causes any unwanted side-effects. For now it seems like it fixed my problem
https://github.com/MrAlexand0r/keen-slider/commit/aecee9de414cea4544c09d07843f67e06ab13170
