### ISSUE TITLE
[Question] Is it possible to use overflow-x: scroll with .keen-slider?

### ISSUE THREAD

**Issue by Sin1tar** [rcbyr/keen-slider#238]
Hello everyone, thanks for this great library!

So, Is it possible to use overflow-x: scroll with .keen-slider?
Or, maybe, some tips to implement custom scrollbar?

**Comment by rcbyr** [comment]
Thank you!

Here is a codesandbox with an idea how to solve this problem: https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/default/react?file=/src/App.js
