### ISSUE TITLE
clicks and drag events collision if slider content has interactive (clickable) elements

### ISSUE THREAD

**Issue by mtin79** [rcbyr/keen-slider#24]
hi there,
is there a built in way to intercept or distinguish clicks from drags within a slider element?
my slide content is interactive and might probably have even another slider embedded.
problem is that if i click i also receive drag events and vice versa.
or do i need to stop event propagation by using hammerjs to the parent slide container or similar?

thanks for help!

**Comment by rcbyr** [comment]
Hey @mtin79 

I thought about your problem, and I've come to the conclusion that I have to solve this within the slider. So, thanks for pointing that out. There's a new release tomorrow. I will then provide an attribute that the slider ignores if one of its elements has it.

**Comment by rcbyr** [comment]
Hey @mtin79 

I just released a new version. Be aware of some style changes. If you want to prevent the slider events on your elements within a slide, you can simply add the attribute data-keen-slider-pe. You can change the attribute name if needed, see the API.

**Comment by spluxx** [comment]
Hey @rcbyr 

How are you expecting the attribute to be used to distinguish between a tap and a swipe? I really love the library's capabilities but this is one thing that I can't figure out here.

I really wish there's a `onTap: (idx) => void` similar to `dragStart` and `dragEnd`, but this is just a suggestion.

**Comment by gibatronic** [comment]
Same for me, when the user clicks / taps I want to open a fullscreen gallery.
But the click event is going through after a swipe, which should have been prevented.

**Comment by avinash-vllbh** [comment]
+1 to what @spluxx suggested. @rcbyr is there a way to distinguish between a tap and a drag?
