### ISSUE TITLE
[Question] CSS defined spacing

### ISSUE THREAD

**Issue by rasteiner** [rcbyr/keen-slider#240]
Hello and thanks for the awesome work, it has replaced flickity for me :)

I just have a question about being able to define the space between slides via CSS, especially with properties like `gap`. 
example: https://codepen.io/rasteiner/pen/OJQYJOB

Keen-Slider thinks that spacing is `0`, and therefore the track width doesn't correspond with the real width of the content (cutting off part of the last slide).
I can work around this by setting the CSS spacing to 0, and copy the value to Keen-Slider during initialization, like here:
https://codepen.io/rasteiner/pen/PoQvoRy

```ts

const el = document.querySelector('.slider');
const spacing = parseInt(getComputedStyle(el).gap);
el.style.gap = '0';

new keenSlider(el, {
  selector: '.slide',
  mode: 'free',
  slides: {
    perView: 'auto',
    spacing
  }
})

```

But I wonder if there's a better way if I want to keep the spacing defined by CSS.

**Comment by rcbyr** [comment]
Hey @rasteiner 

thanks for using the library. Unfortunately, I don't plan to make that possible in the near future, as there are many workarounds and I would have to customize many things to do so. Hope for your understanding.

**Comment by rasteiner** [comment]
No problem, I was just wondering if I'm doing it wrong. Thanks :)
