### ISSUE TITLE
Configure treshold to prevent click on link when drag

### ISSUE THREAD

**Issue by liqueflies** [rcbyr/keen-slider#241]
Hello,

I have a problem clicking on a link inside the slides while dragging. I guess that configuring the threshold  maybe this issue will be solved.

https://github.com/rcbyr/keen-slider/blob/548e2ace14b753f5ba7b63939fbf9514476e255e/src/plugins/web/drag.ts#L83
I checked on this line 5 is fixed.
Can you please move it as a parameter?

Thank you!
L.

**Comment by rcbyr** [comment]
Hey @liqueflies 

why do you want to click on a link while dragging? If you want to achieve this, you can include this in your stylesheet after importing the default styles from keen-slider. 

`[data-keen-slider-moves] * {
  pointer-events: none;
}`

**Comment by liqueflies** [comment]
I solved calling sliderInstance.stop() method on click of my Slide :)
