### ISSUE TITLE
Allow touchstart (pointerdown) event 

### ISSUE THREAD

**Issue by theMosaad** [rcbyr/keen-slider#242]
I have a custom cursor where i listen to `mousemove` events for. keen slider seems to prevent that when dragging so the custom cursor stays in its place until dragging ends.

Found a similar issue with swiperjs where they have a [touchStartPreventDefault](https://swiperjs.com/swiper-api#param-touchStartPreventDefault) options that when i set to false, makes the custom cursor work again.

Is there a workaround i can do inside event hooks that disables preventing touchstart?

**Comment by rcbyr** [comment]
Hey @theMosaad,
 
the easiest way is to set the mousemove event listener with capture enabled.

**Comment by theMosaad** [comment]
TIL! glad that i won't have to use another slider, keen is the best so far for react and laravel projects. thanks for the great work and the quick response!
