### ISSUE TITLE
Before and after offset?

### ISSUE THREAD

**Issue by exdeniz** [rcbyr/keen-slider#25]
Please add before and after offset like slidesOffsetBefore and slidesOffsetAfter like swiper.js. It's necessary when the slider is used full width screen and the slides go over the screen. Like slider on this page - http://exdeniz.protechnolog.danke.agency/career/

**Comment by rcbyr** [comment]
Hey @exdeniz 

I think to achieve this behavior, it would be easier to use the slider with these options:

```javascript
new KeenSlider("#slider", {
  slidesPerView: 2,
  centered: true,
})

```

Do you agree?

**Comment by exdeniz** [comment]
No, it's similar behavior, but a little wrong. 
I make the first slide offset equal to the global padding container. 
I drew a quick layout to explain the idea.

### Center slides:
![](https://femto.pw/6ikk.png)

### Slider with offset, start position.
![](https://femto.pw/z42a.png)

### Slider with offset, second slide position.
![](https://femto.pw/nuck.png)

### Slider with offset, last slide postion.
![](https://femto.pw/rxj7.png)

**Comment by rcbyr** [comment]
Hello @exdeniz 

okay, I get it now. I'll put it on my list, but I can't tell you when I'm gonna do it. There are some more important features for me right now that need some time. But I hope to give you this feature soon.

**Comment by exdeniz** [comment]
> Hello @exdeniz
> 
> okay, I get it now. I'll put it on my list, but I can't tell you when I'm gonna do it. There are some more important features for me right now that need some time. But I hope to give you this feature soon.

Thank you, I understand that there are more important things, such as `width:auto` for slides. I just hope to find a light version of swiper.js for my projects.

**Comment by rcbyr** [comment]
@exdeniz 

I think I saw this project on reddit. https://github.com/joe223/tiny-swiper

Maybe, you should give it a try, if you look for a swiperjs-like lib.

**Comment by sergiodebei** [comment]
What about adding an extra empty div as last slide? It might be a quick solution

**Comment by exdeniz** [comment]
> What about adding an extra empty div as last slide? It might be a quick solution
Adding extra slides makes it bad for navigation.

**Comment by setianke** [comment]
@exdeniz 

I achieved your desired behavior with simple CSS: 

Give the `keen-slider` div overflow visible and wrap the slider in a div with padding as desired: 

https://codesandbox.io/s/new-frost-xkkm7?fontsize=14&hidenavigation=1&theme=dark

**Comment by dhananjaygandhi** [comment]
What about one side offset. For example
First slide
<img width="361" alt="Screenshot 2021-05-29 at 10 45 57 AM" src="https://user-images.githubusercontent.com/717821/120058892-609f0500-c06b-11eb-87e2-5fe54b69a8ce.png">

Last slide
<img width="367" alt="Screenshot 2021-05-29 at 10 46 24 AM" src="https://user-images.githubusercontent.com/717821/120058909-77ddf280-c06b-11eb-9921-53a60363d4e2.png">

**Comment by dhananjaygandhi** [comment]
What about one side offset. Like
First Slide
<img width="284" alt="Screenshot 2021-05-29 at 10 51 34 AM" src="https://user-images.githubusercontent.com/717821/120058976-14a09000-c06c-11eb-9e42-616225be14fd.png">

Middle
<img width="279" alt="Screenshot 2021-05-29 at 10 52 34 AM" src="https://user-images.githubusercontent.com/717821/120058986-2aae5080-c06c-11eb-9774-bf06c1f43f99.png">

Last
<img width="285" alt="Screenshot 2021-05-29 at 10 51 56 AM" src="https://user-images.githubusercontent.com/717821/120058991-3a2d9980-c06c-11eb-80e7-4df09129070d.png">

**Comment by rcbyr** [comment]
In the new version of keen-slider you can configure the sizes, origins and spacing of each slide separately. So, I think this issue can be closed.

**Comment by madebyfabian** [comment]
@liqueflies I had the same thing. You can specify `slides.perView = 'auto'` and then give every slide element a `min-width` and `max-width`. I used 75vw, but you can also set pixels.

**Comment by rcbyr** [comment]
Hey @liqueflies 

would it be helpful when the origin parameter can be a function?

**Comment by ArekBartnik** [comment]
@rcbyr if the `origin` became a function would it be possible to pass to it if it is a "looped" slide?
I'm working on a slider in which the first slide is aligned to left and the rest is centered but if I set `origin` to 0 then all "first" slides will be rendered with this `origin`.

**Comment by timfuhrmann** [comment]
@rcbyr If origin could be a function and container size is provided, one could transform the px value into the value related to the container size. Anyways, unfortunately this does not help to achieve inline padding, as the last item would scroll to padding left. Happy to dig in and create a pull request. 

Following @setianke's approach does not work for some cases where `loop` is enabled, since the extra padding is not added to the slider's container size.

**Comment by rootEnginear** [comment]
Here's a snippet me and my colleague cook today:

```ts
const createSlideConfigWithOffset =
	({ perPage = 3, sideOffset = 20, spacing = 8, loop = false } = {}) =>
	(sliderSize: number, slides: HTMLElement[]): TrackSlidesConfigOption =>
		slides.map((_, slideIndex) => {
			const size = (sliderSize - (sideOffset * 2 + spacing * (perPage - 1))) / perPage
			let origin = sideOffset
			if (!loop && slideIndex > slides.length - perPage) {
				origin += (size + spacing) * (perPage - (slides.length - slideIndex))
			}
			return {
				size: size / sliderSize,
				spacing: spacing / sliderSize,
				origin: origin / sliderSize,
			}
		})
```

## Usage:

```ts
const [ref] = useKeenSlider<HTMLDivElement>({
	slides: createSlideConfigWithOffset({ perPage: 5, sideOffset: 20, spacing: 10 }),
})
```

With Looping:

```ts
const [ref] = useKeenSlider<HTMLDivElement>({
	loop: true,
	slides: createSlideConfigWithOffset({ loop: true }),
})
```

**Comment by NickWoodward** [comment]
> Here's a snippet me and my colleague cook today:
> 
> const createSlideConfigWithOffset =
> 	({ perPage = 3, sideOffset = 20, spacing = 8, loop = false } = {}) =>
> 	(sliderSize: number, slides: HTMLElement[]): TrackSlidesConfigOption =>
> 		slides.map((_, slideIndex) => {
> 			const size = (sliderSize - (sideOffset * 2 + spacing * (perPage - 1))) / perPage
> 			let origin = sideOffset
> 			if (!loop && slideIndex > slides.length - perPage) {
> 				origin += (size + spacing) * (perPage - (slides.length - slideIndex))
> 			}
> 			return {
> 				size: size / sliderSize,
> 				spacing: spacing / sliderSize,
> 				origin: origin / sliderSize,
> 			}
> 		})
> 
> ## Usage:
> 
> const [ref] = useKeenSlider<HTMLDivElement>({
> 	slides: createSlideConfigWithOffset({ perPage: 5, sideOffset: 20, spacing: 10 }),
> })
> 
> With Looping:
> 
> const [ref] = useKeenSlider<HTMLDivElement>({
> 	loop: true,
> 	slides: createSlideConfigWithOffset({ loop: true }),
> })

you sir, are an absolute legend. thank you!

**Comment by adamchipperfield** [comment]
Has anyone got a solid solution to this? @rootEnginear's solution sort of works, but is quite buggy and I'm struggling to resolve it.

I really need a tidy way to do this.
