### ISSUE TITLE
Move slides when scaling one Slide

### ISSUE THREAD

**Issue by DaniloTrotta** [rcbyr/keen-slider#250]
Hi, first of all thank you for this amazing library!

I am trying to accomplish a Slider which has an x Amount of slides which are scaled by the factor of 1.2 on hover. This is working currently , but I am wondering if it is possible to move all Slides on the right side of the scaled slide accordingly to the scaling.

I made a picture to illustrate better what I mean: 
![Bildschirmfoto 2022-07-19 um 17 25 12](https://user-images.githubusercontent.com/104756510/179788519-4f5fb405-be49-4a05-8e61-fb7157753c7f.png)

Is it possible to accomplish this? 

I hope to hear from you soon!

**Comment by rcbyr** [comment]
Hey @DaniloTrotta 

sorry for the late answer. It would be nice if you have a code example or something similar where I can try to achieve the desired behavior. In general I would say it is probably possible.
