### ISSUE TITLE
Origin: center

### ISSUE THREAD

**Issue by pt-sublime** [rcbyr/keen-slider#252]
I have 10 images, and the perView setting set as 5 images.

When I use origin: center, it won't show more than 3 images at the start, as the first image is centered (so 2 blanks at top).

Is there any support/setting for always showing a minimum of slides even with the centering option enabled?

A little hack-ish way I tried was setting the "initial" setting to 2, and that delivers the intended behavior somewhat. However, as soon as you click image 1 or 2, the same issue will re-appear again.

**Comment by rcbyr** [comment]
Hey @pt-sublime 

the easiest way is to use the range property. See here: https://codesandbox.io/s/crazy-hooks-e49g56?file=/src/App.js
