### ISSUE TITLE
wrong slide size

### ISSUE THREAD

**Issue by chocovelod** [rcbyr/keen-slider#253]
Hey there. When page is loaded second slide have some wrong size.
<img width="624" alt="Снимок экрана 2022-07-26 в 14 34 23" src="https://user-images.githubusercontent.com/65286428/180996641-430fd08e-94b1-4e5f-9b92-a55fff5fb98d.png">

But just a little resize of page fixing that
<img width="627" alt="Снимок экрана 2022-07-26 в 14 36 20" src="https://user-images.githubusercontent.com/65286428/180996765-0133bce0-718a-4229-9ce8-ec039188a65c.png">

Can anybody explain how to fix this without resize?

**Comment by chocovelod** [comment]
Hey people! How can i set max-width to slide?

**Comment by rcbyr** [comment]
Hey @chocovelod 

it would be nice to have a reproducible code example, then I could help you more easily. The problem is that the layout changes after the slider is initialized.

**Comment by chocovelod** [comment]
Problem was solved by using max-width on whole div with className="keen-slider"
