### ISSUE TITLE
Not able to move/drag to other cards when using static content to populate slider

### ISSUE THREAD

**Issue by abishekilango-wayfwd** [rcbyr/keen-slider#258]
Version used: 6.6.5

Slider is implemented with react hook. I did some digging around and found that the size property of the slider is `1` which is not the container/viewport width.

But when added a delay of ~1s before rendering using a loading state, the slider works as expected. In this case, the size property has the correct container width.

**Comment by rcbyr** [comment]
Can you update to the current version 6.6.7? Is the error still there?
