### ISSUE TITLE
Handling 2-way slide navigation

### ISSUE THREAD

**Issue by harrygr** [rcbyr/keen-slider#259]
I'm trying to use keen slider where both the slider and a list of buttons can react to a given selected slide.

See this example: https://codesandbox.io/s/blissful-chatterjee-e42r1d?file=/src/App.tsx

I have a slider consisting of 5 slides. When the slide changes I want to update the component `selectedSlide` state with the currently active slide ID. I use this state to colour a corresponding button elsewhere in the component.

In addition to this, when a button is clicked I also update the `selectedSlide` state. I'm using a `useEffect` hook to subscribe to this state and change the selected slide in the slider using its `moveToIdx` method.

This almost works, however there's a problem with the fact that `moveToIdx` fires off the `slideChanged` event callback as it steps through the slides from <current slide> to <target slide>, in turn updating `selectedSlideId` state and causing the `useEffect` to fire again. This then prevents the target slide from being reached if it's more than 1 slide away from the current slide.

You can observe this behaviour in the codesandbox by starting from slide 1 and clicking button 5.

Is there anyway to suppress the firing of the `slideChanged` for the intermediate slides with `moveToIdx`? Or is there a better way to achieve the above?

 --

Note: the sandbox is a contrived example; in reality things are more complex. I.e. I'm using useEffect here as the state for the selected slide ID actually lives externally to the slider component, so just calling `moveToIdx` directly from a button is not an option.

**Comment by rcbyr** [comment]
Hey @harrygr 

I adjust your codesandbox. https://codesandbox.io/s/zealous-frost-rujsrw?file=/src/App.tsx
