### ISSUE TITLE
Refresh() does not override original method

### ISSUE THREAD

**Issue by pupubird** [rcbyr/keen-slider#26]
Hi!
So I had been trying to override the `slideChanged()` method using the `refresh()` method, as mentioned in the documentation, the `refresh` method will accept an object that will initialize the slider and override with the method passed in the options object:

Original 

```javascript
      slideChanged: s => {
          state = s.details().relativeSlide;
      }
```

Using a button onclick function to call the refresh:

```javascript

  function move_to_slide(n) {
    slider.refresh({
      slideChanged: s => {
        state = s.details().relativeSlide;
        console.log("Slide change");
      }
    });
    slider.moveToSlideRelative(n);
  }
```

Expected output:
It will console log "Slide change" when after I click the button and interact with the slider

Actual output:
No log is output in the console.

Very much thanks for helping!

**Comment by rcbyr** [comment]
Hey @pupubird 
Thanks for the hint. I just fixed it, it will be in the next release. (probably today)

**Comment by pupubird** [comment]
Thanks!
