### ISSUE TITLE
Stop auto move on mouse over

### ISSUE THREAD

**Issue by sorknes** [rcbyr/keen-slider#262]
Hi,

I would like to stop [auto move](https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/autoplay/automove/react-typescript?file=/src/App.tsx) on mouse over. How would you solve this, or does anyone have an example?

**Comment by ponciusz** [comment]
Hi
check this: https://codesandbox.io/s/keen-slider-auto-move-ifqsjj?file=/src/App.tsx

```
      onMouseEnter={() => {
        if (slider.current) {
          slider.current.animator.stop();
        }
      }}
      onMouseLeave={() => {
        if (slider.current) {
          slider.current.moveToIdx(
            slider.current.track.details.abs + 5,
            true,
            animation
          );
        }
      }}
```

**Comment by sorknes** [comment]
Perfect @ponciusz - Thanks!

**Comment by nalovehs** [comment]
hello.
I came here while looking for a slider that can use media queries. Thanks for making a great slider.

I am a beginner who has just started studying JavaScript.
I've been looking at this example and researching it for hours, but I'm not sure, so I'm asking a question.
Can you give me an example of this as VANILLAJS?
Sorry to bother you.

**Comment by nalovehs** [comment]
https://github.com/rcbyr/keen-slider/issues/262#issuecomment-1240499984
바로 위에있는 예제를 바닐라 자바스크립트로 알려줄 수 있는지 문의한 것입니다.
나는 자바스크립트를 공부하기 시작한 초보이고 위 react나 타입스크립트는 몰라서 chatGPT에게는 여러번 물어봤으나 성공하지 못했습니다.

정리하자면 https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/autoplay/automove/javascript?file=/index.html
이 예제를 마우스 오버 시에 자동 플레이가 정지되고 마우스 오버가 아닐 때는 다시 재생하고 싶은 것입니다.
감사합니다
