### ISSUE TITLE
Slides derail when viewport changes only in one dimension (help wanted)

### ISSUE THREAD

**Issue by Asbestcode** [rcbyr/keen-slider#264]
I am working on a simple full screen image slider that moves horizontal on landscape _and vertical on portrait._
The slides are centered and use the full height _and width._ I got what i wanted by setting min-width _and min-height_ to fit-content, but there is still one problem. If the window is resized only in height _or width,_ the slides derail:

https://codesandbox.io/s/recursing-cookies-2g7v3s?file=/index.html

Knowing my images will always have the same aspect ratio, i tried another solution with
```
perView: () => {
                return (window.innerWidth / (window.innerHeight * 1.5))
```
but resizing the window in height when in landscape _and in width when in portrait_ does not affect the scaling of the slides:

https://codesandbox.io/s/recursing-goldwasser-eoquu2?file=/index.html

I doubt that this is an issue of Keen, but i am going in circles. 
Pease help, how can i avoid these glitches?

**Comment by rcbyr** [comment]
Hey @Asbestcode 

maybe there is a bug. Does the ResizeObserver-plugin fix your problem. See here: https://codesandbox.io/s/dreamy-germain-8cvn3m?file=/index.html:0-2217

**Comment by Asbestcode** [comment]
Yes @rcbyr the ResizeObserver-plugin fixes the issue.

Separately, i had another issue where the slides don't align properly after the images are loaded for the first time (i could not reproduce it on CodeSandbox: https://asbestcode.github.io/RO_fit-content/), which doesn't happen when I calculate the slides per view instead of "auto". So i am now going with that and ResizeObserver plugin. 

Thank you and greetings to the baltic sea!

**Comment by Asbestcode** [comment]
Closing the issue
