### ISSUE TITLE
autoplay issue in NextJs

### ISSUE THREAD

**Issue by kmcabano** [rcbyr/keen-slider#266]
hello, fairly new to all of this so i apologize if this is a dumb question. I'm using NextJs. i've created a slider set for an automatic, smooth, continuous scroll much like the one in [this example](https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/autoplay/automove/react?file=/src/App.js). it appeared to work, but upon refreshing the page, the animation stopped. i've since found that when the page loads, it is static. if I tweak any code in my editor, triggering a refresh, it begins moving. it also begins moving if I resize the window. I assume this has something to do with the SSR and the answer may lie in some sort of useEffect situation? but I am at a loss, and can't find anything useful online about this. if anyone might have a suggestion it would be much appreciated.

**Comment by ponciusz** [comment]
if it stops from some reason try to force move it by effect I did some pause/start example recently you could use some effect like this
```
...yourCode
const [loaded, setLoaded] = useState(false)
...yourCode
   created() {
      setLoaded(true)
    },
...yourCode
  useEffect(() => {
    if (instanceRef.current) {
      instanceRef.current.moveToIdx(
        instanceRef.current.track.details.abs + 5,
        true,
        animation
      );
    }
  },[loaded])
...yourCode
```

number five should be your elements length - 1 probably.
 and your `loaded` is in effect dependency 

personally I recommend to use Observer and start/pause slider based on if its in view as your performance might suffer if its keep updating DOM

**Comment by rcbyr** [comment]
Hey @kmcabano 

please update your version to v6.8.2. I've created a fix for the use with React 18, which I believe you are using.

**Comment by kmcabano** [comment]
I found out that it worked on the deployed version of the site, just not on my local copy
