### ISSUE TITLE
Blocking of mouse click events is broken since 6.8.0

### ISSUE THREAD

**Issue by PaulSchiretz** [rcbyr/keen-slider#267]
Hi @rcbyr,

Since the last update the blocking of link clicks while dragging doesn't work anymore on Desktop(e.q. Mouse input) on touch devices it works fine. Tested on chrome. I have seen you changed the drag logic for better performance, but this breaks the slider on desktop. I guess it might be a timing issue between click and drag start events or mouse release and drag end. I currently rolled back to 6.7 can you please have a look at that?

Thanks,
Paul

**Comment by rcbyr** [comment]
Hey @PaulSchiretz 

thank you for noticing me about this problem. I have created a fix in v6.8.1.

**Comment by PaulSchiretz** [comment]
Perfect, once it's available via jsdelivr i give it a try!

Thank you!

**Comment by PaulSchiretz** [comment]
Works! :-) Thank you!
