### ISSUE TITLE
Fixed height slider with variable width image slides

### ISSUE THREAD

**Issue by slavanossar** [rcbyr/keen-slider#269]
I'm having an issue creating a particular layout, where the slider has a fixed height and contains images with different aspect ratios, with options `mode: 'free-snap'` and `slides.perView: 'auto'`.

![slider](https://user-images.githubusercontent.com/7077600/191201109-366d4762-d035-4794-a8bd-87f5b9ea4619.jpg)

I've created an example repo here: https://github.com/slavanossar/keen-slider-auto-width-image-slides

Here's a quick breakdown of the behaviour:

• On initial page load, track length is calculated correctly and slider functions as expected.
• When navigating from another page, track length is calculated as shorter than it actually is, preventing all the images from being viewed.
• When destroying/creating the sliders (using a toggle checkbox), the track length is calculated as longer than it actually is.

Also this isn't strictly related to the above, but I've also noticed that the slider destroys itself immediately on navigating to a different page, removing the spacing between slides. Is this something that can be prevented? Or should I hook into the `destroyed` event and apply styles myself?

**Comment by rcbyr** [comment]
Hey @slavanossar 

please have a look at this codeexample. https://keen-slider.io/examples#resize

The ResizePlugin will fix your problem.
