### ISSUE TITLE
Rubberband might not pull back

### ISSUE THREAD

**Issue by badtant** [rcbyr/keen-slider#27]
Hi,
First of all thanks for a great slider, I'm really enjoying it.

I ran in to a little bug where the "rubberband" might not pull the slides back if you push it enough.
See attachment.

Thanks
[rubberband.mov.zip](https://github.com/rcbyr/keen-slider/files/4856014/rubberband.mov.zip)

**Comment by rcbyr** [comment]
Hey @badtant

thank you very much for the hint. I was able to reproduce this and will fix it soon.

**Comment by rcbyr** [comment]
This should no longer occur in the new version.

**Comment by xin2014** [comment]
Still exists on version 6.2.0
[official demo](https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/ios-like-picker/time/react-typescript?file=/src/App.ts
change height higher to easier to reproduce
![动画](https://user-images.githubusercontent.com/7124907/144399167-161a20a3-3cba-403c-8f7c-5d3f77cef0b0.gif)
x)

**Comment by rcbyr** [comment]
Thanks for the pointer. I will have a look at it.

**Comment by xin2014** [comment]
clearer gesture to reproduce
![y](https://user-images.githubusercontent.com/7124907/144402680-dda3b1ac-6168-4c98-ab5e-9a90cf95c993.gif)

**Comment by rcbyr** [comment]
Hey @xin2014 

thanks again for the hint.
I just released a patch for that. (v6.2.2)
