### ISSUE TITLE
How to know which element is in center, when I use more than 1 per view

### ISSUE THREAD

**Issue by guilhermediniz1** [rcbyr/keen-slider#270]
I wanted to know if there is a way to know which element is centered
![image](https://user-images.githubusercontent.com/50873941/192046324-5dee9b25-3be1-4075-823e-76f09cd31471.png)
here, for example the element three is at center. So maybe there is a method for this.

I tried an approach using the total length and finding which element is positioned at middle, but i was kinda bad.

**Comment by rcbyr** [comment]
You can always get the currently active slide (relative and absolute) from the slider instance. There are also hooks that are triggered when slides are changed. I have created a code sandbox for yours: https://codesandbox.io/s/friendly-kalam-8u4uec?file=/index.html

**Comment by guilhermediniz1** [comment]
Thanks!
