### ISSUE TITLE
Property 'next' or 'prev' does not exist on type with React Native useKeenSliderNative hook

### ISSUE THREAD

**Issue by demosofa** [rcbyr/keen-slider#273]
I followed official doc: [keen-slider/native](https://keen-slider.io/docs/react-native) and I noticed that the doc mentions the `next` and `prev` function from `slider` instance of **Event Hook** but when I used it in my expo project, they didn't appear when I typed and run in vscode and avd.

**Comment by rcbyr** [comment]
Thank you for noticing me about that. Fixed in version v6.8.3.
