### ISSUE TITLE
Clicking on the slider before it settled compounds the sliding inertia and continues scrolling

### ISSUE THREAD

**Issue by ivancuric** [rcbyr/keen-slider#276]
Reproduction in video:

https://user-images.githubusercontent.com/2827047/194546614-ff6f499e-5d74-4268-85b1-838287afcd5d.mov

**Comment by beadlespouse** [comment]
I wonder if this is related to #282 ?

On any slider with more than one slide visible, if you scroll and click just after the scroll finishes, the slider scrolls again to the next slide. This effect is also triggered by a mobile 'scroll' if the user 'scrolls' from the slider area.

This is clear to see on the examples page.

**Comment by rcbyr** [comment]
Thanks for sharing this. Fixed in version v6.8.3.
