### ISSUE TITLE
Position bar instead of dots.  Is this pattern possible?

### ISSUE THREAD

**Issue by dungle-scrubs** [rcbyr/keen-slider#277]
Hi,

I'm attempting to implement the following with `keen-slider` and have unsuccessfully tried to use the information within `track.details` to build it, but I can't get it right. 

The idea is to have the highlighted area of the bar represent the visible area of slides within the browser's viewport. In this picture, there would probably be about 6 slides. But if there were only 3, the highlighted area would take up about 95% of the bar.

Is something like this possible with the information provided in the instance?  

![CleanShot 2022-10-08 at 17 25 19](https://user-images.githubusercontent.com/13479539/194703604-976c7c1a-e55f-4d3a-8b25-667c059b994f.jpg)

Thanks

**Comment by rcbyr** [comment]
Hey @dungle-scrubs 

I've created a codesandbox for you: https://codesandbox.io/s/heuristic-ellis-b8w644?file=/src/App.js

**Comment by dungle-scrubs** [comment]
Thanks @rcbyr , much nicer than what I was attempting.
