### ISSUE TITLE
Drag event on a slide that contains a link

### ISSUE THREAD

**Issue by sergiodebei** [rcbyr/keen-slider#28]
If you drag an element that has link, on mouse up, the link is fired. I tried the "data-keen-slider-pe" but it doesnt seem to solve the issue. Thank you

**Comment by rcbyr** [comment]
@sergiodebei 
Thanks for the hint. I just fixed it and make a new release. (v5.0.4)

**Comment by sergiodebei** [comment]
Thank you so much for the quick response. Im gonna use it for some other new projects :)

**Comment by Hujjat** [comment]
Hey @rcbyr 

Just want to let you know, The links are still firing when you drag the slider. I tried `data-keen-slider-pe` on the link. Not working. 

Thanks

**Comment by patrickdmccarthy** [comment]
@rcbyr `data-keen-slider-pe` doesn't seem to work in  "keen-slider": "6.4.1" – is there another way around this in the new version?

**Comment by rcbyr** [comment]
Hey @patrickdmccarthy,

look at the documentary. https://keen-slider.io/docs#attributes
The attribute name has changed to `data-keen-slider-clickable`.

**Comment by sagrael** [comment]
v6.4.1 data-keen-slider-clickable not working on angular + [routerLink]

**Comment by rcbyr** [comment]
Hey @sagrael 

can you create a codesandbox? It works for me.

**Comment by danielrob** [comment]
`data-keen-slider-clickable` just seems to disable the click events altogether - no drag is now possible. Is it possible to have both drag and no mouseup link click after dragging?
