### ISSUE TITLE
Need help on writing plugin / override default config

### ISSUE THREAD

**Issue by xiaoyu-tamu** [rcbyr/keen-slider#280]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/33362998/195768459-c7354b89-9af5-44b3-8c0e-3bd01754768b.png">

I want set origin per slide, the first slide have origin "auto" (no padding on left side) and rest sliders have origin "center". 

I think the offset for origin is calculated here, is there anyway to change this via plugin?

https://github.com/rcbyr/keen-slider/blob/1b2f10817352b3964f262722d7311753ff2c6e38/src/plugins/web/web.ts#L171-L181

I want it be something like this 
```js

const origin =
  i == 0 ? 0 :
  originOption === 'center'
    ? 0.5 - size / 2
    : originOption === 'auto'
    ? 0
    : originOption
config.push({
  origin,
  size,
  spacing,
})

```

**Comment by rcbyr** [comment]
Hello @xiaoyu-tamu 

the only way to achieve that at the moment is the following: https://codesandbox.io/s/holy-lake-hmdbl8?file=/src/App.js

Hope it helps!

**Comment by xiaoyu-tamu** [comment]
it works, thanks
