### ISSUE TITLE
Slider skips to the next slide if slider is clicked immediately after a slide change (with slides per view > 1)

### ISSUE THREAD

**Issue by beadlespouse** [rcbyr/keen-slider#282]
If a user scrolls down the page immediately after having changed slide on a centered, snapping keen slider, the slider progresses to the next slide quite suddenly.

https://user-images.githubusercontent.com/40166257/196305163-2cfabd57-77f2-4fb0-a879-08ef1315a9d1.MOV

**Comment by beadlespouse** [comment]
Update - On any slider with more than one slide visible, if you scroll and click just after the scroll finishes, the slider scrolls again to the next slide. This effect is also triggered by a mobile 'scroll' if the user 'scrolls' from the slider area.

You can see this issue on the keen slider examples page. Try drag scrolling any slider with more than one slide visible, then click on that slider just after the drag animation has finished - it will skip again to the next slide.

This behaviour is most problematic on mobile where a user is likely to drag the slider across, and then scroll down. The scroll down action is registered the same way as a 'click' by keen slider, and again an unwanted slide skip is triggered (as in the video above).

**Comment by rcbyr** [comment]
Hey @beadlespouse 

this is the same problem as described here #276. The fix will deployed in the next days.

**Comment by rcbyr** [comment]
Fixed in version v6.8.3.
