### ISSUE TITLE
Q&A / Is it possible to exclude elements from slide touch?

### ISSUE THREAD

**Issue by pixobit** [rcbyr/keen-slider#283]
I'm looking for something similar to this [noSwipingClass](https://swiperjs.com/swiper-api#param-noSwipingClass)
Basically I have some slidable components, and have some draggable elements inside them. The problem is, that whenever I'm trying to drag the items inside the slider, the slider kicks in, and I can't drag them...

**Comment by rcbyr** [comment]
Hey @pixobit 

see `data-keen-slider-clickable` -> https://keen-slider.io/docs#attributes

Codesandbox example: https://codesandbox.io/s/bold-cray-dtrggo?file=/src/App.js

**Comment by pixobit** [comment]
Tried it, but unfortunatelly it seems like it's breaking things under the hood.
I tried recreating it here with sliderjs: https://codesandbox.io/s/zealous-shirley-g8imr9?file=/src/App.js

**Comment by pixobit** [comment]
Thanks for the quick fix, you're awesome!

One thing I noticed, is that it needs to be a wrapper element that gets the `data-keen-slider-clickable` attribute, otherwise it doesn't work. But you're probably aware of this, since you already added that in the example.
Anyways, great work. Will close this issue now.
