### ISSUE TITLE
Can't display slider inside headless UI modal with Next js / React

### ISSUE THREAD

**Issue by davidmedero** [rcbyr/keen-slider#287]
Very similar to this stackoverflow question: https://stackoverflow.com/questions/71934538/angular-keen-slider-slider-just-work-in-modal-when-resize-window

This issue is only present when keen slider is placed inside a modal. Slider works perfectly fine everywhere else. 
Slider appears if I resize the browser or change something random in my code then save. 

Any ideas on how I can work around this?

**Comment by rcbyr** [comment]
Hey @davidmedero 

please have a look at this example. https://keen-slider.io/examples#resize
The ResizeOberserver plugin will probably solve your problem.

**Comment by davidmedero** [comment]
That worked! Thank you so much!
