### ISSUE TITLE
update slides number on n-th slide

### ISSUE THREAD

**Issue by areepp** [rcbyr/keen-slider#296]
I want to make the slider updates the slides number and content state after reaching the last slide.

Have a look at this sandbox to see what I meant by it 
https://codesandbox.io/s/nifty-shockley-9gc6wt?file=/src/App.tsx

This is giving me a headache, is this possible?

**Comment by rcbyr** [comment]
Here is a fix for your example: https://codesandbox.io/s/modern-wood-vgkb1u?file=/src/App.tsx 

In general, this type of behavior should rather be implemented with a loop in combination with a range.

**Comment by areepp** [comment]
Thanks for the solution!

But there is one thing though, is there a way to make the animation smoother? On the last slide the animation seems to be a bit snappy.

**Comment by rcbyr** [comment]
This is because the length of the slider has been updated in slideChanged. This resets the slider. That's why I wrote that I would implement this type of behavior differently.

**Comment by areepp** [comment]
I'm not sure how to implement this using loop and range. Something like this? https://codesandbox.io/s/strange-hypatia-giq7zy?file=/src/App.tsx (I also give some more explanations of what i want to achieve to the sandbox)

Could you give an example?

**Comment by rcbyr** [comment]
Please have a look at this example: https://keen-slider.io/examples#dynamic-content

**Comment by areepp** [comment]
Thanks for pointing that out! Guess I didn't realize that there was a dynamic content example on the documentation.

And thank you for the package!
