### ISSUE TITLE
Is there a way to know what kind of direction slider will be moved to?

### ISSUE THREAD

**Issue by nemyung** [rcbyr/keen-slider#299]
Thanks for giving us wonderful slider lib. As i said above, I want to know the specific direction **after dragging**.
The direction comprises next or previous. I have started accessing `track.details.position` at `dragStarted` event and calculate next `position` at `dragEnded` event and calculate thresholds to define direction. I was guessing minimum offset is 0.5 but it is incorrect :( 

Edit+
The `slideChange` event is tempting to me. I will try to set local variable flag and do conditional logic inside event handler.

**Comment by praneshsingha** [comment]
This is an example of how you can check if the slider is moving to left or right
let a = 0
    let cityGuideOldSlide = 0;
{
        loop: true,
        initial: this.cityGuideCurrentSlide,
        slideChanged: (s) => {
          this.cityGuideCurrentSlide = s.track.details.rel
          if(this.cityGuideCurrentSlide > cityGuideOldSlide){
            // next slider
          }
          else if(this.cityGuideCurrentSlide < cityGuideOldSlide){
            // previous
          }
          cityGuideOldSlide = this.cityGuideCurrentSlide;
          a++;
          this.cityGuideFadeTimer();
        }
      },
