### ISSUE TITLE
TypeError when using dot navigation

### ISSUE THREAD

**Issue by gitgudcameron** [rcbyr/keen-slider#31]
Hi i'm getting an error in my Gatsby site when trying to use the dot naviation from [the example](https://codesandbox.io/s/keen-slider-navigation-react-pbmic?file=/src/App.js). I'm assuming this is from my lack of experience with react and gatsby. I've copied everything from the example - if anyone could help me, i'd apprecitate it! (Loving keen-slider btw - thank you!)

**TypeError: Array(...).keys(...).concat is not a function**
Compiled:
` Array(slider.details().size).keys().concat().map(function (idx) {`

Source:
```
{slider && (
        <div className="dots">
          {[...Array(slider.details().size).keys()].map(idx => {
            return (
              <button
                key={idx}
                onClick={() => {
                  slider.moveToSlideRelative(idx);
                }}
                className={"dot" + (currentSlide === idx ? " active" : "")}
              />
            );
          })}
        </div>
      )}
```

**Comment by rcbyr** [comment]
Hey,

I looked into the code example and couldn't find the use of concat(). So, I would remove it, since you not passing an array to it anyway.
For the sake of completeness, this would work:
```javascript
[...Array(slider.details().size).keys()].concat().map(function (idx) {
```

> (Loving keen-slider btw - thank you!)
Thank you very much!

**Comment by gitgudcameron** [comment]
Thanks for the quick reply @rcbyr.

Just to clarify, i'm using the exact same code as the react example, and it works perfect on codesandbox. The line with Concat is coming from the error message after it's compiled with Gatsby, i'm not adding it into the code. 

Again this is likely me just being a noob so i'll keep digging around but if anyone knows what i'm doing wrong, let me know! Cheers.

**Comment by rcbyr** [comment]
Hey @gitgudcameron 

I understand. Unfortunately, I couldn't reproduce this with gatsby. The navigation example works for me without errors or warnings.

**Comment by gitgudcameron** [comment]
Thanks @rcbyr sorry for wasting your time. If I figure out what my issue is, and if it's not too embarrassing 😂, I'll post it here.
