### ISSUE TITLE
How to get instance DOM or ID?

### ISSUE THREAD

**Issue by MennStudio** [rcbyr/keen-slider#32]
I try to add multiple keen-slider on one page with dots using vanilla.js. Some sliders may have 3 dots, some have 4.

When I change slider, the event "slideChanged" will pass "instance" value. But I can't map to the slider that using it. Then I can't add active class to proper ".dot" element.

Do you have any suggestion if I'd like to use multiple sliders? Or how can I get DOM / ID from instance.details() ?

Thank you very much for your time and your great slider :)

**Comment by rcbyr** [comment]
Hey @MennStudio 

I have created a small code example to show you a way how you could solve your problem. I hope this will help you.

https://codesandbox.io/s/keen-slider-navigation-vanilla-tgtxz?file=/index.html

**Comment by MennStudio** [comment]
Oh so fast. The code is clean and very easy to understand.

Thank you so much and keep up your great work :)
