### ISSUE TITLE
Width keen-slider__slide with scrollbar

### ISSUE THREAD

**Issue by RusakovDenis** [rcbyr/keen-slider#33]
Hi!

If the site has a preloader and at the beginning of the page loading there is no scrollbar, then "keen-slider__slide" has a width excluding the width of the scrollbar

**Comment by rcbyr** [comment]
Hey @RusakovDenis 

it would be easier to help you if you shared your code. Maybe on Codesandbox.

**Comment by RusakovDenis** [comment]
http://cf37691-bitrix.tw1.ru/ 
if not difficult, man

**Comment by RusakovDenis** [comment]
maybe width sccroll bar 16px not taken into account in the width of the slide

**Comment by rcbyr** [comment]
Okay, I see the problem. After initializing the slider, there's a resize that the slider doesn't recognize. The easiest thing you can do is to trigger the resize function after the initialization of your website or after the preloader was hidden. You can do this in this way: 
```javascript
var slider = new KeenSlider("#my-slider")
// your code
slider.resize()
```

I hope this will help you.

**Comment by RusakovDenis** [comment]
Thanks, man)

**Comment by RusakovDenis** [comment]
Great
