### ISSUE TITLE
Option to disable non-touch controls (mouse events)

### ISSUE THREAD

**Issue by markpinero** [rcbyr/keen-slider#36]
Hi,

Please add an option to remove mouse events to drag slides, allowing only touch events.

**Comment by rcbyr** [comment]
I will do that.

**Comment by Eugene0** [comment]
> Я сделаю это.
Hello, can you tell us if the option to disable non-touch controls has been added?

**Comment by Eugene0** [comment]
> I will do that.

Hello, can you tell us if the option to disable non-touch controls has been added?

**Comment by Eugene0** [comment]
I found a `controls ` property in the documentation that solves this problem. Thanks.

**Comment by rcbyr** [comment]
Example of how to do this: https://codesandbox.io/s/xenodochial-jones-tzggnm?file=/index.html

**Comment by TaniziaFagundes** [comment]
Para referências, usando a versão 5, conseguir remover usando o { controls: false }, o default dele é true.
