### ISSUE TITLE
Implement "passive" event listeners where events will not "preventDefault"

### ISSUE THREAD

**Issue by dualcyclone** [rcbyr/keen-slider#37]
I am unsure whether this is configurable at all, but at present, using `keen-slider` impacts our lighthouse scores on a project I'm working on for the following reasons:

https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools

I've investigated and can see that there are a few places where the event listeners never call `preventDefault`, or optionally call `preventDefault` based on configuration, and can therefore identify if they are `passive` or not.

Without this flag, the browser will wait for events to complete before deciding if it should take over scrolling. With the flag, the browser knows immediately that it can scroll without waiting.

---

Multiple event listeners in this block can identify that they are `passive` event listeners that will not prevent scrolling:
https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L161-L179

**dragstart**
https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L164-L167
Potentially above should indicate `passive` flag when `isTouchable()` returns `false`

**eventDragStart**
https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L80-L91
Doesn't appear to `preventDefault`, so the following references should use the `passive` flag:

https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L168
https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L172

**eventDragStop**
https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L93-L105
Doesn't appear to `preventDefault`, so the following references should use the `passive` flag:

https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L170-L171
https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L174-L175

**wheel**
https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L176-L178
Seems to indicate it is never passive, but is passive when `isTouchable()` returns `false`:

https://github.com/rcbyr/keen-slider/blob/1af5b7b6fd5649df4f1404e86a7392dd4b0b3f16/src/keen-slider.js#L156-L159

**Comment by rcbyr** [comment]
Hey @dualcyclone 

thanks for pointing that out. I rewrite this part at the moment and will take this into account for the new major release. Probably, I will also make a patch for the current release.

**Comment by rcbyr** [comment]
@dualcyclone

I fixed this with v5.2.2.
