### ISSUE TITLE
Slider with images not working when images aren't available immediately 

### ISSUE THREAD

**Issue by x4th** [rcbyr/keen-slider#38]
I've created a [reproducible example on codesandbox](https://codesandbox.io/s/keen-slider-default-react-ts-omnvk?file=/src/App.tsx).

Resizing the window makes the slider behave as expected.

This is how I'd use the slider in my app, where the variable containing the image URLs would be null initially and then set after fetching the data from the server. I'd like to understand why this is currently a problem. 

Thanks for creating this library.

**Comment by rcbyr** [comment]
Hey @x4th 

you only need to change the size of the slider manually after loading the images is complete.

See here: https://codesandbox.io/s/keen-slider-default-react-ts-k7wir?file=/src/App.tsx:975-1008

**Comment by x4th** [comment]
Thanks for the quick reply. Do you think the library should ideally detect and handle this automatically?

**Comment by rcbyr** [comment]
Yes, I plan to implement a mutation observer.

**Comment by x4th** [comment]
That's great to hear.

I've run into another issue which I'd like to ask you about and maybe it'll help someone out in the future as well. I'm trying to make the zoom out slider example work for me when again, I'm fetching image urls from the server and then the slides length isn't available immediatelly. Is there a way to [make this work](https://codesandbox.io/s/keen-slider-zoomout-react-vo4vo?file=/src/App.js)?

**Comment by rcbyr** [comment]
Currently, you can only change the slides with a refresh.  See here: https://codesandbox.io/s/keen-slider-zoomout-react-69dsk?file=/src/App.js

**Comment by yogeshkotadiya** [comment]
@x4th As a workaround, don't initialize the slider until you get the data.

Or you can manually refresh as @rcbyr Suggested.

```jsx
import * as React from "react";
import "./styles.css";
import { useKeenSlider } from "keen-slider/react";
import "keen-slider/keen-slider.min.css";

const target_images = [
  "https://images.unsplash.com/photo-1590004953392-5aba2e72269a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
  "https://images.unsplash.com/photo-1590004845575-cc18b13d1d0a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
  "https://images.unsplash.com/photo-1590004987778-bece5c9adab6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
  "https://images.unsplash.com/photo-1590005176489-db2e714711fc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80"
];

const Slider = ({images}: {images:any[]}) => {
  const [ref] = useKeenSlider<HTMLDivElement>();

  return (
    <div ref={ref} className="keen-slider">
    {images.map((src, idx) => (
      <div key={idx} className="keen-slider__slide">
        <img src={src} />
      </div>
    ))}
  </div>
  )
}

export default function App() {
  const [images, setImages] = React.useState();
  React.useEffect(() => {
    setTimeout(() => setImages(target_images), 1000);
  },[]);

  return (
    <React.Fragment>
      {Array.isArray(images) && (
        <Slider images={images} />
      )}
    </React.Fragment>
  );
}
```

**Comment by rcbyr** [comment]
You should follow the suggestion of @yogeshkotadiya.

**Comment by azhararmar** [comment]
> @x4th As a workaround, don't initialize the slider until you get the data.
> 
> Or you can manually refresh as @rcbyr Suggested.
> 
> ```js
> import * as React from "react";
> import "./styles.css";
> import { useKeenSlider } from "keen-slider/react";
> import "keen-slider/keen-slider.min.css";
> 
> const target_images = [
>   "https://images.unsplash.com/photo-1590004953392-5aba2e72269a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
>   "https://images.unsplash.com/photo-1590004845575-cc18b13d1d0a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
>   "https://images.unsplash.com/photo-1590004987778-bece5c9adab6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80",
>   "https://images.unsplash.com/photo-1590005176489-db2e714711fc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&h=500&w=800&q=80"
> ];
> 
> const Slider = ({images}: {images:any[]}) => {
>   const [ref] = useKeenSlider<HTMLDivElement>();
> 
>   return (
>     <div ref={ref} className="keen-slider">
>     {images.map((src, idx) => (
>       <div key={idx} className="keen-slider__slide">
>         <img src={src} />
>       </div>
>     ))}
>   </div>
>   )
> }
> 
> export default function App() {
>   const [images, setImages] = React.useState();
>   React.useEffect(() => {
>     setTimeout(() => setImages(target_images), 1000);
>   },[]);
> 
>   return (
>     <React.Fragment>
>       {Array.isArray(images) && (
>         <Slider images={images} />
>       )}
>     </React.Fragment>
>   );
> }
> ```

This seems to be a good solution and it worked for me.
