### ISSUE TITLE
Setting the slider when it has fewer slides than perView

### ISSUE THREAD

**Issue by SzymonCU** [rcbyr/keen-slider#380]
Hello,
I have a slider that has different settings for different resolutions.
Here is the code:
```
{
        loop: true,
        breakpoints: {
            "(max-width: 768px)": {
                slides: {perView: 2, spacing: 30},
            },
            "(max-width: 530px)": {
                slides: {perView: 1, spacing: 30},
            },
        },
        slides: {perView: 3, spacing: 30},
        defaultAnimation: {duration: 800},
    }
```

The problem occurs if I have <=3 slides.
The slider should "stop being a slider" and should display, for example, 1, 2 or 3 slides but then there should be no autoplay and no ability to move slides.

However, if I have 3 slides but go below 768px resolution then the slider should work normally because I have 2 slides visible.

Is it possible to set the slider as I described above?

**Comment by maxsplawski** [comment]
I'm actually having the same issue, would really appreciate any answer on this 🙏

**Comment by SzymonCU** [comment]
Closed, I found a solution to this problem.
