### ISSUE TITLE
Shortest route moveToSlide and loop

### ISSUE THREAD

**Issue by erikhuisman** [rcbyr/keen-slider#4]
For `loop: true`

If we have 5 slides and use `slider.next()` we move slide 5 > 1.
If we have 5 slides and use `slider.moveToSlide(0)` we move slide 5 > 4 > 3 > 2 > 1

It might feel the mostest native if we would slide the shortest route to the next slide.  

Use case: A slider with thumbails underneath for navigation

**Comment by rcbyr** [comment]
Yes, definetly. I'll fix that in the next few days.

**Comment by rcbyr** [comment]
@erikhuisman 

I have just released a new version v4.2.0 It has a new function moveToSlideRelative. This will provide what you needed with the parameter "nearest". See the [API](https://keen-slider.io/api/#methods)

**Comment by erikhuisman** [comment]
It works! Didn't expect you to add a whole new method for it. Hop it doesnt mess up your clean api.
