### ISSUE TITLE
Weird Resize Happening to All Slides

### ISSUE THREAD

**Issue by brandonbjs** [rcbyr/keen-slider#418]
This has happened twice now where the slides were perfectly sized and centered and then all of a sudden something begins drastically increasing the min-height and max-height of each .keen-slider__slide and overriding my CSS. There is no in-line or element styling in my code. Something is changing min/max height when the app is run. Below is a snip of my DevTools showing how large each slide is being resized to: 
![weirdResize](https://github.com/rcbyr/keen-slider/assets/68050507/e7c1add9-0351-4db0-afc0-38ac4758deeb)

Any insight on what might be causing these resizes would be much appreciated.

**Comment by brandonbjs** [comment]
Solved.

**Comment by nayanbamnote** [comment]
how?
