### ISSUE TITLE
Feature request: Accessibility

### ISSUE THREAD

**Issue by nihlton** [rcbyr/keen-slider#43]
Have you given through to making this accessible?

https://www.w3.org/WAI/tutorials/carousels/

nice to haves:  
keyboard navigation between slides
move focus into first slide after transition
convert to UL / LI elements
announce transitions via aria-=live

accessible example:  https://www.w3.org/WAI/tutorials/carousels/full-code/

Seems like some of this could be implemented by devs implementing your slider - but it would be nice if it was handled upstream

**Comment by rcbyr** [comment]
Hello @nihlton 

thanks for your request. The keyboard navigation may be one thing that could be integrated into the slider. The other things are currently out of scope and could be implemented very easily on your own.

**Comment by rcbyr** [comment]
Keyboard controls can now be added with custom plugins. See here: https://codesandbox.io/s/festive-brown-dc1n0

**Comment by mossypaul** [comment]
I'll also add that this would be great to be built in by default, it would be a win for accessibility if everyone got this
