### ISSUE TITLE
React Typescript dragSpeed for Date/Time pickers

### ISSUE THREAD

**Issue by joomation** [rcbyr/keen-slider#44]
I'm using React v16.3.1 and Typescript.
```tsx
dragSpeed: (val, instance) => {
      const height = instance.details().widthOrHeight;
      return val * (height / ((height / 2) * Math.tan(slideDegree * (Math.PI / 180))) / slidesPerView);
    },
```
I am getting an **error** about the type `(val, instance) => {...`
**and how do I set the type?**

Even if I specify as below, type error occurs.
`js(val:number, instance:any) => {...`

**Comment by rcbyr** [comment]
hey @joomation 

thanks for noticing that. Seems like the type definition isn't up-to-date. I will fix that.

Here is a quickfix:
```javascript
dragSpeed: ((val: number, instance: any) => {
      const height = instance.details().widthOrHeight
      return (
        val *
        (height /
          ((height / 2) * Math.tan(slideDegree * (Math.PI / 180))) /
          slidesPerView)
      )
    }) as any
```

**Comment by joomation** [comment]
Oh.. 
Thank you very much!!
