### ISSUE TITLE
Feature request: More agressive snap (one slide forward/back)

### ISSUE THREAD

**Issue by x4th** [rcbyr/keen-slider#45]
It would be really useful if the slider included a mode where the most you can move per swipe is one slide forward or back. Right now when mode is set to "snap" and I swipe faster the slider usually stops after two slides.

**Comment by rcbyr** [comment]
Thanks for the feedback. This will be fixed in the next major release.

**Comment by rcbyr** [comment]
The behavior is optimized. The slider orientates itself to the slide that was touched first.
