### ISSUE TITLE
Feature request: Tap to slide

### ISSUE THREAD

**Issue by x4th** [rcbyr/keen-slider#46]
If slidesPreView is more than 1, it would be great to be able to tap on a slide to make that one active.

**Comment by rcbyr** [comment]
Hello @x4th 

I'm currently working on the slider and will make an example of how to implement this.

**Comment by dereckquock** [comment]
yeah, for the [`centered mode`](https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/master/basic/centered/react?file=/src/App.js), it would be nice to be able to tap/click on the next or previous slide to select it

I implemented an example of this with _invisible_ previous and next buttons, but it doesn't allow you to click/tap and slide when starting the drag from those ends https://codesandbox.io/s/keen-slider-08pyu?fontsize=14&hidenavigation=1&theme=dark

**Comment by rcbyr** [comment]
I have created an example for this use case. https://codesandbox.io/s/unruffled-hofstadter-k1rb7?file=/index.html
