### ISSUE TITLE
Autoplay feature missing

### ISSUE THREAD

**Issue by Slowl** [rcbyr/keen-slider#5]
While testing it, I realised that the autoplay feature is missing. 

Are we going to see this implemented soon ?
Autoplay with the control of duration and an onHoverStop event would be a nice addition

**Comment by rcbyr** [comment]
Hello @Slowl,

I am currently working on the examples and will create an autoplay example for you.

The slider itself will not have this function, as this is too individual in my opinion.

**Comment by rcbyr** [comment]
Hey @Slowl,

I've created a code example for you. See [https://keen-slider.io/examples/#autoplay](https://keen-slider.io/examples/#autoplay)

**Comment by k-sav** [comment]
Is it possible to pause and play an autoplaying slider?

**Comment by rcbyr** [comment]
@k-sav: As you can see in the [example](https://codesandbox.io/s/keen-slider-autoplay-react-e7msi?file=/src/App.js), there is a function called setPause. You can use it to pause/play the autoplay slider.

**Comment by Catsvilles** [comment]
Thanks for the example, I'm also after this feature :)

**Comment by Slowl** [comment]
> Hey @Slowl,
> 
> I've created a code example for you. See https://keen-slider.io/examples/#autoplay

That's EXACTLY what I needed, thank you !
