### ISSUE TITLE
RequestAnimationFrame block by media(img, background etc.) rendering

### ISSUE THREAD

**Issue by chestnutchen** [rcbyr/keen-slider#50]
**Env:**
iOS webkit
A mediocre network traffic

**Problem:**
Found the issue that slide animation lost a lot of frames when page is almost loaded and ui thread is painting some media elements such as img tag or CSS background. 

**Some info:**
Dived into performance debugging and found the requestAnimationFrame was delayed by nothing. But it took 50ms, 100ms or even more time to do next `moveAnimateUpdate` detecting by `console.log`. The issue could be reproduced in the demo page without page cache in a mediocre network traffic.

**Comment by rcbyr** [comment]
Thank you very much. I will investigate this behavior and will create a fix.

**Comment by rcbyr** [comment]
At the moment, I don't think there is a performance problem with the slider. Therefore, I am closing this issue for the moment.
