### ISSUE TITLE
width will change when total slider number is smaller than slidesPerView

### ISSUE THREAD

**Issue by gaoljie** [rcbyr/keen-slider#52]
when the total slider count is smaller than slidesPerView, the slides width is not parentWidth / slidesPerview

this is the source code
https://codesandbox.io/s/keen-slider-spacing-react-forked-48x2h?fontsize=14&hidenavigation=1&theme=dark

```
import React from "react";
import { useKeenSlider } from "keen-slider/react";
import "keen-slider/keen-slider.min.css";
import "./styles.css";

export default (props) => {
  const [sliderRef] = useKeenSlider({ slidesPerView: 3, spacing: 15 });
  const [sliderRef2] = useKeenSlider({ slidesPerView: 3, spacing: 15 });

  return (
    <>
      <div ref={sliderRef} className="keen-slider">
        <div className="keen-slider__slide number-slide1">1</div>
        <div className="keen-slider__slide number-slide2">2</div>
        <div className="keen-slider__slide number-slide3">3</div>
        <div className="keen-slider__slide number-slide4">4</div>
        <div className="keen-slider__slide number-slide5">5</div>
        <div className="keen-slider__slide number-slide6">6</div>
      </div>
      <div ref={sliderRef2} className="keen-slider">
        <div className="keen-slider__slide number-slide1">1</div>
        <div className="keen-slider__slide number-slide2">2</div>
      </div>
    </>
  );
};
```

this is the screenshot
![image](https://user-images.githubusercontent.com/10665889/91902688-f598dd00-ec56-11ea-97e8-f218f85045fe.png)

Is it possible to keep the slider's width the same when the slider count is smaller than slidesPerView?

**Comment by rcbyr** [comment]
@gaoljie

It will be possible in the next version. I'm working a lot on this recently, so I hope I will release it soon.

**Comment by akisvolanis** [comment]
Any progress on this?

**Comment by rcbyr** [comment]
@akisvolanis Sorry, for the late answer. Not yet, my job, moving, and family keeps me very busy. But I think it will be something in January.

**Comment by spacedawwwg** [comment]
only way I've been able to solve this is with `!important` max-width min-width in my css :/

**Comment by clonestudios** [comment]
@spacedawwwg saved me dude. Thanks for the tip!

**Comment by rcbyr** [comment]
This is fixed in the new version.
