### ISSUE TITLE
Bug: cannot render slider correctly if the list is dynamic

### ISSUE THREAD

**Issue by gaoljie** [rcbyr/keen-slider#53]
Hi I encounter issue when I need to change the list for rendering the slide, after changing the list, the width of each slide cannot be set correctly.

example: 
https://codesandbox.io/s/keen-slider-multiple-react-forked-f8y2i?file=/src/App.js

**Comment by rcbyr** [comment]
Hello @gaoljie,

unfortunately, the slider currently has no built-in mutation observer. So you have to tell him if something has changed.

fixed example: https://codesandbox.io/s/keen-slider-multiple-react-forked-4xpgg?file=/src/App.js

**Comment by gaoljie** [comment]
thanks! the resize method works!
