### ISSUE TITLE
Feature Request: Overflowing Loop Support

### ISSUE THREAD

**Issue by slavanossar** [rcbyr/keen-slider#54]
**The Problem**

When trying to force `overflow: visible;` on `.keen-slider` and setting `loop: true` on the slider instance, slides appear and disappear as the slider jumps between the start/end transforms.

![keen-loop-overflow](https://user-images.githubusercontent.com/7077600/93781332-a00b8b00-fc6c-11ea-85bd-95946b986e0c.gif)

**Possible Solution**

I'm sure you've sen how other libs get around this by cloning the start/end elements, maybe could be done if `loop: true` is set. [Glide also has a really nice `peek` option](https://glidejs.com/docs/options/#peek), allowing elements just outside the bounds of the slider to be pulled in.

Also, thanks for creating this – all of the slider libraries I've tried over the past few years are either extremely large (swiper.js), or have average to horrible touch behaviour (glide.js and many others). You have nailed both of these, so well done!

**Comment by rcbyr** [comment]
Hello @slavanossar 

thanks for the feedback! I really appreciate it.

I've created an example that I hope will solve your problem. https://codesandbox.io/s/keen-slider-spacing-vanilla-forked-2z6ok?file=/index.html

**Comment by slavanossar** [comment]
@rcbyr amazing, thanks! didn't even think to try non-integers for `slidesPerView`.

**Comment by patrickbjohnson** [comment]
@rcbyr Sorry to chime in on an older ticket, happy to make my own. Trying to recreate this but doesn't seem like the `slidesPerView` is being respected. Purposely not setting widths on any element. The ultimate result should look something like this: 

<img width="185" alt="Screen Shot 2022-06-15 at 4 18 20 PM" src="https://user-images.githubusercontent.com/1939017/173919350-6e820886-a6ad-4c6d-a1ad-4826cdaccd92.png">

My code

```
<template>
  <div class="max-w-800 mx-auto md:flex md:items-center">    
    <div class="keen-slider" ref="carousel">
      <div class="keen-slider__slide text-center" v-for="(slide, index) in slides" :key="slide">
        <div
          :class="{
            'bg-thin-line': current === index,
            'bg-foam': current !== index
          }"
          class=" h-200 border border-cactus"
        >
        
          <!-- <div class="relative w-140 md:w-200 h-300 mx-auto flex items-center yellow-badge">
            <svg class="w-full" viewBox="0 0 200 200" shape-rendering="geometricPrecision" text-rendering="geometricPrecision">
              <ellipse rx="100" ry="100" transform="translate(100 100)" fill="#ffbe3e" stroke-width="0"/>
              <path id="curve" d="M18,100c-2.194643,41.477572,37.5218,83.618511,82,82c41.881999,2.029144,84.227971-37.48754,82-82" opacity="0" fill="none" stroke-width="0.5"/>
              <text width="200" fill="#01483A">
                <textPath class="font-thin text-xs tracking-wider" xlink:href="#curve" text-anchor="middle" startOffset="50%">
                {{ slide.title }}
                </textPath>
              </text>
            </svg>
            
            <div class="absolute inset-0 flex items-center justify-center">
              <img class="mx-auto" :src="slide.image.src" :alt="slide.image.alt">
            </div>
          </div> -->
        </div>
      </div>
    </div>
  </div>

</template>
<script>


import KeenSlider from "keen-slider"
import 'keen-slider/keen-slider.min.css'
export default {
  name: "TestCarousel",
  props: {

  },  
  data: () => {
    return {
      slider: null,
      current: 0,
      tallestSlide: 0,
      bp: '',
      slides: [
        {
          title: "Title here",
          copy: "This is some copy",
          image: {
            src: "https://dummyimage.com/640x360/fff/aaa",
            alt: "This is an alt"
          }
        },
        {
          title: "Title here 2",
          copy: "This is some copy",
          image: {
            src: "https://dummyimage.com/640x360/fff/aaa",
            alt: "This is an alt"
          }
        },
        {
          title: "Title here 3",
          copy: "This is some copy",
          image: {
            src: "https://dummyimage.com/640x360/fff/aaa",
            alt: "This is an alt"
          }
        },
        {
          title: "Title here 4",
          copy: "This is some copy",
          image: {
            src: "https://dummyimage.com/640x360/fff/aaa",
            alt: "This is an alt"
          }
        }
      ]
    };
  },
  computed: {
    dots() {
      return this.slider ? [...Array(this.slider.track.details.slides.length).keys()] : []
    },
  },
  methods: {
  },
  mounted() {
    console.log('slides: ', this.slides)
    if (this.$refs.carousel) {
      this.slider = new KeenSlider(this.$refs.carousel, {
        slidesPerView: 2,
        centered: true,
        slideChanged: (s) => {
          this.current = s.track.details.rel
        },
      })
      
    }
  },
};
```

**Comment by rcbyr** [comment]
Hey @patrickbjohnson 

the API has slightly changed since I commented this issue. If you are using v6.* you have to change the options to 
`slides: {
    perView: 2,
    origin: 'center',
  },
  slideChanged: (s) => {
    this.current = s.track.details.rel
  },`

**Comment by MickCoelho** [comment]
Hi!
There are some occurences for which the `perView` isn't an ideal solution. For example, I'm currently sizing the slider using some complex CSS grid logic. I could compute the `perView` easily, but that creates some layout shift. 
For a CSS only solution, this would be a great feature. Here's an example that I currently have: 
https://codesandbox.io/p/sandbox/crazy-leavitt-2wmrpq?file=%2Fsrc%2FApp.js%3A8%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsv048uq00073b6fdy52tjzk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsv048uq00033b6fp3jxafhj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsv048uq00043b6f7vvkn86t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsv048uq00063b6fpulb235h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsv048uq00033b6fp3jxafhj%2522%253A%257B%2522id%2522%253A%2522clsv048uq00033b6fp3jxafhj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsv06sgc00023b6fqottag46%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsv06sgc00023b6fqottag46%2522%257D%252C%2522clsv048uq00063b6fpulb235h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsv048uq00053b6fuynq3dmx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsv048uq00063b6fpulb235h%2522%252C%2522activeTabId%2522%253A%2522clsv048uq00053b6fuynq3dmx%2522%257D%252C%2522clsv048uq00043b6f7vvkn86t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsv048uq00043b6f7vvkn86t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by release-please** [comment]
Has anyone managed to fix this bug without a workaround?
