### ISSUE TITLE
Feature Request: Support Vue directive syntax similar to React Hooks

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [rcbyr/keen-slider#56]
As a Vue developer I would like to use directive based syntax that is similar to React Hooks:
```
import React from 'react'
import 'keen-slider/keen-slider.min.css'
import { useKeenSlider } from 'keen-slider/react'

export default () => {
  const [sliderRef, slider] = useKeenSlider()

  return (<div ref={sliderRef}>
    <div class="keen-slider__slide">1</div>
    <div class="keen-slider__slide">2</div>
    <div class="keen-slider__slide">3</div>
  </div>)
}
``` 

**Proposed Vue syntax:**
```
<template>
<div
        class="keen-slider"
        v-slider:mySlider="sliderOptions"
...
</div>
</template>

import 'keen-slider/keen-slider.min.css'
import { useKeenSlider } from 'keen-slider/vue'

const {directive} = useKeenSlider()

export default {
    name: 'MySlider',
    directives: {
      slider: directive
    },
   data() {
      return {
          sliderOptions: {...}
      }
    }
}
```
Such syntax will allow much cleaner slider instantiation with no need to do anything in mounted hook as well as no need to manually destroy slider instance since that can be done internally by watching directive detachment from the DOM

**Comment by rcbyr** [comment]
Hello @AndrewBogdanovTSS 

thanks for your request. I'll add it to my list. 
I'm currently working on a new version, which will be a complete rewrite and will add most of the missing features that people want. So I think it will take a few weeks.

**Comment by AndrewBogdanovTSS** [comment]
@rcbyr great to hear that and thanks for your efforts on this project!

**Comment by rcbyr** [comment]
I have added a composition API function for Vue 3 to the project. I don't plan to a directive, anymore.
