### ISSUE TITLE
Bug: Slides option is not working with Vue $refs

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [rcbyr/keen-slider#57]
According to the [docs](https://keen-slider.io/api/#api) **slides** property should support array of raw html elements but when used with Vue $refs property it's not working as expected.
Reproduction link: https://codesandbox.io/s/keen-slider-default-vue-forked-zpkur?file=/src/Slider.vue

Expected result: slider initializes correctly when $refs is used

**Comment by slavanossar** [comment]
@AndrewBogdanovTSS `slides` defines the selector used to find the slide elements within the `.keen-slider` element, by default it is `.keen-slider__slide`. So in your example you don't need to define `slides`, removing it correctly initialises the slider.

**Comment by AndrewBogdanovTSS** [comment]
@slavanossar if I was satisfied with using default class I wouldn't create this bug report. I don't want to use the default `.keen-slider__slide`, since my slides are passed to a component via scope slots and I have 0 guarantees that someone will provide default class just to make things work. It just not how it should work!

**Comment by rcbyr** [comment]
Hello @AndrewBogdanovTSS 

thanks for reporting this bug. I'll fix this. Until then, you can pass the refs with a function like this:

```javascript 
slides: () => this.$refs.slides
```

**Comment by AndrewBogdanovTSS** [comment]
@rcbyr thanks for the workaround. It works 👍

**Comment by rcbyr** [comment]
Unfortunately it took some time, but this is fixed in v6.3.1.
