### ISSUE TITLE
How can I handle prev and next events?

### ISSUE THREAD

**Issue by ttoni** [rcbyr/keen-slider#62]
I want to update some field on my page after the next and prev functions were called.  
I know there are the beforeChange, afterChange and slideChanged events but they also get trigger after the slider is initialized.

**Comment by rcbyr** [comment]
Hey @ttoni,

there is no built-in hook at the moment. However, here is a possible implementation: https://codesandbox.io/s/keen-slider-navigation-vanilla-forked-4unls?file=/index.html:4710-4721

I hope this helps.

**Comment by ttoni** [comment]
This solved my issue 👍🏻
