### ISSUE TITLE
Browser subpixel rendering issue

### ISSUE THREAD

**Issue by roderickhsiao** [rcbyr/keen-slider#63]
We are currently doing JavaScript calculation 

```js
      const style = `calc(${100 / slidesPerView}% - ${
        (spacing / slidesPerView) * (slidesPerView - 1)
      }px)`
```

This will cause slide count like 3 becomes `calc(33.3333% - 0)`, browse hence will have very small sub-pixel rendering and make every slide move slightly miss some pixel.

We can do custom attribute and let browser to calculate itself. take 3 pages for examples

```css
 --size: calc(1/3);
max-width: calc(var(--size) - 0)px
```

Then the subpixel rendering issue will be fixed.

Our example here is the child supposed to be 68px x 68px, and parents are correctly display 68 * 3, but each slide unit has been assign max-width based on width calculation 33.3333%, and cause slightly move. (especially very obvious if we have a fixed element there trying to match the centered item position)

<img width="342" alt="Screen Shot 2020-10-21 at 6 49 04 PM" src="https://user-images.githubusercontent.com/3906130/96811928-e4f02200-13d0-11eb-815f-922f2efdd933.png">

**Comment by roderickhsiao** [comment]
still seeing same issue with custom attribute

**Comment by Shaokun-X** [comment]
@roderickhsiao Hello, did you manage to solve this?

**Comment by balthazar** [comment]
Seeing the same issue
