### ISSUE TITLE
Right arrow when there are multiple slides

### ISSUE THREAD

**Issue by leonmanifesto** [rcbyr/keen-slider#65]
Hi, love this slider!

What's the best way of handling the disabled state on the right arrow when there are multiple slides in view (slidesPerView).

See an example here:

https://codesandbox.io/s/keen-slider-navigation-vanilla-forked-mi39m?file=/index.html

Many thanks!

**Comment by rcbyr** [comment]
Hey @leonmanifesto 

thanks a lot. Here is a possible solution: https://codesandbox.io/s/keen-slider-navigation-vanilla-forked-dq2e2?file=/index.html

Hope this helps!

**Comment by leonmanifesto** [comment]
Hello @rcbyr!

Thank you, that worked very well!

My slidesPerView changes with breakpoints so instead of setting it as a const variable I used `instance.details().slidesPerView`. I had to update keen-slider js from 5.0.2 to 5.2.4 for this to be available. 

You can see it in action here: https://codesandbox.io/s/keen-slider-navigation-vanilla-forked-izv3u?file=/index.html

I also use `Math.round` because I use decimals in my `slidesPerView` so the next slide is revealed slightly (which actually works pretty well!).

Thanks again
