### ISSUE TITLE
Disable on certain breakpoints

### ISSUE THREAD

**Issue by grantkang5** [rcbyr/keen-slider#66]
Would be nice if having `slidesPerView` at 0 would disable the slider.

**Comment by rcbyr** [comment]
Hey @grantkang5,

didn't find an elegant way to achieve that yet. I will come up with a solution soon. Until that, you could simply add a `display: none;` on a certain breakpoint.

**Comment by WebDevCode** [comment]
Hi, tried to hide this at certain breakpoint by setting the container to `display:none;` However, if I resize the browser and the slider is displayed again, it stops working. Tried to refresh the slider but no go. It won't work unless I refresh the page itself. Any thoughts on what I'm doing wrong?

**Comment by cmalven** [comment]
This would be a very valuable feature for me, too. A very common design requirement for the sites I work on is that the content only behaves as a slider at mobile sizes, and falls back to displaying the slides as individual, stacked content at larger sizes (or vice versa). Seems like the only way to handle this right now would be to destroy and refresh the slider when the breakpoint threshold is crossed, but I would love to have a nicer way of accomplishing this using the `breakpoints` functionality that is already built in.

e.g. something like:

```
      breakpoints: {
        '(min-width: 768px)': {
          disabled: true
        }
      },
```

Ideally, this would both disable slider javascript and unset any styles applied by `keen-slider` or `keen-slider__slide`

**Comment by gilesbutler** [comment]
Just came across as I'm looking for the same functionality.

Currently hacking it with...
```
breakpoints: {
        "(min-width: 1280px)": {
          controls: false,
          slidesPerView: 6,
          spacing: 0,
        },
}
```

```
.keen-slider__slide {
  @screen xl {
    max-width: 100% !important;
    min-width: 0 !important;
  }
}
```
@cmalven's solution would be really nice.

**Comment by boompikachu** [comment]
Another way around to hide the carousel is to wrap the carousel with a div then at that specific breakpoint, make the div height to 0px and overflow hidden.

**Comment by glutaminefree** [comment]
Vote for native slider option for this! :+1:

**Comment by rcbyr** [comment]
There is now a 'disabled'-option that can also be used in the breakpoint option. If true, all styles and events are removed from the container. Also, an attribute is set to the container - 'data-keen-slider-disabled'. So you could add this to your stylesheet:
`.keen-slider[data-keen-slider-disabled]{
  display: none;
}`

**Comment by Nivethan-Ar** [comment]
> There is now a 'disabled'-option that can also be used in the breakpoint option. If true, all styles and events are removed from the container. Also, an attribute is set to the container - 'data-keen-slider-disabled'. So you could add this to your stylesheet: `.keen-slider[data-keen-slider-disabled]{ display: none; }`

worked for me, thanks you
