### ISSUE TITLE
slideChanged firing when attempting to slide to where no slides exist

### ISSUE THREAD

**Issue by hotscotch92** [rcbyr/keen-slider#67]
With `loop: false`, if you try to go to left of first slide or right of last slide, `slideChanged` is still fired with what would be the prev/next slide number even though said number shouldn't exist.

This could be an issue if say you want to hide the left nav button if you are focussed on the first slide via `if (KeenSlider.details().relativeSlide === 0) // then hide` with `loop: false`. If you try slide to left of first slide, `slideChanged` fires with `trackCurrentIdx` equalling -1 thus making `relativeSlide` equal `length - 1`. Which would briefly show the left nav button.

**Comment by rcbyr** [comment]
Thank you! Released with v5.3.5.
