### ISSUE TITLE
Please, more Vanilla.js examples!

### ISSUE THREAD

**Issue by Catsvilles** [rcbyr/keen-slider#7]
Just started using keen-slider in my Svelte/Sapper project and I hope it will go well. I plan to replace Siema (keen-slider seems to be even more lightweight?) but getting inspiration and converting existing examples from React to Svelte way is a bit of pain, I guess would be really cool for everyone if there would always be a Vanilla.js example a reference alongside already existing examples? (Not asking for Svelte ones, as this would be too much). Cheers!

**Comment by rcbyr** [comment]
Hey @Catsvilles,

thank you. I hope so, too. Please, let me know if something isn't right.
Currently, I'm porting all examples to angular and vue. I will be finished with that tomorrow. I'm sure that'll be of some help to you. But yes, I will also provide the examples in VanillaJS. I just need some time.

**Comment by Catsvilles** [comment]
@rcbyr Thanks for getting back to me! No rush at all, I just meant overall, that having those would be nice! I'm currently struggling with my first issue, can see only the first slider, rest are blank white spaces. I'm using first simple example, looks like it's CSS issue from my side. But one question, is importing keen-slider/keen-slider.min.css actually required?

**Comment by rcbyr** [comment]
@Catsvilles To get the basic behavior of the slider, you need to implement these styles.    You can also copy the styles to a place where you want to have them.
