### ISSUE TITLE
Problem with spacing

### ISSUE THREAD

**Issue by comertcimen** [rcbyr/keen-slider#70]
I am having a  problem with spacing on initial load. Spacing and slider is not working until i resize the window. I have set up 5 slides on desktop and 3 slides on mobile.

Desktop size first load

https://i.hizliresim.com/VEvAoB.png

Desktop size after resizing the window

https://i.hizliresim.com/v8H16L.png

Mobile size first load

https://i.hizliresim.com/cVESK5.png

Mobile size after resizing the window

https://i.hizliresim.com/02y1XX.png

**Comment by comertcimen** [comment]
Used slider.resize() to manually trigger the slider size.

**Comment by rcbyr** [comment]
Hey @comertcimen 

this is not a common problem. Can you give me a code example, so that I can reproduce your problem?

**Comment by comertcimen** [comment]
> Hey @comertcimen
> 
> this is not a common problem. Can you give me a code example, so that I can reproduce your problem?

Well, it is not a problem of keen slider. I was trying to render the slider while i was retriving async data from the server and map through it. I rendered the slider after all the data is received and the problem is solved.

`{Boolean (data.length) && <slider here>}`
