### ISSUE TITLE
Feature Request: Indicate if slider has reached beginning or ending

### ISSUE THREAD

**Issue by ruijdacd** [rcbyr/keen-slider#71]
Currently there isn't a reliable way to know if the slider has either reached the beginning or ending of the track, besides checking the `relativeSlide` on the details.

However this only works when the slider has one slide per view, since the last slide will always be considered visible.

By providing a similar implementation of Swiper (`isBeginning` and `isEnd`), we can easily do things such as disabling the navigation arrows, in order to mitigate extra clicks on the buttons by the user.

**Comment by ruijdacd** [comment]
The issue I reported can be fixed on _user land_, if the `slidesPerView` parameter is a `number`, by checking this:
```ts
const isBeginning: boolean = !options.loop && currentSlide === 0
const isEnd: boolean = !options.loop && typeof slider?.details().slidesPerView === "number" && currentSlide === slider?.details().size - slider?.details().slidesPerView
```

However if the parameter for `slidesPerView` is a function, that returns the size of each slide (width/height depending if it's horizontal or vertical respectively), it appears there is currently no way to know that unless we calculate based on the percentage of the track with the size of the last slide.

I wonder if these tweaks regarding these properties could land on the library, as I believe more people would rely on them for their own use cases.

I'd be happy to raise the necessary PRs for these features, along with others that I have been working on for the last couple of days, such as a11y (keyboard nav when slider is in focus), grouped slides, both bullet pagination and prev/next navigation (with support for grouped slides).

Hopefully by end of this week, I'll be available to start working on bringing these features to the lib itself and perhaps allowing for a better API consumption for react users (myself included).

**Comment by rcbyr** [comment]
Hey @ruijdacd 

thank you very much for describing this problem. If you don't have time for implementation and pull request, I would be happy if you create an issue.

You could have solved your problem with the 'progressSlides' property. This value indicates where the position of the slider is.  0 at the beginning and 1 at the end. While I was creating a codesandbox example for you, I realized that there is a rounding problem and therefore it doesn't work. So I have to fix it.

**Comment by ruijdacd** [comment]
Hey @rcbyr,

Thanks for the quick reply. I hope that next week, I'll have some time free to help out with these features.

As for the `progressSlides` property, I did try it out, and I did notice the rounding problem you're mentioning, though this property would not fix my problem, as the progress is being counted based on the left side of the slider and not the whole width of it.

Forking one of your code examples on this issue https://github.com/rcbyr/keen-slider/issues/3#issuecomment-656535307, which is a layout that I would need to get working.

https://codesandbox.io/s/bold-brattain-4217i?file=/src/index.js

**Comment by stepanO** [comment]
I found the solution:

```
const isFirst = !details.loop && details.relativeSlide === 0;
const isLast = !this.loop && details.relativeSlide + details.slidesPerView === details.size;
```

**Comment by rcbyr** [comment]
The rounding bug is now fixed. https://codesandbox.io/s/pedantic-shadow-hfkph?file=/src/index.js

**Comment by Enkil11** [comment]
To determine if the slider has reached its end, I utilized the following condition:
slider.track.details.maxIdx === slider.track.details.rel

I hope this proves helpful to someone, as it was precisely what I sought when I came across this thread.
