### ISSUE TITLE
Feature Request: Second/next slide "peaking from off screen"

### ISSUE THREAD

**Issue by joelod** [rcbyr/keen-slider#72]
Hi, first of all, great job on this library.

I was wondering, is there a possibility to create an effect where the second/next slide is "peaking from off screen", when showing one slide at time? That would be usefull, for example for situations (on mobile) where related products exist.

All the best, and sorry if this something that is already possible with Keen Slider and I'm not figuring it out!

**Comment by rcbyr** [comment]
Hey @joelod 

thank you very much!

Check this out, hope it helps: https://codesandbox.io/s/async-cookies-3hjen?file=/index.html

**Comment by joelod** [comment]
Hey @rcbyr, this is great! Thank you very much!

**Comment by aaronstezycki** [comment]
Hi @rcbyr, quick question related to this... can slides be given this treatment whilst applying a max width? I've tried, but been unable to think of a way the slider options could handle this? 

I've also wanted to attempt some parallax functionality a lot like ... https://codepen.io/aaron-stez/pen/bGBObEY. I'm guessing it would be similar to this example... https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/master/media/zoom-out/javascript?file=/index.html but transformX the slides child img node?
