### ISSUE TITLE
Animation effect on autoplay

### ISSUE THREAD

**Issue by flowjoy** [rcbyr/keen-slider#74]
Thanks for this great library! 

I was wondering if it is possible to modify the autoplay feature (that calls .next) so that it's continous instead of snapping off to the next slide? I would like to create a continuous flow of images rolling by

**Comment by rcbyr** [comment]
Hey @flowjoy 

thank you very much. Unfortunately, it is not possible at the moment, but it will be very soon. I will let you know!

**Comment by flowjoy** [comment]
> Hey @flowjoy
> 
> thank you very much. Unfortunately, it is not possible at the moment, but it will be very soon. I will let you know!

Thats awesome, thanks! Do you have any estimate when it will be released? Just so I know how to proceed

**Comment by rcbyr** [comment]
Hey @flowjoy 

I wanted to release the version last month. But I had a lot of private stuff to do and not much time. I would say January is realistic.

**Comment by Bobeta** [comment]
@rcbyr Hi there, are there still plans to add this anytime soon? Seems like it didn't get solved in january

**Comment by danjonesdev** [comment]
@rcbyr Hi eric, any news on this? Would love to have some sort of 'animation-type option so I can also have a 'linear' scroll.

**Comment by PavelZhuravlev** [comment]
@rcbyr any updates here?

**Comment by rcbyr** [comment]
Sorry, but it took longer than expected. I have published a new version and added an example: https://keen-slider.io/examples#auto-move
