### ISSUE TITLE
slider.resize doesn't resize when content changes

### ISSUE THREAD

**Issue by emilkowalski** [rcbyr/keen-slider#75]
I'm using Vue and when I press the button to change the content of a slider the resize method doesn't trigger for some reason. 
Here's a demo: 
https://codesandbox.io/s/nervous-sutherland-lt87t?file=/src/Slider.vue

Followed this sandbox written in react where everything works as expected: 
https://codesandbox.io/s/keen-slider-multiple-react-forked-4xpgg?file=/src/App.js

**Comment by rcbyr** [comment]
Hey @emilkowalski 

you have to wait until the dom is updated. I have forked your demo: https://codesandbox.io/s/dry-cookies-vh9e9?file=/src/Slider.vue

Hope this helps!
