### ISSUE TITLE
Center a slide is behaving strange

### ISSUE THREAD

**Issue by HejdesGit** [rcbyr/keen-slider#76]
Hello,

I found a possible bug when trying to center a slide. Best explanation is to check the gif. 

![snapTo4](https://user-images.githubusercontent.com/893988/101166462-9cb35900-3638-11eb-8966-17a2dc580505.gif)

But I would say that expected behaviour would be to snap to the 4:number slider when the V-arrow is above the slide.
Would like the behaviour of the 'free-snap'-mode but with center.

I'm using chrome with "device toolbar" but it is doing the same without emulating phone.

Recreate/test:
https://codesandbox.io/s/charming-chaum-glt82?file=/src/App.js

**Comment by badtant** [comment]
Digging in this issue I ended up changing the moveSnapOne function.
How does that look @rcbyr ? 

```
const relativeMovement = touchIndexStart === trackCurrentIdx ? 0 : Math.abs(touchIndexStart - trackCurrentIdx) moveToIdx(touchIndexStart + (relativeMovement * trackDirection))
```

**Comment by rcbyr** [comment]
Hey @HejdesGit 

thanks for noticing me about this issue. I will have a look at that.

@badtant Thanks for digging. I didn't try your solution but at first glance, this will have an impact on the swipe experience. You have to swipe much further to change a slide.

**Comment by badtant** [comment]
Yes, that it true. But I think that is better then ending up on a slide that I wasn't near swiping to :)

**Comment by rcbyr** [comment]
This behavior is now fixed.
