### ISSUE TITLE
Feature Request: HTML should indicate the current slide

### ISSUE THREAD

**Issue by cmalven** [rcbyr/keen-slider#78]
In other slider libraries, it's fairly common for me to want to add a transition to the contents of a slide - for instance, animate in some text when the slide containing that text becomes visible. Most libraries will automatically add something like an `is-selected` class or a `data-is-selected` data attribute that I can use in CSS to toggle transitions.

Keen Slider doesn't seem to do this. I could enable this myself by adding event listeners and toggling these classes, but I'd rather not have to do this if it is something Keen could automatically do.

Would you consider adding this?

Thanks for your work on the project!

**Comment by ruijdacd** [comment]
Hello @cmalven,

Currently there aren't any classes or attributes being added to the current slide, though I agree with you, in that the library should add some sort of class/attribute to the current slide.

However as a temporary solution, you could hook into the `slideChanged` method, on the options object, and get the active slide (`relativeSlide`) and add the class to the respective element (don't forget to remove from the previously active slide).

I am aware that this is isn't the best solution, as the library should allow that (possibly through an option `slideActiveClass`).

I will look into adding this over the holidays, unless someone is eager to pick this one up instead :)

Have a great day! 👋

**Comment by rcbyr** [comment]
Hello @cmalven,

as you have mentioned you can build this feature easily by using the available event hooks. The idea behind this library is to be as simple and small as possible, but also powerful/empowering enough to accomplish anything you want. At the moment, this idea remains and will flow in the next major release (hopefully released in January - I'm still struggling with the API). I will keep your request in mind and find an elegant solution.

P.S. Thank you very much for your sponsoring.

**Comment by cmalven** [comment]
@ruijdacd Thanks for the response!

@rcbyr I respect your goal of keeping the library as simple as possible. I'll implement this manually for now.

**Comment by rrrrpppp** [comment]
Hello all,

have seen the issue because I also miss the active class. You can also just use the dots function for the active class setting of the slides.

This could then look like this:

````
var slidys = document.querySelectorAll(".keen-slider__slide")
slidys.forEach(function (slidy, idx) {
	idx === slide
	? slidy.classList.add("slidy--active")
	: slidy.classList.remove("slidy--active");
});
````

Just wanted to share it in case someone else is looking for it :)

**Comment by kostas-artware** [comment]
Hello,
I tried to implement the qat

> Hello all,
> 
> have seen the issue because I also miss the active class. You can also just use the dots function for the active class setting of the slides.
> 
> This could then look like this:
> 
> ```
> var slidys = document.querySelectorAll(".keen-slider__slide")
> slidys.forEach(function (slidy, idx) {
> 	idx === slide
> 	? slidy.classList.add("slidy--active")
> 	: slidy.classList.remove("slidy--active");
> });
> ```
> 
> Just wanted to share it in case someone else is looking for it :)

Hey  @rrrrpppp ,

Thank you for the snippet. I used it and it kinda works.  
Altough it adds the slick-class on the first slide It's not updating on the next slide? Is there anything I'm missing.
