### ISSUE TITLE
Bug when `loop: true` with a slider containing 1 photo

### ISSUE THREAD

**Issue by baptisteArno** [rcbyr/keen-slider#81]
Hi, thank you for this amazing library.
It looks like there is a motion bug when the `loop` argument is set to `true` and there is only 1 photo in the slider.

**Comment by rcbyr** [comment]
Yes, you're right. Thanks for reporting. Will be fixed this week.

**Comment by rcbyr** [comment]
Hey @baptisteArno 

I fixed that with the current release v5.4.0. Thanks again.

**Comment by baptisteArno** [comment]
Thank you @rcbyr, amazing work!
