### ISSUE TITLE
Picker inside slide

### ISSUE THREAD

**Issue by AlessandroAnnini** [rcbyr/keen-slider#83]
Hi, I am trying to use the picker inside a slide but it won't work because the click on the wheel is used only for the slide move.
is there a way to set a threshold for the slide movement or to prevent the event propagation from the inner picker to the slide?
Thanks

**Comment by rcbyr** [comment]
Hey @AlessandroAnnini

documentation is missing for this. Sorry for that. You can use the class 'data-keen-slider-pe' to prevent events inside a slide.

**Comment by AlessandroAnnini** [comment]
@rcbyr tnx for your fast response, I am trying here: https://codesandbox.io/s/mystifying-waterfall-e0rrs?file=/src/App.js
slide 3, which has Page3 component in it, contains the picker but I can't seem to make it work with that attribute.
Do you have the time to take a look?

**Comment by rcbyr** [comment]
Okay, you've found a bug. I will take care of this.

**Comment by rcbyr** [comment]
Is fixed.
