### ISSUE TITLE
Change of slides does not refresh slider

### ISSUE THREAD

**Issue by ASgmbv** [rcbyr/keen-slider#86]
Hi, thank you for a great library!

Recently I had a bug similar to this: [https://codesandbox.io/s/keen-slider-cn8g9](https://codesandbox.io/s/keen-slider-cn8g9), when you change slides slider behaves weirdly, ex: some slides do not show up, some extra empty slides are added. 

I could fix this like this: [https://codesandbox.io/s/keen-slider-2-04qrq](https://codesandbox.io/s/keen-slider-2-04qrq)

If you have some time could you look at it, is this an expected behavior or a bug and library should handle this?

Thank you!

**Comment by rcbyr** [comment]
Hey @ASgmbv 

thanks for using the library. Yes, the behavior is correct, since the slider does not observe the slides. Your fix is correct, but you can use the function resize as well since it does less than the refresh, which recreates the whole slider.

**Comment by sivasankar9** [comment]
Hi,
use slider.refresh() it updates the newly added dom elments with drag functionality.

  let [sliderRef, slider] = useKeenSlider({
    slidesPerView,
  });
  useEffect(() => {
    slider && slider.refresh();
  }, [children]);

**Comment by osorvr** [comment]
> Hi, use slider.refresh() it updates the newly added dom elments with drag functionality.
> 
> let [sliderRef, slider] = useKeenSlider({ slidesPerView, }); useEffect(() => { slider && slider.refresh(); }, [children]);

Hi @sivasankar9 

I added text to each slider but I want them to refresh and make the animation work every time you change the slider... How would you go about this using vanilla js.

**Comment by rv-ragul-guvi** [comment]
> Hi, thank you for a great library!
> 
> Recently I had a bug similar to this: https://codesandbox.io/s/keen-slider-cn8g9, when you change slides slider behaves weirdly, ex: some slides do not show up, some extra empty slides are added.
> 
> I could fix this like this: https://codesandbox.io/s/keen-slider-2-04qrq
> 
> If you have some time could you look at it, is this an expected behavior or a bug and library should handle this?
> 
> Thank you!

I am also facing this issue. Can you tell me what you have done to solve this?
