### ISSUE TITLE
Reset autoplay timer when user manually changes slides

### ISSUE THREAD

**Issue by ghost** [rcbyr/keen-slider#89]
Hi, just want to preface this by saying I really like this slider and I think it's one of the best React carousel solutions out there.

I'm wondering if it's possible to reset the autoplay timer whenever a user manually changes slides i.e. by dragging onto the next slide or pressing the arrows or dots navigation.

Currently, I believe the timer is independent of any user action which can throw the rhythm of the UX off. For example, if the autoplay is set to 5 seconds and the user manually changes slides 4 seconds in, the user will only be on the new slide for 1 second.

I'd appreciate any help configuring this so that the autoplay timer is reset whenever the user manually changes slides. So in the example above, after the user manually changes slides 4 seconds in, the user will be on the new slide for the full 5 seconds.

I've tried a few things but can't seem to crack this.

    export const Slideshow = () => {
  
	  const [currentSlide, setCurrentSlide] = React.useState(0)
	  const [pause, setPause] = React.useState(false)
	  const timer = React.useRef()
	  const [sliderRef, slider] = useKeenSlider({
		  loop: true,
		  initial: 0,
		  duration: 1000,
		  slideChanged(s) {
			  setCurrentSlide(s.details().relativeSlide)
		  },
		  dragStart: () => {
			  setPause(true)
		  },
		  dragEnd: () => {
			  setPause(false)
			  // Some code here that resets the timer?
		  },
	  })
  
	  React.useEffect(() => {
		  sliderRef.current.addEventListener('mouseover', () => {
			  setPause(true)
		  })
		  sliderRef.current.addEventListener('mouseout', () => {
			  setPause(false)
		  })
	  }, [sliderRef])
  
	  React.useEffect(() => {
		  timer.current = setInterval(() => {
			  if (!pause && slider) {
				  slider.next()
			  }
		  }, 5000)
		  return () => {
			  clearInterval(timer.current)
		  }
	  }, [pause, slider])
  
	  return (
		  <div ref='sliderRef' className='keen-slider'>
			  <div className='keen-slider__slide'>1</div>
			  <div className='keen-slider__slide'>2</div>
			  <div className='keen-slider__slide'>3</div>
		  </div>
		  {slider && (
			  <div className='dots'>
				  {[...Array(slider.details().size).keys()].map((idx) => {
					  return (
						  <button
							  key={idx}
							  onClick={() => {
								  slider.moveToSlideRelative(idx)
								  // Some code here that resets the timer?
							  }}
							  className={'dot' + (currentSlide === idx ? 'active' : '')}
						  />
					  )
				  })}
			  </div>
		  )}
	  )
    }

**Comment by rcbyr** [comment]
Hey @wanglophile 

sorry for the late answer. I have tried everything, but I could not reproduce the behavior you describe. The timer is reset when pause or slider is changed. Could you give me a "working" example as a repo or codesandbox?

**Comment by wanglophile** [comment]
Hey, so after a bit more investigation, it seems like the the behavior I described only happens when you manually change auto-playing slides via the dots navigation.

Changing slides by manually sliding or using the arrows navigation works fine and will reset the timer.

Here's a codesandbox: https://codesandbox.io/s/new-architecture-uxwst?file=/src/App.js

**Comment by ruijdacd** [comment]
@wanglophile in that case I would change the pausing behaviour to do `setPause(true)` on the `move` hook and `setPause(false)` on `afterChange` since that one gets triggered after the slider has finished changing.

**Comment by rcbyr** [comment]
I have rebuilt this example with the new main version. The problem is fixed there. Check this out: https://keen-slider.io/examples#auto-switch
