### ISSUE TITLE
Fullscreen & Thumbnail Navigation Feature Request

### ISSUE THREAD

**Issue by schellenbergk** [rcbyr/keen-slider#9]
The title speaks for itself :)

**Comment by rcbyr** [comment]
Thanks, I really needed some ideas for more examples/use cases. I hope I will be able to implement those soon.

**Comment by schellenbergk** [comment]
Hi @rcbyr,

Good examples are:

https://flickity.metafizzy.co/api.html#fullscreen
https://flickity.metafizzy.co/options.html#asnavfor

**Comment by robertimes** [comment]
I second that. 
A multiple slider sync is what this needs, basically you create two different sliders and one acts as thumbnails and can control the main slider - that's how Flickity and Swiper do it.

**Comment by ChipRyan** [comment]
This would be absolutely great! Any chance this could be implemented soon?

**Comment by mamat14** [comment]
it's a bit hard to synchronize two sliders(both having control over current slide) using current api.

**Comment by jgrauel** [comment]
I agree it would be really nice to have thumbnails via multiple slider sync. Any update on this feature?

**Comment by Filip1139** [comment]
Any update?

**Comment by rcbyr** [comment]
Sorry for let you waiting. I released a new major version and created an example for that case. (thumbnail/slider sync)

The fullscreen thing should be a no brainer.

**Comment by gcerni** [comment]
> Sorry for let you waiting. I released a new major version and created an example for that case. (thumbnail/slider sync)
> 
> The fullscreen thing should be a no brainer.

@rcbyr what about having something similar to colorbox, where clicking on an image, will open that full screen?
