### ISSUE TITLE
More elegant dots navigation for looping first and last slides

### ISSUE THREAD

**Issue by wanglophile** [rcbyr/keen-slider#90]
Say you have six slides (1, 2, 3, 4, 5, 6) and you've enabled looping and dots navigation for a horizontal right-to-left slideshow.

When you are on the last slide and you click the 1st dot, the slider will scroll left and go over slides 5, 4, 3, and 2 before reaching the first slide.

How can we set it up so that the slider will instead scroll right once and go directly to the intended first slide?

There is the same problem if you're on the 1st slide and you click the last dot - currently, it scroll right over all the other slides (2, 3, 4, 5) to get to 6 instead of scrolling left once to get to 6 directly.

Same issue if it's vertical and/or left-to-right slideshow.

Here's a codeandbox: https://codesandbox.io/s/new-architecture-uxwst?file=/src/App.js

**Comment by rcbyr** [comment]
Hey @wanglophile 

sorry for the late answer.

This problem was solved in #4.
