### ISSUE TITLE
Multiple instances per page

### ISSUE THREAD

**Issue by saschabregenhorn** [rcbyr/keen-slider#92]
Are multiple slider instances with same options and without specific IDs on one page possible? If, how? Thanks!

**Comment by avinash-vllbh** [comment]
@saschabregenhorn Yes it's possible, you can imagine a slider instance is tied to a DOM node. As long as you have different nodes identifiable uniquely, you can instantiate a slider for each and they should work independently of each other.
e.g 
```javascript
const slider = new KeenSlider('#my-keen-slider')
const slider2 = new KeenSlider('#my-keen-slider2')
```
`#my-keen-slider` & `my-keen-slider2` are `id` attributes of two seperate DIVs/any DOM nodes.

**Comment by saschabregenhorn** [comment]
> @saschabregenhorn Yes it's possible, you can imagine a slider instance is tied to a DOM node. As long as you have different nodes identifiable uniquely, you can instantiate a slider for each and they should work independently of each other.

Thanks. My problem is, the slider instances can be added as content elements in a CMS, so I don't have specific IDs. Other sliders automatically handle instances via a class, so I am curious, if the keen slider can do this as well.

**Comment by rcbyr** [comment]
Hey @saschabregenhorn 

you can achieve by adding something like this to your site:
`
document.querySelectorAll('.sliders').forEach(slider => {
    new KeenSlider(slider)
})
`

**Comment by saschabregenhorn** [comment]
> you can achieve this by adding something like that to your site:
> `document.querySelectorAll('.keen-slider').forEach(slider => { new KeenSlider(slider) })`

Thanks for the quick reply. The sliders are initialized now, but the navigation (arrows + bullets) controls all instances. Here's my code. 

`document.querySelectorAll('.keen-slider').forEach(slider => {
    
      new KeenSlider(slider, {
        loop: true,
        slides: '.keen-slide',
        slidesPerView: 1,
        spacing: 20,
        breakpoints: {
          '(min-width: 480px)': {
            slidesPerView: 2
          },
          '(min-width: 720px)': {
            slidesPerView: 3
          }
        },
        created: function(instance) {
    
          document
            .getElementById("arrow-left")
            .addEventListener("click", function() {
              instance.prev();
            });
    
          document
            .getElementById("arrow-right")
            .addEventListener("click", function() {
              instance.next();
            });
    
          var dots_wrapper = document.getElementById("dots");
          var slides = document.querySelectorAll(".keen-slide");
    
          slides.forEach(function(t, idx) {
            var dot = document.createElement("button");
            dot.classList.add("dot");
            dots_wrapper.appendChild(dot);
            dot.addEventListener("click", function() {
              instance.moveToSlide(idx);
            });
          });
    
          updateClasses(instance);
    
        },
    
        slideChanged(instance) {
          updateClasses(instance);
        }
    
      });
    
    })
    
    function updateClasses(instance) {
    
      var slide = instance.details().relativeSlide;
      var arrowLeft = document.getElementById("arrow-left");
      var arrowRight = document.getElementById("arrow-right");
    
      slide === 0
        ? arrowLeft.classList.add("arrow--disabled")
        : arrowLeft.classList.remove("arrow--disabled");
    
      slide === instance.details().size - 1
        ? arrowRight.classList.add("arrow--disabled")
        : arrowRight.classList.remove("arrow--disabled");
    
      var dots = document.querySelectorAll(".dot");
    
      dots.forEach(function(dot, idx) {
        idx === slide
          ? dot.classList.add("dot--active")
          : dot.classList.remove("dot--active");
      });
    
    }


Thanks again!

**Comment by rcbyr** [comment]
I've created an example for you.

https://codesandbox.io/s/magical-lehmann-v1f0w?file=/script.js

**Comment by saschabregenhorn** [comment]
> I've created an example for you.
> 
> https://codesandbox.io/s/magical-lehmann-v1f0w?file=/script.js

Works great, thank you very much for your time!

**Comment by SethKitchen** [comment]
Is there an example for React?

**Comment by pawandeore** [comment]
@saschabregenhorn  how do i give different parameters like  i want to loop 1 slider but i don't want to loop another one

**Comment by janstieler** [comment]
Hi,
I tried also to use the script for multiple sliders. First I changed it to the actual version and I got the error `details is not a function` so I changed it to the new `detailsChanged()`. But I got the same error.
To get a lighter sourcecode I deleted the dots part because I don't need them.
And I have take the height of the Slider to 300px and make them vertical and centered with 2 slides. Now the arrows have  problems to calculate the slide hight correct.

```javascript
function createSlider(wrapper) {
        new KeenSlider(wrapper.querySelector('.keen-slider'), {
            loop: true,
            slides: {
                origin: 'center',
                perView: 2,
                spacing: 10,
            },
            vertical: true,
            created: function (instance) {
                wrapper.querySelector(".arrow--top").addEventListener("click", function () {
                    instance.prev();
                });

                wrapper.querySelector(".arrow--bottom").addEventListener("click", function () {
                    instance.next();
                });

                updateClasses(instance);
            },
            slideChanged(instance) {
                updateClasses(instance);
            }
        });

        function updateClasses(instance) {
            var slide = instance.detailsChanged().relativeSlide;
            var arrowLeft = wrapper.querySelector(".arrow--top");
            var arrowRight = wrapper.querySelector(".arrow--bottom");
            
            slide === 0
                ? arrowLeft.classList.add("arrow--disabled")
                : arrowLeft.classList.remove("arrow--disabled");
                
            slide === instance.detailsChanged().size - 1
                ? arrowRight.classList.add("arrow--disabled")
                : arrowRight.classList.remove("arrow--disabled");
        }
    }

    document.querySelectorAll('.slider-wrapper').forEach((wrapper) => {
        createSlider(wrapper);
    });
    ```
    Hopefull someone can help me?
    
    Best
