### ISSUE TITLE
Slider gets stuck on the tab's first loading and is aligned to the right side of the screen when slides width less than window's width

### ISSUE THREAD

**Issue by hirashuriken** [rcbyr/keen-slider#93]
Hi, @rcbyr 
Could you please help me with an issue, I updated your codesandbox example which you attached for the opened issue (https://github.com/rcbyr/keen-slider/issues/3) and found few problems. 

**Codesandbox:** https://codesandbox.io/s/unruffled-snow-fx3dc?file=/src/index.js

**First issue:**
Steps:
1. Open codesandbox
2. Reload browser tab by pressing F5 or ctrl+R

Expected result:
1. Slider works in a free mode, spacing is applied to sliders

Actual result:
1. Slider is stuck

**Second issue:**
Steps:
1. Open codesandbox
2. Refresh screen
3. Increase size of the screen to more than a sum of sliders width

Expected result:
1. Slides are aligned on the left side of the screen

Actual result:
1. Slides are aligned on the right side of the screen

**Video approve:**
https://www.loom.com/share/9d780a660a164256889d536d0a996aec

**Comment by hirashuriken** [comment]
Hi @rcbyr 
Sorry for interrupting you but maybe you had a chance to check this issue? T___T

**Comment by rcbyr** [comment]
Sorry for not responding to this issue. The problems should be gone with the actual version.
