### ISSUE TITLE
Add or remove slides without jumping?

### ISSUE THREAD

**Issue by alancwoo** [rcbyr/keen-slider#94]
Is there any way to add or remove slides without the slider jumping?

I'm trying to show the starting slide only once then remove it after changing, which causes the slider to jump to the next item once `resize()` is called.

Fairly crude example here: https://codesandbox.io/s/icy-dew-hzfp5?file=/src/Slider.vue

```
<div ref="slider" class="keen-slider">
    <div v-if="showFirst" class="keen-slider__slide number-slide1">1</div>

...

mounted() {
    this.slider = new KeenSlider(this.$refs.slider, {
      loop: true,
      afterChange: (slider) => {
        if (this.showFirst && slider.details().relativeSlide !== 0) {
          this.showFirst = false;
          slider.refresh();
        }
      },
    });
  },
```

**Comment by rcbyr** [comment]
Hey @alancwoo,

I made it work and hope it helps: https://codesandbox.io/s/naughty-sanderson-9vvip?file=/src/Slider.vue

**Comment by alancwoo** [comment]
Sorry for the incredible delay, thank you for the help and for this great library :)
