### ISSUE TITLE
Strange behavior on Firefox Android 

### ISSUE THREAD

**Issue by badalexander** [rcbyr/keen-slider#95]
Dear all

I have tested the slider in firefox on android and when swiping right to left it bounces back so intead of going from slider 1 -> 2 it goes sometimes backwards moves to the right. But only in firefox. How can I fix this. Any help would be appreciated. Cause the code looks great and the size is wow.

**Comment by rcbyr** [comment]
Hey,

I tried to reproduce the described behavior but it works fine on my device. Could you give me the device name, android version and firefox version?

**Comment by badalexander** [comment]
Firefox 85.1.3
Android version 9
Phone: Xiaomi Mi A1

**Comment by badalexander** [comment]
I have created a short video with one of the samples cannot see the thumb but I think it;s obvious the behavior
[https://1drv.ms/u/s!At7y1Fb4sraYjiojyYZmNGpnix6z?e=pkdm9Q](url)

**Comment by rcbyr** [comment]
Could not reproduce that and hope the problem is gone with the new version.
