### ISSUE TITLE
How do I listen to drag end

### ISSUE THREAD

**Issue by VincentVToscano** [rcbyr/keen-slider#96]
Hi,

Thank you for creating an awesome slider and making it publicly available. I'd like to be able to listen to when a user has finished dragging the slider. Could you point me in the direction on how best to do that?
THANK YOU

**Comment by rcbyr** [comment]
Hey @VincentVToscano, 

thanks for using the slider. 
See the link for your problem: https://codesandbox.io/s/empty-feather-vyb4s?file=/index.html

**Comment by VincentVToscano** [comment]
> Hey @VincentVToscano,
> 
> thanks for using the slider.
> See the link for your problem: https://codesandbox.io/s/empty-feather-vyb4s?file=/index.html

Thank you kindly. Have a great week!
