### ISSUE TITLE
Adaptive height support

### ISSUE THREAD

**Issue by dmorda** [rcbyr/keen-slider#98]
I looked at the documentation, but didn't see anything that indicated that the slider could adjust its height dynamically based on the content in the slide.

Is that currently supported, if not, would you consider adding it?

**Comment by HamzaInPerth** [comment]
same here!

**Comment by rcbyr** [comment]
Hello @dmorda 

sorry for the late answer. Here is an example with the new version: https://keen-slider.io/examples#adaptive-height

**Comment by braincore** [comment]
@rcbyr Any recommendation if the height of a slide is dynamic without an explicit height set?

**Comment by derekphilipau** [comment]
@braincore I also needed the height to be dynamic based on images with varying aspect ratios:
```
<div class="keen-slider">
  <img src="1.jpg" class="keen-slider__slide" />
  <img src="2.jpg" class="keen-slider__slide" />
</div>
```
The hack I came up with was to manually calculate the height in slideChanged() and created().  (With the caveat that the images must have already been loaded so that natural dimensions exist.)
```
const newHeight =
  s.slides[s.track.details.rel].offsetWidth
  * s.slides[s.track.details.rel].naturalHeight
  / s.slides[s.track.details.rel].naturalWidth;
s.container.style.height = newHeight + "px";
```

**Comment by grazianodev** [comment]
+1 for adding dynamic height support

**Comment by ayoubkhan558** [comment]
We can use adaptive height for keen slider, here is example code for react.
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/misc/adaptive-height/react?file=/src/App.js
